// Auto-assembled from SWD(2026) 616 (5 parts, 958 pp) — ETS review impact assessment,
// 17 July 2026. Findings were AI-extracted (Sonnet agents, one per part) and are
// pending human verification; every entry carries its PDF part + page and, where
// rendered, a page screenshot under /data/impact-assessment/shots/.

export type IaCategory =
  | 'carbon-price' | 'mitigation-cost' | 'scenarios' | 'technology-scaling'
  | 'industry' | 'macro' | 'removals' | 'other';

export interface IaFinding {
  id: string; title: string; category: IaCategory; part: number;
  keyNumbers: string[]; figureOrTable: string; pdfPages: number[];
  whyImportant: string; quote: string; shots: string[];
}

export const IA_PARTS: Record<number, string> = {
  1: "Part 1 — Main report",
  2: "Part 2 — Annexes 1–7",
  3: "Part 3 — Annexes 8–11",
  4: "Part 4 — Annexes 12–14",
  5: "Part 5 — Annex 15 (evaluation)",
};

export const IA_FINDINGS: IaFinding[] = [
  {
    id: "cap-trajectories-2040",
    title: "EU ETS cap trajectories to 2040 (CAP1/CAP2/CAP3)",
    category: "scenarios",
    part: 1,
    keyNumbers: ["2030 cap: 911 Mt (all cap options)", "2035 cap: 560-670 Mt range across CAP1/CAP2/CAP3", "2040 cap: 330-375 Mt gross emissions", "LRF 2030-2035: 2.5-3.3%; LRF 2035-2040: 2.1-2.7%", "Carbon budget 2031-2040: 5,605-6,295 Mt CO2 (PRIMES/POTEnCIA range)"],
    figureOrTable: "Table 2 / Table 3",
    pdfPages: [28, 29],
    whyImportant: "Gives the actual modelled ETS cap/linear-reduction-factor pathway underlying the 2040 climate target, the core reference for the ETS's contribution to -85%/-90% net GHG reduction.",
    quote: "CAP2: Default modelled trajectory to 85%: it follows the 2031-2040 trajectory of GHGs currently under ETS towards the estimated cost-effective contribution of the EU ETS to a reduction of economy-wide net GHGs by 85% in 2040.",
    shots: ["p1-028-cap-trajectories.png", "p1-029-cap-trajectories-2.png"],
  },
  {
    id: "msr-eua-price-index",
    title: "Indexed EUA price evolution under MSR reform options",
    category: "carbon-price",
    part: 1,
    keyNumbers: ["PO1 (MSR1, static parameters): price rises to 2029, declines 2029-2034, then steep increase to 2040", "PO2/PO3 (MSR3, dynamic declining parameters): monotonic, steady price increase 2028-2040", "Modelled with POLES-Enerdata supply-demand equilibrium model, indexed to 2028"],
    figureOrTable: "Figure 5",
    pdfPages: [51, 52],
    whyImportant: "The only explicit carbon-price trajectory figure in the report, showing how MSR design choices reshape the EUA price path to 2040 and its stability for investors.",
    quote: "For PO2 and PO3, the MSR3 design allows for a monotonic and steady increase in the price throughout the period, indicative of a healthy supply-demand balance on the market.",
    shots: ["p1-052-msr-eua-price-paths.png"],
  },
  {
    id: "tnac-emissions-ratio",
    title: "TNAC-to-emissions ratio (market liquidity) by policy option",
    category: "carbon-price",
    part: 1,
    keyNumbers: ["2027 TNAC-to-emissions ratio: ~0.6 in all options", "PO1 range 2027-2040: 0.29-0.68 (u-shaped, low point 0.29 in 2036)", "PO2 range: 0.28-0.59", "PO3 range: 0.25-0.59"],
    figureOrTable: "Figure 6",
    pdfPages: [53, 54],
    whyImportant: "Quantifies market liquidity/tightness outcomes of MSR reform - a key indicator of price-stability and trading-friction risk as the market shrinks.",
    quote: "The spread of the ratio for the 2027-2040 period is slightly lower for PO2 (0.28-0.59) than for PO3 (0.25-0.59), although both are within an acceptable range.",
    shots: ["p1-053-tnac-emissions-ratio.png"],
  },
  {
    id: "idb-abatement-cost",
    title: "Industrial Decarbonisation Bank (IDB): abatement volume and unit cost",
    category: "mitigation-cost",
    part: 1,
    keyNumbers: ["Cumulative abatement: 1,630 MtCO2 over ten years", "Budget: EUR 100 billion (ten annual rounds of EUR 10bn each)", "Weighted average awarded support: EUR 60/tCO2 abated", "Direct investment leverage effect: 5%-75% (weighted average 45% across modelled projects)"],
    figureOrTable: "Figure 4 / text (Section 6.1.1.4, 6.2.3.2)",
    pdfPages: [34, 67],
    whyImportant: "The headline EUR/tCO2 cost-effectiveness and leverage figures for the EU's flagship EUR 100bn industrial decarbonisation instrument.",
    quote: "This analysis indicates a cumulative GHG emission abatement of 1630 MtCO2 over a ten-year period, based on a total budget of EUR 100 billion allocated across ten yearly auction rounds, each of EUR 10 billion funding volume.",
    shots: ["p1-034-idb-cost-effectiveness.png"],
  },
  {
    id: "energy-system-costs-gdp",
    title: "Industry energy system costs as % of GDP and annual investment needs (CAP3 '9085' scenario)",
    category: "mitigation-cost",
    part: 1,
    keyNumbers: ["Industry energy system costs: 2.0-2.3% of GDP (2030), 2.1-2.4% (2035), 2.2-2.3% (2040)", "Annual industry investment: EUR 30-45bn (2021-2030), EUR 30-40bn (2031-2040), ~0.2% of GDP", "Supply-side (power+fuels) investment: EUR 110-175bn/year, 0.6-0.8% of GDP", "CAP4 'accelerated 9085' raises whole-decade energy costs +3.4% for industry vs CAP3"],
    figureOrTable: "Table 8 / Table 9 / Table 10 / Table 11",
    pdfPages: [64, 65, 66],
    whyImportant: "Directly quantifies the mitigation cost burden on industry as a share of GDP and by investment timing, comparing linear vs front-loaded cap trajectories.",
    quote: "Energy system costs as % GDP (including auction payments) ... Industry 2.0%; 2.3% / 2.1%; 2.4% / 2.2%; 2.3%",
    shots: ["p1-064-energy-system-costs.png", "p1-065-industry-investment-needs.png"],
  },
  {
    id: "removals-net-gross-targets",
    title: "Carbon removals integration: eligible volumes and net/gross emissions objectives",
    category: "removals",
    part: 1,
    keyNumbers: ["Eligible removals (BioCCS+DACCS) modelled for 85% scenario: 175-330 Mt by 2040", "PO1 (public purchase, CR4): modelling shows overachievement at 222 Mt vs 175 Mt target", "PO2 (operator integration, CR1): 110 Mt of removals generated on top of net cap", "By 2040 removals can cover 10-13% of gross ETS emissions"],
    figureOrTable: "text (Section 6.1.1.2, Annex 8 Table 3)",
    pdfPages: [29, 30],
    whyImportant: "Sets the quantitative scale (Mt) of the EU ETS's planned reliance on permanent carbon removals to hit its 2040/2050 targets, and how integration design changes delivered volumes.",
    quote: "The net objective for each policy option is the gross emissions limit in that option minus an amount of eligible removals modelled for the 85% scenario of between 175 and 330 Mt.",
    shots: ["p1-029-cap-trajectories-2.png"],
  },
  {
    id: "removals-public-purchase-fiscal-cost",
    title: "Fiscal cost of PO1 public removals-purchasing programme",
    category: "removals",
    part: 1,
    keyNumbers: ["Upfront investment for 173 Mt BioCCS/DACCS by 2040: EUR 35.7bn (mid-point), range EUR 29-43bn", "Net fiscal cost after removal-backed allowance sales: EUR 3 billion"],
    figureOrTable: "text (Section 6.2.5.1, Annex 8)",
    pdfPages: [81],
    whyImportant: "A rare explicit public-fiscal-cost estimate (not just EUR/tCO2) for scaling up engineered/biogenic CDR via the ETS.",
    quote: "It estimates the total investment requirements for achieving net emissions reduction target of 85% with the ETS integration of 173 Mt of BioCCS and DACCS (PRIMES modelling result) by 2040 at EUR 35.7 billion based on the mid-point technology costs.",
    shots: [],
  },
  {
    id: "free-allocation-volumes",
    title: "Free allocation volumes and value, and cross-sectoral correction factor",
    category: "industry",
    part: 1,
    keyNumbers: ["Baseline free allocation: 778 million EUAs (2031-2040)", "Policy option range: 487-990 million EUAs, worth EUR 70-170bn (vs EUR 110bn+ baseline)", "Cross-sectoral correction factor (CSCF): applied in most years, ranging 0.92 to 0.36 depending on scenario", "PO2 conditional-investment requirement: EUR 50-90bn induced investment"],
    figureOrTable: "text (Section 6.2.1.6, 6.2.3.5; Annex 12 Table 12)",
    pdfPages: [57, 74],
    whyImportant: "Quantifies the scale of industrial free allocation (a major carbon-leakage protection lever) in volume and euro terms across policy options.",
    quote: "the resulting free allocation will range between 487 and 990 million EUAs over the period 2031-2040 ... between aproximately 70 - 170 billion EUR for the policy scenarios",
    shots: [],
  },
  {
    id: "gem-e3-macro-impacts",
    title: "GEM-E3 macroeconomic impacts (GDP, employment, consumption) by policy option",
    category: "macro",
    part: 1,
    keyNumbers: ["GDP change vs baseline 2040: +0.01% (PO1), -0.01% to 0.00% (PO2), +0.02% (PO3)", "Sectoral (ETS) employment change: +0.01% (PO1), -0.05% to -0.03% (PO2), -0.06% (PO3)", "Total private consumption change: +0.02% (PO1), -0.08% to -0.05% (PO2), -0.10% (PO3)", "GDP increase overall ranges 0.00% (PO2_50) to 0.08% (PO3R) vs reference"],
    figureOrTable: "Table 15",
    pdfPages: [98],
    whyImportant: "The report's core macroeconomic modelling output (GEM-E3), quantifying GDP, employment and consumption effects of carbon-leakage design choices - the standard macro reference metric.",
    quote: "The GDP increase ranges from 0.00% under PO2_50 to 0.08% under PO3R, with the latter achieving the highest GDP level due to the combined effect of a lower carbon price and stronger household demand.",
    shots: ["p1-098-gem-e3-macro-summary.png"],
  },
  {
    id: "maritime-social-npv",
    title: "Social Net Present Value of maritime policy options",
    category: "mitigation-cost",
    part: 1,
    keyNumbers: ["Monetised GHG benefits: EUR 22,075m (PO2) / EUR 27,790m (PO3)", "Additional abatement costs (excl. ETS revenue): -EUR 14,404m (PO2) / -EUR 16,171m (PO3)", "Social NPV: EUR 7,283m (PO2) / EUR 10,778m (PO3), both vs PO1"],
    figureOrTable: "Table 17",
    pdfPages: [99],
    whyImportant: "A rare full cost-benefit (NPV) calculation in the report, directly comparing monetised abatement benefits against compliance/admin costs for a specific sector.",
    quote: "Results presented in Table 17 show that both PO2 and PO3 would lead to a positive social NPV, compared to PO1.",
    shots: ["p1-099-maritime-npv-options-scoring.png"],
  },
  {
    id: "aviation-emissions-scenarios",
    title: "Global international aviation CO2 emissions and carbon-price coverage by option",
    category: "scenarios",
    part: 1,
    keyNumbers: ["2024 baseline emissions: 690 Mt CO2", "Baseline 2040: 590 Mt, of which 155 Mt ETS-covered, 435 Mt unpriced", "PO1 2040: 600 Mt, only 45 Mt ETS-covered, 555 Mt unpriced", "PO2/PO3 2040: 595 Mt, 95 Mt ETS-covered, 500 Mt unpriced", "CORSIA structurally exempts ~500 Mt CO2/year"],
    figureOrTable: "Table 5 / Table 6",
    pdfPages: [38, 39, 40, 41],
    whyImportant: "Shows how much of global aviation's climate impact remains unpriced under each policy option - central to assessing the EU's 'fair share' contribution via ETS vs CORSIA.",
    quote: "Emissions are highest under PO1, where the ETS geographic scope of 2026 continues to apply, and no extra support for the uplift of SAF is set aside.",
    shots: ["p1-038-aviation-emissions-options.png"],
  },
  {
    id: "industrial-tech-deployment",
    title: "Industrial decarbonisation technology deployment (steel, cement, chemicals)",
    category: "technology-scaling",
    part: 1,
    keyNumbers: ["Steel: pre-capture emissions cut by more than half via hydrogen direct reduction; 20-40% of remainder via CCS; residual ~35 Mt", "Cement/non-metallic minerals: 70-100 Mt captured via CCS; residual emissions ~35-40 Mt", "Chemicals: ~50% pre-capture emissions cut via electrification/biomass/hydrogen; ~1/3 of remainder captured", "Other industry: 60-70% emissions cut mostly via electrification", "Electrification could supply up to 90% of Europe's industrial heat demand by 2035"],
    figureOrTable: "text (Section 6.2.3.1, referencing 2040 Climate Target IA Part 3)",
    pdfPages: [44, 63, 64],
    whyImportant: "The most concrete sector-by-sector technology-mix numbers (hydrogen DRI, CCS Mt, electrification %) for how EU heavy industry is modelled to decarbonise by 2040.",
    quote: "For steel modelling shows a large reduction in pre-capture emissions by more than half due to a strong decrease in blast furnace use, substituted by hydrogen direct reduction technologies.",
    shots: ["p1-064-energy-system-costs.png"],
  },
  {
    id: "cdr-employment-and-auction-revenue",
    title: "CDR industry job creation and cumulative ETS auction revenue",
    category: "macro",
    part: 1,
    keyNumbers: ["CDR sector could support up to 670,000 jobs across Europe by 2050", "By 2035, CDR sector could support 125,000-180,000 jobs", "EEA aircraft operator employment by 2040 vs 2024: +28% (PO1), +26% (PO2/PO3)", "Cumulative ETS auction revenue 2031-2040: ~EUR 600bn to over 800bn, depending on policy option"],
    figureOrTable: "text (Sections 6.3.1.2, 6.3.1.4, 6.2.5)",
    pdfPages: [79, 86, 87],
    whyImportant: "Combines the report's clearest jobs-creation estimates for the emerging CDR industry with the overall fiscal scale (auction revenue) available to fund the transition.",
    quote: "They conclude that by 2050, the CDR sector in Europe could support up to 670,000 jobs.",
    shots: [],
  },
  {
    id: "options-comparison-preferred",
    title: "Final comparison of policy options and preferred option (PO2)",
    category: "other",
    part: 1,
    keyNumbers: ["Effectiveness ranking: PO1 '+', PO2 '+++', PO3 '++'", "Efficiency ranking: PO1 '++', PO2 '++', PO3 '+'", "Coherence ranking: PO1 '++', PO2 '+++', PO3 '++'", "Additional revenues vs baseline (Table 16): EUR 315bn (PO1), EUR 335bn (PO2), EUR 540bn (PO3)"],
    figureOrTable: "Table 18 / Table 16",
    pdfPages: [99, 102],
    whyImportant: "The Commission's own bottom-line scoring of the three policy options and its choice of PO2 as preferred - the single most decision-relevant summary in the report.",
    quote: "PO2 was considered to be the preferred policy option. Together, its measures strengthen the environmental effectiveness of the system while maintaining proportionality, regulatory stability, and fairness across sectors, and safeguarding competitiveness.",
    shots: ["p1-099-maritime-npv-options-scoring.png", "p1-102-options-revenues-comparison.png"],
  },
  {
    id: "baseline-cap-trajectory",
    title: "Baseline ETS cap trajectory to 2040",
    category: "scenarios",
    part: 2,
    keyNumbers: ["Cap 2030: 975 Mt", "Cap 2035: 485 Mt", "Cap 2040: 69 Mt", "LRF: -4.4%", "Cumulative budget 2031-2040: 4436 Mt"],
    figureOrTable: "Table 9 (Annex 7)",
    pdfPages: [106],
    whyImportant: "Defines the legally-legislated counterfactual cap path against which all policy options and carbon-price/abatement results are benchmarked.",
    quote: "Baseline: Cap 2030 (Mt) 975, Cap 2035 (Mt) 485, Cap 2040 (Mt) 69, LRF -4.4%, Budget 2031-2040 (Mt) 4436.",
    shots: ["p2-106-baseline-cap-table.png"],
  },
  {
    id: "preferred-option-emission-reduction",
    title: "Preferred option: 2040 GHG reduction outcome",
    category: "scenarios",
    part: 2,
    keyNumbers: ["85% emission reduction by 2040", "~-62% by 2030 vs 2005 levels"],
    figureOrTable: "text (Annex 3, Overview of Benefits table)",
    pdfPages: [36],
    whyImportant: "Headline environmental outcome of the preferred policy package, the single top-line number linking the ETS review to the 2040 climate target.",
    quote: "Achieves 85% emission reduction by 2040 (~-62% by 2030 compared to 2005 levels).",
    shots: [],
  },
  {
    id: "carbon-removal-purchasing-volume",
    title: "Carbon removals: public purchasing programme volume",
    category: "removals",
    part: 2,
    keyNumbers: ["175-330 MtCO2 removal via public purchasing programme", "170-330 Mt of additional allowances released", "fiscal cost estimated at EUR 3 bn"],
    figureOrTable: "text (Annex 3 benefits/costs tables)",
    pdfPages: [31, 36, 42],
    whyImportant: "Quantifies the scale and public fiscal cost of the preferred removals mechanism (BECCS/DACCS), a key CDR reference volume for the 2031-2040 period.",
    quote: "Regarding carbon removal, the preferred option is expected to lead to 175-330 MtCO2 removal through a public purchasing programme.",
    shots: [],
  },
  {
    id: "idb-abatement-and-investment",
    title: "Industrial Decarbonisation Bank (IDB): scale and abatement",
    category: "mitigation-cost",
    part: 2,
    keyNumbers: ["EUR 100 bn deployed over 10 years", "average direct leverage effect ~45%", "over 1,630 Mt CO2 abatement over 10 years of awarded projects"],
    figureOrTable: "text (Annex 3, Overview of Benefits)",
    pdfPages: [36, 38],
    whyImportant: "Central investment-support instrument for EU industrial decarbonisation; gives a concrete EUR/tCO2-abated scale (~EUR 61/t over 10yr on the EUR 100bn envelope) and leverage ratio for financing gap analysis.",
    quote: "The IDB can deliver over 1,630 Mt of CO2 abatement (over 10 years of operation of the awarded projects)... EUR 100bn, with average direct leverage effect estimated at 45%.",
    shots: [],
  },
  {
    id: "free-allocation-and-auction-revenue-change",
    title: "Free allocation increase and auction revenue increase vs baseline",
    category: "industry",
    part: 2,
    keyNumbers: ["Free allocation +42%-47% over 2031-2040 vs baseline", "Auction revenues +137%-146% vs baseline"],
    figureOrTable: "text (Annex 3, Overview of Benefits; Annex 12 Tables 12/21)",
    pdfPages: [38, 40],
    whyImportant: "Quantifies how much more carbon-leakage protection (free allocation) and how much extra public revenue the preferred option generates relative to current law.",
    quote: "Increased free allocation of 42%-47% over 2031-2040... Higher auction revenues (+137% - 146 %) compared to baseline.",
    shots: [],
  },
  {
    id: "aviation-compliance-cost-and-carbon-cost-share",
    title: "Aviation compliance costs and carbon-cost share of operating costs",
    category: "mitigation-cost",
    part: 2,
    keyNumbers: ["Compliance costs 36% lower in 2035 vs baseline", "Carbon costs rising to 5.4% of operating costs by 2030 (vs 10.8% in baseline)", "Fuel use 15% higher than baseline"],
    figureOrTable: "text (Annex 3 Table; Annex 5 competitiveness section 3.3)",
    pdfPages: [39, 91],
    whyImportant: "Direct sectoral cost-competitiveness metric showing the preferred option roughly halves aviation's carbon-cost burden relative to the baseline's narrower-scope-but-higher-price outcome.",
    quote: "Compliance costs are significantly lower compared to the baseline (36% lower in 2035)... rising to 5.4% of operating costs by 2030, compared to 10.8% in the baseline.",
    shots: [],
  },
  {
    id: "maritime-net-benefit-and-smaller-vessel-costs",
    title: "Maritime: net benefit and smaller-vessel ETS extension costs",
    category: "mitigation-cost",
    part: 2,
    keyNumbers: ["Net benefit EUR 7bn (preferred option)", "Smaller-vessel ETS extension: +EUR 1.2bn shipping costs (2030), +EUR 1.8bn (2040), +EUR 0.7bn (2050)"],
    figureOrTable: "text (Annex 3, Section 7.2 reference; Annex 3 cost table)",
    pdfPages: [39, 45],
    whyImportant: "Cost-benefit test (discounted emission savings vs abatement/admin costs) for the maritime package, plus a time profile of the direct cost of scope extension.",
    quote: "Maritime policy options are expected to yield a net benefit of EUR 7bn in the preferred option... Extension of ETS scope to smaller vessels increases shipping costs by EUR 1.2 bn in 2030, 1.8 billion in 2040 & 0.7 bn in 2050.",
    shots: [],
  },
  {
    id: "employment-and-trade-impact-range",
    title: "Employment and production/export impact ranges across policy options",
    category: "macro",
    part: 2,
    keyNumbers: ["Overall employment impact: -0.56% to +1.76%", "Production impact: -0.56% to +1.61%", "Export impact: -1.09% to +4.63%"],
    figureOrTable: "text (Annex 3 benefits table; Annex 5 Section 3.1, referencing Annex 12 GEM-E3 results)",
    pdfPages: [40, 90],
    whyImportant: "GEM-E3-modelled macro/sectoral sensitivity range across policy option variants - the key figure for bounding employment and competitiveness risk of ETS design choices.",
    quote: "Across sectors and policy measures, the overall employment impact ranges from -0.56% to 1.76... the impact on production and export across policy measures and sectors relative to the baseline ranges from -0.56% to 1.61% for production and -1.09% to 4.63% for exports.",
    shots: [],
  },
  {
    id: "eu-gdp-growth-assumptions",
    title: "EU GDP growth assumptions underpinning all scenarios",
    category: "macro",
    part: 2,
    keyNumbers: ["Real GDP +23% in 2030 vs 2015", "+39% in 2040 vs 2015", "+60% in 2050 vs 2015"],
    figureOrTable: "Figure 7 / text (Annex 4, Section 1.2.1)",
    pdfPages: [69],
    whyImportant: "Core macroeconomic input assumption (DG ECFIN Ageing Report-based) shared by PRIMES/GEM-E3/POLES across all scenarios - needed to interpret every downstream cost and price result.",
    quote: "At EU level, real GDP is projected to be 23% higher in 2030 than in 2015, 39% higher in 2040, and 60% higher in 2050 compared to 2015.",
    shots: ["p2-069-gdp-assumptions.png"],
  },
  {
    id: "corsia-and-jet-fuel-price-path",
    title: "CORSIA offset price and jet fuel price trajectory",
    category: "carbon-price",
    part: 2,
    keyNumbers: ["CORSIA offset price: EUR 30/tCO2 (2030) to EUR 83/tCO2 (2035)", "Jet fuel price: EUR 85/boe (2030) to EUR 97/boe (2040), +14%"],
    figureOrTable: "text (Annex 4, Section 1.2.3.1)",
    pdfPages: [71],
    whyImportant: "Only explicit international carbon-price figures given in this part; needed to compare EU ETS aviation pricing with the global CORSIA benchmark used in AERO-MS/PRIMES modelling.",
    quote: "The offset price of CORSIA... is projected to increase from 30 EUR/tCO2 in 2030 to 83 EUR/tCO2 in 2035... International jet fuel prices... projected to increase by 14% approximately from 85 EUR/boe in 2030 to 97 in 2040.",
    shots: [],
  },
  {
    id: "aviation-emissions-with-without-saf",
    title: "Baseline global aviation CO2 emissions with vs without SAF uptake",
    category: "technology-scaling",
    part: 2,
    keyNumbers: ["690 MtCO2 in 2024", "763 MtCO2 in 2040 without SAF", "590 MtCO2 in 2040 with SAF (ReFuelEU-mandated uptake)"],
    figureOrTable: "text (Annex 7, Section 1.3 Baseline; cross-ref Annex 10 Table 2)",
    pdfPages: [107],
    whyImportant: "Isolates the emissions-reduction contribution of SAF technology deployment alone within the baseline aviation projection.",
    quote: "In the baseline global aviation CO2 emissions should decrease to 590Mt CO2 in 2040. Without accounting for the use of SAF, these emissions would increase from 690 Mt CO2 in 2024 to 763Mt CO2 in 2040.",
    shots: [],
  },
  {
    id: "maritime-baseline-fuel-mix-and-costs",
    title: "Maritime baseline: low-carbon fuel uptake and total shipping cost growth",
    category: "technology-scaling",
    part: 2,
    keyNumbers: ["Renewable/low-carbon fuel share: 7% (2030), 63% (2040), 87% (2050)", "Total shipping costs: EUR 105bn (2030) to EUR 163bn (2050)"],
    figureOrTable: "text (Annex 7, Section 1.3 Baseline)",
    pdfPages: [109],
    whyImportant: "Concrete technology-scaling trajectory (alternative marine fuels) paired with the resulting sector-wide cost trajectory under the baseline, useful for benchmarking policy-option variants.",
    quote: "Total shipping costs are expected to grow over the period 2030-2050 from 105 billion EUR to 163 billion EUR... reaching 7% of the energy mix in 2030, 63% in 2040 and 87% in 2050.",
    shots: [],
  },
  {
    id: "20mw-threshold-quantification",
    title: "20 MW threshold lowering: emissions vs administrative burden trade-off",
    category: "other",
    part: 2,
    keyNumbers: ["227 MtCO2e (2021-2023 avg) currently outside EU ETS below relevant thresholds", "85% of this already covered by ETS2", "28 MtCO2e remaining process emissions", "Lowering to 10MW brings in ~10 MtCO2e but +11,000 installations"],
    figureOrTable: "text (Annex 7, Section 2.5.3)",
    pdfPages: [124, 125],
    whyImportant: "Rare explicit cost-effectiveness (emissions-per-installation) calculation used to justify rejecting a scope-expansion option in all three policy packages.",
    quote: "Lowering the threshold to 10 MW would bring approximately 10 MtCO2e of annual emissions into the ETS, but would expand the EU ETS by more than 11,000 installations.",
    shots: [],
  },
  {
    id: "mwi-inclusion-emission-reduction",
    title: "Municipal waste incineration (MWI) inclusion: emissions impact",
    category: "industry",
    part: 2,
    keyNumbers: ["-53 MtCO2 or -22% cumulative reduction over 2031-40 vs baseline", "Waste carbon cost EUR 39-66/tonne in 2031"],
    figureOrTable: "text (Annex 3 benefits table; Annex 3 costs table)",
    pdfPages: [36, 47],
    whyImportant: "Quantifies the emissions and cost impact of bringing a wholly new sector (municipal waste incineration) into the EU ETS scope for the first time.",
    quote: "Including emissions from municipal waste incineration in the ETS is expected to reduce cumulative emissions from municipal waste incineration by -53 MtCO2 or -22% over 2031-40 compared to the baseline.",
    shots: [],
  },
  {
    id: "cap-legal-default-trajectory",
    title: "Legal default cap trajectory (LRF 4.4%)",
    category: "scenarios",
    part: 3,
    keyNumbers: ["EEA cap 2030: 975 Mt", "2035: 485 Mt", "2040: 69 Mt", "LRF -4.4%", "Carbon budget 2031-2040: 4,436 Mt", "+148 Mt in 2027 from aviation scope"],
    figureOrTable: "Table 1 / Figure 1",
    pdfPages: [7, 8, 9],
    whyImportant: "Baseline against which all ETS1 cap policy options are benchmarked; shows the sharp emissions-space kink from aviation scope expansion.",
    quote: "Applying the Linear Reduction Factor (LRF) of 4.4% to the total cap in the relevant base years leads to the following estimates.",
    shots: ["p3-008-legal-cap-trajectory.png"],
  },
  {
    id: "cap-trajectories-cap1-2-3",
    title: "CAP1/CAP2/CAP3 cap trajectories (PRIMES & POTEnCIA, 85% scenario)",
    category: "scenarios",
    part: 3,
    keyNumbers: ["2030: 911 Mt (all)", "PRIMES 2035: 620/580/560 Mt", "POTEnCIA 2035: 645/670/605 Mt", "2040: 330 Mt (PRIMES) / 375 Mt (POTEnCIA)", "Carbon budget range 2031-2040: 5,605-6,295 Mt"],
    figureOrTable: "Table 2, Table 3, Table 4",
    pdfPages: [11, 12],
    whyImportant: "Core cap-trajectory design choice (linear vs 85-pathway vs 90-85 pathway) with model uncertainty range - directly determines LRF and carbon budget options for the ETS1 reform.",
    quote: "For the further modelling-based analysis we have used the PRIMES 85 trajectory as PRIMES was used to assess the policy options.",
    shots: ["p3-011-cap123-primes.png", "p3-012-cap123-potencia.png"],
  },
  {
    id: "cap-po1-po2-po3",
    title: "Cap setting for Policy Options 1-3",
    category: "scenarios",
    part: 3,
    keyNumbers: ["PO1 carbon budget 2031-2040: 5,120-5,775 Mt", "PO2: 5,890-6,330 Mt", "PO3: 6,715-7,335 Mt", "PO2 2040 cap incl. MWI: 310-340 Mt", "PO3 2040 cap incl. waste/landfill: 420-465 Mt"],
    figureOrTable: "Table 12, Table 13, Table 14",
    pdfPages: [19, 20, 21],
    whyImportant: "Direct cap/LRF quantification for the three headline policy options compared in the impact assessment, including scope-expansion effects (MWI, hazardous waste, landfill).",
    quote: "Table 14: Table showing the cap for PO3 ... Carbon Budget 2031-2040 6715-7335",
    shots: [],
  },
  {
    id: "investment-needs-system-costs",
    title: "Investment needs and energy system costs by cap scenario",
    category: "mitigation-cost",
    part: 3,
    keyNumbers: ["Industry annual investment 2031-2040: EUR 30-40bn", "Supply-side: EUR 140-175bn", "Energy system cost industry 2030: 2.0-2.3% of GDP", "CAP4 accelerated scenario: industry costs +3.4% vs CAP3 over 2031-2040", "CAP5 90% scenario: +13% industry system costs in 2031-2035"],
    figureOrTable: "Table 7, Table 8, Table 9, Table 10",
    pdfPages: [13, 14, 15, 16],
    whyImportant: "The main total-system-cost and %GDP estimates for ETS1 sectors under different cap-trajectory ambition levels, showing front-loading vs back-loading cost trade-offs.",
    quote: "The overall energy-related costs in the first half of the decade in the CAP4 accelerated 9085 scenario are around 5.7% higher than under the CAP 3 9085 scenario for energy intensive industries.",
    shots: ["p3-013-investment-needs-cap.png", "p3-016-system-costs-removals.png"],
  },
  {
    id: "removals-eligible-volumes",
    title: "Total eligible removals in the EU (BioCCS+DACCS), 85% scenario",
    category: "removals",
    part: 3,
    keyNumbers: ["2030: 5-10 Mt", "2035: 5-25 Mt", "2040: 45-60 Mt", "2031-2040 cumulative: 170-330 Mt", "Removals = 2.5-5% of cap 2031-2040, 10-13% by 2040"],
    figureOrTable: "Table 11 (Annex 8-I); Table 3 (Annex 8-II)",
    pdfPages: [16, 17, 35, 36],
    whyImportant: "Core PRIMES/POTEnCIA modelled removals-supply figures used to size the removals-linked allowance space and cap decomposition (net vs gross emissions).",
    quote: "The total eligible removals in the EU are estimated to be ... Removals stored underground 5-10 / 5-25 / 45-60 / 170-330",
    shots: ["p3-016-system-costs-removals.png", "p3-036-removals-volumes-prices.png"],
  },
  {
    id: "cdr-technology-unit-prices",
    title: "BioCCS and DACCS removal unit price trajectory 2030-2040",
    category: "removals",
    part: 3,
    keyNumbers: ["Average BioCCS price: EUR 214 (2030) -> EUR 176 (2040)", "Average DACCS price: EUR 428 (2030) -> EUR 278 (2040)", "PRIMES DACCS capture+transport+storage: EUR 518 (2030) -> EUR 251 (2040)", "PRIMES BECCS: EUR 171 (2030) -> EUR 148 (2040)", "BECCS cost-competitive with EUA price by 2036-2038; DACCS not within period"],
    figureOrTable: "Table 4, Table 5, Table 6",
    pdfPages: [36, 47, 48],
    whyImportant: "Key cost-competitiveness benchmark comparing removal technology costs against expected EUA prices, central to the removals-integration policy design (CR1-CR5).",
    quote: "Based on these technology costs, removal units from BECCS are expected to become cost competitive vis-a-vis the allowance price in 2036-38, whereas DACCS removal units would not reach cost competitiveness within the period.",
    shots: ["p3-036-removals-volumes-prices.png", "p3-047-cdr-costs-fiscal.png", "p3-048-cdr-unit-prices.png"],
  },
  {
    id: "cdr-investment-fiscal-cost",
    title: "Public purchasing programme investment and fiscal cost for CDR (CR4)",
    category: "removals",
    part: 3,
    keyNumbers: ["Upfront investment PRIMES: EUR 29-43bn (avg EUR 35.7bn)", "Upfront investment POTEnCIA: EUR 46-65bn (avg EUR 55.5bn)", "Final fiscal cost 2031: EUR 0.41-1.04bn", "Final fiscal cost 2040: negative (EUR -0.92bn / -2.92bn)", "Illustrative net fiscal cost: PRIMES EUR +3bn, POTEnCIA EUR -1.7bn"],
    figureOrTable: "Figure 3, Figure 5",
    pdfPages: [47, 49],
    whyImportant: "Quantifies the net budgetary cost/benefit of a public removals-purchasing programme, showing it could become self-financing (or revenue-positive) by 2040 as removal costs fall below the carbon price.",
    quote: "the purchasing programme under PRIMES would have an illustrative final fiscal cost of Euro EUR 3 bn and of EUR -1.7bn under POTEnCIA.",
    shots: ["p3-047-cdr-costs-fiscal.png"],
  },
  {
    id: "msr-measures-dashboard",
    title: "MSR measures summary dashboard (MSR0 to MSR3)",
    category: "scenarios",
    part: 3,
    keyNumbers: ["Cumulative emissions 2026-2040: MSR0 11,016 Mt; MSR0+ 11,282 Mt; MSR1 11,214 Mt; MSR2 10,845 Mt; MSR3 11,117 Mt", "First MSR release year: MSR0 2037; MSR0+ 2031; MSR1 2034; MSR2 2040; MSR3 2035", "TNAC-to-emissions ratio spread: MSR3 0.34-0.55 (narrowest)"],
    figureOrTable: "Table 5",
    pdfPages: [126, 127],
    whyImportant: "The single comparative quantitative summary of how five alternative Market Stability Reserve designs affect cumulative ETS1 emissions and reserve/liquidity dynamics through 2040.",
    quote: "Cumulative emissions over 2026-2040 (MtCO2): MSR0 11,016; MSR0+ 11,282; MSR1 11,214; MSR2 10,845; MSR3 11,117",
    shots: ["p3-126-msr-dashboard-1.png", "p3-127-msr-dashboard-2.png"],
  },
  {
    id: "po-summary-dashboard",
    title: "Policy Option summary dashboard (PO1-PO3 with MSR3)",
    category: "scenarios",
    part: 3,
    keyNumbers: ["Cumulative emissions 2026-2040: Baseline 10,350 Mt; PO1 10,690 Mt; PO2 11,817 Mt; PO3 12,379 Mt", "First MSR release: PO1 2035, PO2/PO3 2036", "TNAC-to-emissions ratio spread: PO2/PO3 0.25-0.59 vs PO1 0.29-0.68"],
    figureOrTable: "Table 12",
    pdfPages: [138, 139],
    whyImportant: "Consolidated headline liquidity/emissions comparison across the three final ETS1 policy options combined with the recommended MSR3 design.",
    quote: "PO2 and PO3 under MSR3 are considered the preferred options, as they achieve emissions reductions comparable to PO1 while providing stronger economic performance.",
    shots: ["p3-138-po-dashboard.png"],
  },
  {
    id: "idb-abatement-model",
    title: "Industrial Decarbonisation Bank (IDB) modelled GHG abatement",
    category: "industry",
    part: 3,
    keyNumbers: ["Cumulative abatement: 1,630 Mt CO2 over 10 years", "Budget: EUR 100bn (EUR 10bn/year x 10 rounds)", "Weighted average awarded support: EUR 60/tCO2 abated"],
    figureOrTable: "Figure 9 / text (Section 3.4.1.2)",
    pdfPages: [184, 185],
    whyImportant: "The headline quantitative output of the IDB auction-simulation model, translating the EUR 100bn endowment into an explicit cost-per-tonne and total abatement figure for industry.",
    quote: "The model results indicate cumulative GHG emission abatement of 1,630 Mt CO2 over a ten-year period ... the resulting weighted average awarded support amounts to EUR 60/t CO2 abated.",
    shots: ["p3-184-idb-abatement-model.png", "p3-185-idb-abatement-model-2.png"],
  },
  {
    id: "idb-leverage-effect",
    title: "IDB direct private investment leverage effect",
    category: "industry",
    part: 3,
    keyNumbers: ["Direct investment leverage: 5%-75% by sector/technology", "Weighted average leverage: 45%"],
    figureOrTable: "text (Section 3.4.1.3)",
    pdfPages: [186],
    whyImportant: "Key multiplier showing how much private capital each euro of IDB public support is expected to mobilise for industrial decarbonisation.",
    quote: "the direct investment leverage effect varies between 5% and 75%, depending on the sector and technology considered ... the weighted average direct investment leverage amounts to 45%.",
    shots: [],
  },
  {
    id: "idb-ccfd-intensity",
    title: "IDB support intensity and emissions coverage (illustrative CCfD)",
    category: "mitigation-cost",
    part: 3,
    keyNumbers: ["Support intensity: EUR 50-100/tCO2 (on top of EU ETS price)", "Over 10 years could address 20%-40% of industrial emissions (100-200 Mt CO2)", "Industry investment needs: EUR 30-50bn/year", "Industry OPEX: ~EUR 300bn/year"],
    figureOrTable: "text",
    pdfPages: [157],
    whyImportant: "Illustrative back-of-envelope linking the EUR 100bn IDB endowment to a plausible EUR/tCO2 support intensity and share of industrial emissions addressed, contextualised against total industry investment/OPEX.",
    quote: "If IDB supported the industrial decarbonisation projects at the intensity of between 50 to 100 EUR/tCO2 (on top of the EU ETS price), over 10 years, it could address between 40% and 20% of the industrial emissions in the EU.",
    shots: [],
  },
  {
    id: "aviation-maritime-abatement-costs",
    title: "Marginal abatement costs for maritime hydrogen, biofuels, methanol",
    category: "mitigation-cost",
    part: 3,
    keyNumbers: ["Hydrogen MAC: EUR 763/tCO2 (2025) -> EUR 247/tCO2 (2040)", "Biofuels MAC: EUR 190/tCO2 (2025) -> EUR -93/tCO2 (2040)", "Methanol MAC: EUR 924/tCO2 (2025) -> EUR 329/tCO2 (2040)"],
    figureOrTable: "text (near Table 17)",
    pdfPages: [219],
    whyImportant: "Concrete EUR/tCO2 marginal abatement cost curve for maritime alternative fuels, showing biofuels reaching negative abatement cost (cheaper than fossil) by 2040 once carbon price is factored in.",
    quote: "the marginal abatement cost for using hydrogen is EUR 763 in 2025 and modelled to decrease to EUR 247 by 2040 ... For maritime biofuels, the marginal abatement cost is EUR 190 in 2025, modelled to decrease to negative EUR 93 by 2040.",
    shots: ["p3-219-maritime-fuel-macs.png"],
  },
  {
    id: "saf-price-projections",
    title: "SAF price projections by fuel type 2028-2035",
    category: "technology-scaling",
    part: 3,
    keyNumbers: ["Fossil kerosene: EUR 799/t (2028) -> EUR 882/t (2035)", "Biofuels: EUR 2,291/t (2028) -> EUR 2,217/t (2035)", "Advanced biofuels: EUR 2,705/t (2028) -> EUR 2,310/t (2035)", "RFNBOs: constant EUR 8,465/t (2028-2035)"],
    figureOrTable: "Table 28",
    pdfPages: [254],
    whyImportant: "Underpins the sizing of ETS-financed SAF support mechanisms and shows the persistent large cost gap for e-fuels (RFNBOs) vs fossil kerosene through 2035.",
    quote: "Table 28: SAF price projections, by SAF type, 2028 to 2035 (EUR per tonne) ... RFNBOs 8,465 8,465 8,465 8,465",
    shots: ["p3-254-saf-price-projections.png"],
  },
  {
    id: "maritime-mss2-extension",
    title: "Impact of extending ETS to smaller vessels (MSS2)",
    category: "technology-scaling",
    part: 3,
    keyNumbers: ["GHG reduction vs PO1: -1.5% (2030), -24.5% (2040), -70.4% (2050)", "Cumulative 2030-2050 emissions reduction: -124.3 MtCO2 (-28.3%)", "Shipping cost increase: +5.1% average 2030-2050 (+EUR 36.1bn cumulative)", "Renewable fuel share of smaller-vessel energy demand by 2050: 77% (MSS2) vs 26% (baseline)"],
    figureOrTable: "Table 15, Table 16",
    pdfPages: [311, 312, 313],
    whyImportant: "PRIMES-Maritime modelled quantification of extending the ETS to 400-5,000 GT vessels, showing both emissions and cost impacts and the resulting fuel-switching effect.",
    quote: "Total shipping cost increases from policy measure MSS2 were estimated at 5.1% on average during the period 2030-2050, compared to the default policy scenario.",
    shots: ["p3-312-mss2-smaller-vessels.png"],
  },
  {
    id: "maritime-eua-price-reference",
    title: "Current EUA price and maritime derogation cost exemptions",
    category: "carbon-price",
    part: 3,
    keyNumbers: ["Average EUA price 2024: EUR 65/allowance (EUR 2025)", "Current EUA price reference: approx. EUR 70-80/EUA", "2024 cost exemption from derogations: ~EUR 126 million", "Full-scope revenue forgone at 100% surrender: ~EUR 320 million"],
    figureOrTable: "Table 6 / text",
    pdfPages: [291, 293, 294],
    whyImportant: "One of the few absolute (non-indexed) EUA price data points in Part 3, used to monetise the value of maritime scope derogations (OMR/SIP).",
    quote: "Considering the average price of EU allowances in 2024 (EUR 65 per allowance in 2025) ... current EUA price of approximately EUR 70-80 per EUA.",
    shots: [],
  },
  {
    id: "smap-mechanism-support-volumes",
    title: "Sustainable Maritime Alternative Propulsion (SMAP) mechanism sizing",
    category: "technology-scaling",
    part: 3,
    keyNumbers: ["RFNBO-focused support: 26 million EUAs (2031-2040)", "SAF-like share support: 46 million EUAs (2031-2040)", "Annual GHG reduction by 2035: 1.7-9 MtCO2 depending on funding", "Full GHG Fuel Intensity trajectory funding: up to 200 million allowances"],
    figureOrTable: "Table 3",
    pdfPages: [270, 271],
    whyImportant: "Quantified sizing options for a proposed ETS-financed maritime fuel-switching support mechanism, paralleling the aviation SAF support model.",
    quote: "By 2035, it could help deliver an annual GHG emissions reduction in the range of 1,7 to 9 MtCO2, depending on the funding volume made available.",
    shots: [],
  },
  {
    id: "gem-e3-scenarios",
    title: "GEM-E3 carbon-leakage policy scenarios (PO1/PO2/PO3)",
    category: "scenarios",
    part: 4,
    keyNumbers: ["PO1 (CL1): 85% GHG reduction by 2040, improved current free allocation approach", "PO2 (CL2_50/CL2_90): 85% reduction, conditional free allocation with 50% or 90% compliance", "PO3 (CL3): 85% reduction, free allocation phased out fully by 2034", "Revenue recycling variants (R): 50% of ETS revenue as lump-sum to households instead of power-sector investment"],
    figureOrTable: "Table 3",
    pdfPages: [16, 17],
    whyImportant: "Defines the core GEM-E3 policy scenario matrix (PO1/PO2/PO3 and revenue-recycling variants) that underlies nearly all quantitative industry/macro results in Annex 12.",
    quote: "CL1: EU targets 85% reduction in GHG emissions by 2040... CL3: EU targets 85% reduction... as it phases out the free allowance for non-CBAM sectors.",
    shots: ["p4-016-gem-e3-scenarios.png"],
  },
  {
    id: "free-allocation-budget-2031-40",
    title: "2031-40 free allocation budget by scenario",
    category: "industry",
    part: 4,
    keyNumbers: ["Baseline: 1,453 M EUAs (2031-40)", "CL1/PO1: 1,934 M EUAs", "CL2/PO2: 2,026-2,206 M EUAs", "CL3/PO3: 2,367 M EUAs", "Financial value at assumed EUR150/tCO2: baseline EUR116.9bn; PO1 EUR146.6bn; PO2_90(CBAM) EUR171.8bn; PO3 EUR73.1bn"],
    figureOrTable: "Table 4 / Table 12",
    pdfPages: [19, 30, 31],
    whyImportant: "Central quantification of how much free allocation (and its EUR value) industry receives under each policy option for Phase V (2031-2040).",
    quote: "In the baseline, the total free allocation budget is assumed to be 1,453 M EUAs over 2031-40... CL3, which is assumed to be 2,367 M EUAs over 2031-40.",
    shots: ["p4-019-free-allocation-budgets.png", "p4-030-free-allocation-value.png", "p4-031-icc-decomposition.png"],
  },
  {
    id: "auction-revenue-2031-40",
    title: "Cumulative EU ETS auction revenue 2031-40 by policy option",
    category: "macro",
    part: 4,
    keyNumbers: ["Baseline: 1,926 M EUAs auctioned, EUR288.9bn revenue", "PO1: 4,043.7 M EUAs, EUR606.6bn", "PO2: 4,153.5 M EUAs, EUR623.0bn", "PO3: 5,546 M EUAs, EUR831.9bn", "Assumed carbon price EUR150/tCO2 (2031-40 average)"],
    figureOrTable: "Table 22",
    pdfPages: [55],
    whyImportant: "Gives the public-revenue implications (for climate action/decarbonisation financing) of each free-allocation policy option at an assumed EUR150 carbon price.",
    quote: "PO3_Auctioned allowances (mil EUAs) 5546; PO3_Cumulative auction revenue (bn EUR) EUR 831.9.",
    shots: ["p4-055-auction-revenue-2031-40.png"],
  },
  {
    id: "unit-cost-production-2040",
    title: "Sectoral unit production cost changes in 2040 (GEM-E3)",
    category: "industry",
    part: 4,
    keyNumbers: ["Range across sectors/policy options: -0.18% to +0.19% relative to baseline", "Chemical products: largest decrease (-0.17% PO1 to -0.18% PO3)", "PO1R/PO3R (household recycling variants) show higher unit costs (e.g. +0.19% paper products PO1R)"],
    figureOrTable: "Table 14",
    pdfPages: [46],
    whyImportant: "Shows GEM-E3-modelled competitiveness impact (unit cost of production) by sector under each free-allocation design - a key metric for carbon-leakage assessment.",
    quote: "Overall, the impact on unit production costs across policy measures and sectors relative to the Reference ranges from -0.18% to 0.19%.",
    shots: ["p4-046-unit-production-costs.png"],
  },
  {
    id: "gdp-impact-2040",
    title: "GDP and component impacts in 2040 (GEM-E3)",
    category: "macro",
    part: 4,
    keyNumbers: ["GDP change ranges from 0.00% (PO2_50) to +0.08% (PO3R) vs baseline", "PO1: +0.03% GDP; PO3: +0.05%; PO3R: +0.08% (highest, driven by lump-sum recycling)", "Exports +0.03% to +0.08% in standard recycling scenarios; decline under lump-sum variants (PO1R -0.06%, PO3R -0.03%)"],
    figureOrTable: "Table 20",
    pdfPages: [49],
    whyImportant: "The headline macroeconomic (GDP) result of the GEM-E3 modelling for the carbon-leakage/free-allocation policy options - small positive effects in all scenarios.",
    quote: "In all policy options, GDP in 2040 increases relative to the baseline scenario... The GDP increase ranges from 0.00% under PO2_50 to 0.08% under PO3R.",
    shots: ["p4-049-gdp-impacts-2040.png"],
  },
  {
    id: "employment-impact-2040",
    title: "Sectoral employment change in 2040 (GEM-E3)",
    category: "macro",
    part: 4,
    keyNumbers: ["Overall range across sectors/policy measures: -0.56% to +1.76%", "Non-metallic minerals: +1.76% under PO2_90C (largest gain)", "PO1R: highest total-economy employment increase; PO3: lowest (full free-allocation phase-out after 2034)"],
    figureOrTable: "Table 23",
    pdfPages: [56],
    whyImportant: "Quantifies employment effects by ETS-covered sector under each carbon-leakage policy option - key social-impact reference.",
    quote: "Across sectors and policy measures, the overall employment impact ranges from -0.56% to 1.76%.",
    shots: ["p4-056-employment-impacts-2040.png"],
  },
  {
    id: "eu27-emissions-change-2040",
    title: "EU27 and non-EU27 emissions change in 2040 vs baseline (carbon leakage)",
    category: "scenarios",
    part: 4,
    keyNumbers: ["Total economy EU27 emissions increase: +7.72 Mt (PO1) to +46.13 Mt (PO3R)", "Non-EU27 emissions decrease: -3.97 Mt (PO3R) to -8.93 Mt (PO2_90C)", "Chemicals and non-metallic minerals show largest absolute EU27 increases (e.g. +9.99 Mt non-metallic minerals under PO3)"],
    figureOrTable: "Table 25 / Table 26",
    pdfPages: [58, 59],
    whyImportant: "Directly measures the carbon-leakage outcome (domestic vs foreign emissions) of each free-allocation design - the central environmental metric of Annex 12.",
    quote: "EU27 EU ETS GHG emissions increase from baseline levels in all scenarios. Therefore, the conventional formula for carbon leakage estimation is not relevant to this analysis.",
    shots: ["p4-058-emissions-change-leakage.png"],
  },
  {
    id: "icc-cost-decomposition",
    title: "Indirect cost compensation (ICC) cost decomposition to 2040",
    category: "carbon-price",
    part: 4,
    keyNumbers: ["Observed ICC payments avg. 2021-23: EUR4.1bn/year (range EUR2.2-5.5bn)", "Carbon price assumption: EUR53/tCO2 (2021-23 avg) rising to EUR150/tCO2 (2031-40 avg), +174% impact on ICC cost", "Combined participation+intensity effect: +76% (to EUR7.2bn)", "All impacts combined: +310% (default factor, EUR16.8bn) or +102% (market-based factor, EUR8.3bn)", "Estimated at 11%-22% of total ETS revenues 2031-2040"],
    figureOrTable: "Table 13",
    pdfPages: [31, 33],
    whyImportant: "Quantifies how indirect carbon cost compensation is projected to evolve to 2040 as carbon prices rise and the power sector decarbonises - a key industrial cost-support metric.",
    quote: "carbon price 2031-40 avg. +174% ... all impacts combined +310% EUR 16.8 [bn] ... +102% EUR 8.3 [bn].",
    shots: ["p4-031-icc-decomposition.png"],
  },
  {
    id: "cl2-conditional-investment",
    title: "Estimated investment triggered by CL2 conditional free allocation",
    category: "mitigation-cost",
    part: 4,
    keyNumbers: ["CL2_90 (90% compliance): ~EUR90 billion investment over 2031-40", "CL2_50 (50% compliance): ~EUR50 billion investment over 2031-40", "Based on average EUA price of EUR150/tCO2"],
    figureOrTable: "text",
    pdfPages: [25, 28],
    whyImportant: "Provides a direct estimate of the decarbonisation investment mobilised by making free allocation conditional on climate-neutrality plans - a rare investment-cost figure in this annex.",
    quote: "The expected level of investment because of the introduction of further conditionalities under CL2_90 for non-CBAM sectors only is estimated to be around EUR 90 billion over the 2031-40 period.",
    shots: [],
  },
  {
    id: "20mw-threshold-coverage",
    title: "Emissions/installation coverage from lowering the 20MW ETS threshold",
    category: "other",
    part: 4,
    keyNumbers: ["Total addressable emissions <20MW: 28 MtCO2e (mostly process emissions)", "Lower to 15MW: +5 MtCO2e, +5,005 installations (5%)", "Lower to 10MW: +10 MtCO2e, +11,615 installations (12%)", "Lower to 5MW: +18 MtCO2e, +26,345 installations (28%)", "No threshold: +28 MtCO2e, +94,428 installations (100%), vs 8,640 existing ETS installations (2022)"],
    figureOrTable: "Table 31",
    pdfPages: [70],
    whyImportant: "Quantifies the (rejected) option of lowering the 20MW capacity threshold, showing a large increase in installation count for a small emissions gain - basis for the option being discarded.",
    quote: "up to 28 MtCO2e of emissions could be brought into the scope of EU ETS by lowering the 20 MW threshold... lowering the threshold to 15 MW would imply increasing the number of EU ETS stationary installations by over 50%.",
    shots: ["p4-070-threshold-20mw.png"],
  },
  {
    id: "mwi-cap-extension",
    title: "Cap extension estimate for including municipal waste incineration (MWI)",
    category: "scenarios",
    part: 4,
    keyNumbers: ["2024 MWI fossil emissions: 39.4 MtCO2e (EU27: 38.6 Mt)", "Modelled 2030 cap extension: 41.5 MtCO2eq (EU27) to 42.2 MtCO2e (EEA)", "Total MWI emissions (fossil+biogenic) 2024: 85.0 MtCO2eq (47% fossil / 53% biogenic)", "Expected annual EU ETS revenue from MWI inclusion: ~EUR4.75bn/year (2031-2040, at EUR150/tCO2)"],
    figureOrTable: "Table 2",
    pdfPages: [77],
    whyImportant: "Key quantitative input for extending the EU ETS cap to cover municipal waste incineration, one of the main new-sector proposals in this annex.",
    quote: "the cap extension for MWI (measure W1) has been modelled to be in the range of 41.5 MtCO2eq (EU-27) and 42.2 MtCO2e (EEA).",
    shots: ["p4-077-mwi-cap-extension.png"],
  },
  {
    id: "landfill-emissions-estimates",
    title: "Landfill (non-hazardous waste) emissions estimates",
    category: "scenarios",
    part: 4,
    keyNumbers: ["UNFCCC inventory 2023: 65.3 Mt CO2e (managed) + 8.6 Mt CO2e (unmanaged)", "Default emission factor (future emissions, all solid waste) 2022: 82.2 MtCO2e", "Municipal-waste-only future emissions 2022: 31.2 MtCO2e", "Cap coverage range if included: 73.9 Mt (historical) to 82.2 Mt (future) CO2eq"],
    figureOrTable: "Table 3 (waste annex)",
    pdfPages: [80],
    whyImportant: "Landfill methane is the largest single source of EU waste-sector GHG emissions and a candidate new ETS scope (measure W3); this is the core sizing data for that option.",
    quote: "the emissions covered would vary from 73.9 MtCO2eq in 2022 in the latter case to 82.2 MtCO2eq in the former case.",
    shots: [],
  },
  {
    id: "waste-carbon-cost-passthrough",
    title: "Effective carbon cost per tonne of waste at EUR110/tCO2 (2030)",
    category: "mitigation-cost",
    part: 4,
    keyNumbers: ["Municipal waste incineration: EUR38.5-66/tonne of waste (38.5%-66% increase on EUR100 gate fee)", "Landfilling: ~EUR66/tonne of waste on average (more than doubling EUR50 gate fee)", "Price elasticities: -0.2 to -0.4 for residual waste demand; +0.32 to +0.45 diversion to recycling"],
    figureOrTable: "text",
    pdfPages: [82, 83],
    whyImportant: "Translates a EUR110/tCO2 carbon price into concrete per-tonne cost impacts on waste gate fees, underpinning the abatement/behavioural response modelling for the waste sector.",
    quote: "the average effective carbon cost per tonne of municipal waste incinerated is estimated to range between EUR 38.5 and 66 (2030)... the average carbon cost per tonne of landfilled waste is estimated to amount to EUR 66 on average.",
    shots: [],
  },
  {
    id: "wte-carbon-capture-cost",
    title: "Carbon capture cost for waste-to-energy plants",
    category: "mitigation-cost",
    part: 4,
    keyNumbers: ["CAPEX only: EUR40-75/tCO2", "Total CAPEX+OPEX: EUR76-127/tCO2 (lower end) up to EUR172/tCO2 (higher estimate)", "Positive business case (incl. biogenic removals revenue) expected by mid-2030s"],
    figureOrTable: "text",
    pdfPages: [87, 88],
    whyImportant: "Provides a concrete abatement-cost benchmark (EUR/tCO2) for CCUS in the waste sector, comparable to costs in other hard-to-abate industries, plus the removals angle relevant to negative emissions.",
    quote: "the cost of carbon capture in waste-to-energy installations has variously been estimated to range from EUR 40-75/tonne of CO2 (CAPEX) to EUR 76-127/tonne of CO2 (total CAPEX and OPEX)... to EUR172/tonne of CO2.",
    shots: [],
  },
  {
    id: "ccu-co2-capture-potential",
    title: "JRC estimate of technically capturable CO2 for CCU/CCS (EU industry)",
    category: "technology-scaling",
    part: 4,
    keyNumbers: ["Iron & steel, cement, petrochemicals combined: 210-290 Mtpa capturable", "Waste-to-energy plants: 60-120 Mtpa capturable", "Industrial capture cost (hard-to-abate): EUR40-90/tCO2; ~200 Mtpa capturable below EUR100/tCO2", "CO2 pipeline network needed by 2050: up to 9,000 km, EUR9.3-23.1bn investment"],
    figureOrTable: "Figure 12 / text",
    pdfPages: [141, 145],
    whyImportant: "Key technology-scaling benchmark for how much CO2 could realistically be captured across EU industry and waste sectors to feed CCU/CCS and e-fuel production.",
    quote: "a total of 210-290 Mtpa are available for capture in the iron and steel, cement and petrochemicals sectors together... while in waste-to-energy plants the capturable amount would lie between 60 and 120 Mtpa.",
    shots: ["p4-141-ccu-capture-potential.png"],
  },
  {
    id: "ets-emissions-reduction-50pct",
    title: "EU ETS stationary-installation emissions reduction since 2005",
    category: "scenarios",
    part: 5,
    keyNumbers: ["~50% emissions reduction 2005-2024 (stationary installations)", "-16.7% in 2023 vs 2022 (largest annual drop in scheme's history)", "-17.1% 2005-2024 for energy-intensive industry excl. combustion"],
    figureOrTable: "Figure 3",
    pdfPages: [26],
    whyImportant: "Headline ex-post delivery number for the ETS - the actual realized emissions trajectory that any forward-looking model should be benchmarked against.",
    quote: "emissions from stationary installations, including both power and industrial facilities, have decreased by around 50% in 2024",
    shots: ["p5-026-ets-emissions-since-2005.png"],
  },
  {
    id: "eua-price-history",
    title: "Annual average EUA price evolution 2013-2024",
    category: "carbon-price",
    part: 5,
    keyNumbers: ["<EUR 10 2013-2017", "EUR 5.8/tCO2 2017", "EUR 15.8/tCO2 2018", "EUR 24.9/tCO2 2019", "EUR 24.8/tCO2 2020", "EUR 53.7/tCO2 2021", "EUR 80.8/tCO2 2022", "EUR 83.5/tCO2 2023", "EUR 65.9/tCO2 2024"],
    figureOrTable: "Figure 17",
    pdfPages: [65],
    whyImportant: "The single most-referenced historical carbon price series for the EU ETS, showing the price effect of the 2018 reform/MSR and Fit-for-55.",
    quote: "Prices further increased to EUR 24.9 per tCO2e in 2019...Prices increased substantially in both 2021 and 2022 to 53.7 and EUR 80.8 per tCO2e",
    shots: ["p5-065-eua-price-history.png"],
  },
  {
    id: "cap-vs-verified-emissions",
    title: "EU ETS cap trajectory 2005-2030 vs verified emissions",
    category: "scenarios",
    part: 5,
    keyNumbers: ["LRF raised 1.74% -> 2.2% (2021)", "LRF 4.3% (2024-27) -> 4.4% (2028+)", "43% reduction target by 2030 vs 2005 (2018 revision)", "62% reduction target by 2030 vs 2005 (2023 Fit-for-55 revision)"],
    figureOrTable: "Figure 7",
    pdfPages: [37],
    whyImportant: "Shows the official EU ETS cap pathway to 2030 (with 2024/2026 rebasing and maritime inclusion) against actual verified emissions - core reference for any 2030/2040 pathway modelling.",
    quote: "Evolution of the EU ETS cap from 2005 up until 2030 compared with verified emissions...linear reduction factor of 4.3% in 2024-2027 and 4.4% from 2028",
    shots: ["p5-037-cap-vs-verified.png"],
  },
  {
    id: "marginal-abatement-cost-curve",
    title: "Stylised Marginal Abatement Cost Curve for EU ETS instruments",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["Three MAC curve segments: locked-in low-cost/non-price-barrier zone, market-based mid zone, innovation-intensive high-cost zone"],
    figureOrTable: "Figure 8",
    pdfPages: [42],
    whyImportant: "Canonical MAC-curve framework used by the Commission to justify cap-and-trade vs carbon tax vs command-and-control across the cost distribution.",
    quote: "Figure 8 illustrates this relationship using a stylised marginal abatement cost curve",
    shots: ["p5-042-mac-curve-stylised.png"],
  },
  {
    id: "required-carbon-price-industry",
    title: "Required carbon price to make abatement viable (aluminium/chemicals/steel) vs 2021 EU carbon price",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["Chemical industry abatement options up to EUR 500/tCO2 (Rekker et al. 2023)", "Eurofer: hydrogen steel/DRI/CCUS abatement EUR 100-200/t", "Cement Europe: EUA needs to reach >=EUR 200/t for deep decarbonisation business case"],
    figureOrTable: "Figure 6",
    pdfPages: [30, 31],
    whyImportant: "Direct empirical read on the carbon price threshold needed to trigger transformative industrial decarbonisation technologies - key MAC benchmark for hard-to-abate sectors.",
    quote: "the upper estimates of the required carbon price necessary to make a new-build net-zero technology financially viable exceeded the average EU carbon price in 2021",
    shots: ["p5-030-required-carbon-price-tech.png"],
  },
  {
    id: "free-allocation-value-vs-auctioned-value",
    title: "Value of free allocation vs auctioned allowances 2018-2024",
    category: "industry",
    part: 5,
    keyNumbers: ["Free allocation value ~EUR 195 billion (2018-2024)", "Value of allowances used for compliance not free ~EUR 238 billion (2018-2024)", "Counterfactual all-auctioned value ~EUR 433 billion (2018-2024)"],
    figureOrTable: "Figure 9",
    pdfPages: [43, 44],
    whyImportant: "Quantifies the fiscal/economic scale of free allocation as an implicit subsidy versus the counterfactual full-auctioning scenario - central number for industry cost/competitiveness modelling.",
    quote: "The overall value of the free allocation provided is estimated to be around EUR 195 billion over the 2018-24 period",
    shots: ["p5-043-free-allocation-vs-auctioned.png"],
  },
  {
    id: "windfall-profits-cost-passthrough",
    title: "Windfall profits from carbon cost pass-through (CE Delft 2008-2019)",
    category: "industry",
    part: 5,
    keyNumbers: ["EUR 26-46 billion total windfall profits 2008-2019", "Iron & steel: up to EUR 16bn", "Refineries: EUR 12bn", "Cement: EUR 7bn"],
    figureOrTable: "text (CE Delft 2021 study cited)",
    pdfPages: [43, 44, 128, 129],
    whyImportant: "Key ex-post estimate of distributional inefficiency/windfall profit from free allocation - often cited reference number for carbon leakage/CBAM policy debates.",
    quote: "Cost pass through was identified to be the largest driver of windfall profits, with an estimated EUR 26-46 billion... The iron and steel, refineries and cement sectors accrued respectively up to 16 billion EUR, 12 billion EUR, and 7 billion EUR",
    shots: ["p5-043-free-allocation-vs-auctioned.png"],
  },
  {
    id: "mrva-admin-cost-per-tonne",
    title: "MRVA administrative cost per tonne CO2",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["Stationary installations: EUR 0.2-0.9bn/year total, EUR 0.2-0.8/tCO2", "2016 study baseline: EUR 0.16/tCO2", "Aviation: EUR 12-20m total, EUR 0.2-0.4/tCO2 (54 MtCO2 in 2023)", "Free allocation survey: avg EUR 0.98/tCO2 (~1.43% of 2025 carbon price of EUR 68.77)"],
    figureOrTable: "Table 12",
    pdfPages: [132, 133, 170, 171],
    whyImportant: "Quantifies the administrative overhead of the ETS compliance system as a share of the carbon price - useful for total system cost estimates.",
    quote: "total costs for all operators of stationary installations range from EUR 0.2 - 0.9 billion per year... a range of 0.2 to 0.8 euro/tonne CO2",
    shots: [],
  },
  {
    id: "carbon-leakage-benchmark-cost",
    title: "Carbon cost per tonne of output for selected benchmarked products (EUA=EUR80)",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["Ammonia: EUR 32/t", "Dolime: EUR 29/t", "Lime: EUR 25/t", "Hot metal: EUR 19/t", "Primary aluminium: EUR 17/t", "Steam cracking: EUR 17/t", "White cement clinker: EUR 11/t", "Grey cement clinker: EUR 10/t"],
    figureOrTable: "Table 9",
    pdfPages: [112, 113],
    whyImportant: "Concrete, product-level carbon cost exposure figures derived from actual 2021-25 benchmarks vs 2016/17 average emissions - directly usable for industry cost-pass-through modelling.",
    quote: "Table 9 provides an overview of the estimated carbon cost per unit of output for a selection of benchmarked products",
    shots: ["p5-112-benchmark-carbon-costs.png"],
  },
  {
    id: "carbon-leakage-list-targeting",
    title: "Carbon leakage list narrowing under single-indicator methodology (Phase III to IV)",
    category: "industry",
    part: 5,
    keyNumbers: ["~65% reduction in number of NACE 4-digit sectors on carbon leakage list (2015-20 -> 2021-30)", "Only ~2% reduction in direct emissions covered", "Carbon leakage exposure factor: 0.3 for non-listed sectors (2021-25), was 0.8->0.3 through Phase III"],
    figureOrTable: "Figure 22",
    pdfPages: [117],
    whyImportant: "Shows how the 2018 reform re-targeted free allocation - fewer sectors protected but almost same emissions coverage, a key carbon-leakage/CBAM design reference.",
    quote: "the adoption of a single based indicator reduced the number of sectors...declined by around 65%...direct emissions...covered only declined by around 2%",
    shots: ["p5-117-carbon-leakage-list.png"],
  },
  {
    id: "indirect-cost-compensation-growth",
    title: "Indirect Carbon Cost (ICC) compensation growth 2017-2023",
    category: "industry",
    part: 5,
    keyNumbers: ["EUR 0.5bn (2017)", "EUR 1.8bn (2019)", "EUR 2.3bn (2020)", "EUR 3.1bn (2022)", "EUR 5.5bn (2023)", "16% of 2022 auction revenue in 15 MS providing ICC"],
    figureOrTable: "Figure 26 / text",
    pdfPages: [125, 126],
    whyImportant: "Tracks the fiscal cost of protecting electro-intensive industry from indirect (electricity) carbon costs - a rapidly rising figure tied to EUA price increases.",
    quote: "Total ICC compensation has risen over time, from EUR 0.5bn for costs incurred in 2017...to EUR 5.5 bn in 2023",
    shots: ["p5-125-icc-compensation-history.png"],
  },
  {
    id: "carbon-leakage-empirical-evidence",
    title: "Emerging empirical evidence of carbon leakage (recent studies)",
    category: "industry",
    part: 5,
    keyNumbers: ["Wang & Kuusi (2024): +13% carbon content of EU imports, -12% carbon content of EU exports", "Misch & Wingender (2024): carbon leakage rate 0.15 for EU14+ group", "OECD (2024): median leakage rate ~3% (100t domestic reduction -> +3t imported emissions)", "Kanzig et al: African subsidiary emissions of French multinationals grew 2.4x more than German subsidiaries"],
    figureOrTable: "text",
    pdfPages: [139, 140],
    whyImportant: "Represents the frontier of quantitative carbon-leakage-rate estimates now being found in the literature as EU carbon prices rise and free allocation shrinks.",
    quote: "A carbon leakage rate of 0.15 is estimated for the EU14+ group...median leakage rate was estimated by the OECD at around 3%",
    shots: [],
  },
  {
    id: "eib-cost-effectiveness-elasticity",
    title: "EIB (2024) elasticity of carbon efficiency/emissions to ETS price",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["1% increase in ETS price -> 0.04% improvement in carbon efficiency", "1% increase in ETS price -> 0.05% decrease in emissions (regulated manufacturing sectors, 2012-2022)"],
    figureOrTable: "text",
    pdfPages: [33],
    whyImportant: "One of the few quantified econometric price-elasticity estimates in the document linking carbon price level directly to emissions/efficiency outcomes.",
    quote: "a 1% increase in ETS prices leads to an improvement of carbon efficiency by 0.04% and a decrease in emissions of 0.05% in regulated sectors",
    shots: [],
  },
  {
    id: "phase-iv-free-allocation-emissions-elasticity",
    title: "Willemaers (2025): Phase IV free allocation cut -> emissions response",
    category: "mitigation-cost",
    part: 5,
    keyNumbers: ["10% reduction in free allocation -> ~3.5% lower verified emissions (post-2021)"],
    figureOrTable: "text",
    pdfPages: [35],
    whyImportant: "Direct causal estimate for Phase IV (the most policy-relevant period) of how free-allocation cuts translate into installation-level abatement.",
    quote: "a 10% reduction in free allocation is associated with roughly 3.5% lower verified emissions in the post-2021 period",
    shots: [],
  },
  {
    id: "auction-revenue-total",
    title: "EU ETS auctioning revenue and volumes 2015-2023/2018-2024",
    category: "macro",
    part: 5,
    keyNumbers: ["5+ billion allowances auctioned 2015-2023", "EUR 169 billion+ auction revenue 2015-2023 (evaluation period)", "EUR 250 billion+ cumulative to date", "EUR 196 billion auction revenue 2018-2024 (Appendix IV)", "EUR 20 billion raised for RRF/REPowerEU (2023)"],
    figureOrTable: "Figure 38 / Table (Appendix IV)",
    pdfPages: [220, 236, 238, 241],
    whyImportant: "The headline EU ETS revenue figures - core input for any macro/fiscal modelling of ETS revenue recycling, Innovation Fund and Modernisation Fund financing.",
    quote: "over 5 billion allowances were auctioned, generating more than 169 billion EUR",
    shots: ["p5-220-auction-revenue-history.png"],
  },
  {
    id: "tnac-msr-trajectory",
    title: "TNAC (Total Number of Allowances in Circulation) trajectory and MSR intake/invalidation",
    category: "scenarios",
    part: 5,
    keyNumbers: ["TNAC 2012 baseline: 1,750 MEUA", "Historical surplus above threshold: 917 MEUA", "TNAC 2018 (pre-MSR): 1,655 MEUA", "TNAC 2024: 1,148 MEUA (target 833 MEUA)", "Cumulative MSR intake 2019-2024: 2,058 MEUA", "Invalidations 2023-2025: 3,167 million allowances (23.4% of Phase III supply)"],
    figureOrTable: "Figures 11-16",
    pdfPages: [55, 56, 57, 62, 63],
    whyImportant: "Complete quantitative account of the MSR's core supply-management mechanism - essential for any allowance-supply/carbon-price modelling of the EU ETS.",
    quote: "there was an excess historical surplus of 917 million EUA in 2012...total operational intake until 2024 was 2,058 million EUA",
    shots: ["p5-062-tnac-msr-history.png"],
  },
  {
    id: "eu-added-value-cost-of-fragmentation",
    title: "EU added value: cost of national vs EU-wide ETS",
    category: "macro",
    part: 5,
    keyNumbers: ["Reaching Kyoto targets without EU-wide system estimated >=20% more expensive", "Low-carbon innovation up to +30% in regulated firms, +15% revenues, +8% fixed assets (2005-2012)"],
    figureOrTable: "text",
    pdfPages: [77, 78],
    whyImportant: "Quantifies the cost-effectiveness gain from EU-level harmonisation vs a counterfactual patchwork of national systems - relevant for institutional design/coherence assessments.",
    quote: "Pre-implementation modelling estimated that reaching the EU's Kyoto targets without a common EU-wide system would have been at least 20% more expensive",
    shots: [],
  },
  {
    id: "ets-discontinuation-cost-benefit",
    title: "Estimated impact of hypothetically stopping the EU ETS (2023)",
    category: "macro",
    part: 5,
    keyNumbers: ["Loss of ~EUR 93 billion in allowance value (2023 TNAC x price)", "Avoided compliance cost ~EUR 44 billion (2023 auctions)", "External costs from energy-intensive industry: EUR 73 billion in 2021 (down 23% since 2012)", "Central external cost of carbon: EUR2016 100/tCO2 (~EUR2023 120/tCO2)"],
    figureOrTable: "text",
    pdfPages: [79, 80],
    whyImportant: "A rare explicit counterfactual macro cost-benefit calculation for discontinuing the ETS - useful reference for total system value.",
    quote: "a discontinuation of the ETS in 2023 would have led to a loss of approximately EUR 93 billion in allowance value...companies would not have been subject to compliance worth approximately EUR 44 billion",
    shots: [],
  },
  {
    id: "wind-solar-tipping-point-2025",
    title: "Wind and solar overtake fossil generation in EU power mix (2025)",
    category: "technology-scaling",
    part: 5,
    keyNumbers: ["Wind+solar: 30.1% of EU electricity in 2025 (841 TWh)", "Fossil sources: 29% (809 TWh)", "Wind+solar share +10pp since 2020; fossil share -8pp since 2020"],
    figureOrTable: "text (Ember 2026 report cited)",
    pdfPages: [26, 27],
    whyImportant: "Documents the 2025 tipping point where renewables overtook fossil generation in the EU power sector - key technology-scaling milestone tied to ETS price signal.",
    quote: "wind and solar accounted for 30.1% of EU electricity in 2025 (841 TWh), whereas all the fossil power sources in the EU accounted for 29% (809 TWh)",
    shots: ["p5-026-ets-emissions-since-2005.png"],
  },
  {
    id: "aluminium-steel-capacity-losses",
    title: "Industrial capacity losses cited by trade associations (carbon leakage evidence)",
    category: "industry",
    part: 5,
    keyNumbers: ["EU primary aluminium smelting capacity down ~50% since ETS start, 30% since 2008", "EU steel production down ~30 Mt since 2017-18 (10 Mt on export markets)", "EU ammonia production down from ~15 Mt to ~10 Mt", "FuelsEurope: ~30 refineries closed, 85 remaining"],
    figureOrTable: "text (stakeholder interviews)",
    pdfPages: [143, 144, 145],
    whyImportant: "Aggregates industry-reported capacity/output losses used as qualitative carbon-leakage evidence, frequently cited in competitiveness debates even though the SWD attributes much of this to non-ETS factors.",
    quote: "the EU has lost around 50% of its primary aluminium smelting capacity, with 30% lost since 2008 alone",
    shots: [],
  },
];
// ── Source documents ────────────────────────────────────────────────────────
export const IA_DOCS = [
  { label: 'SWD(2026) 616 — landing page (all parts)', url: 'https://climate.ec.europa.eu/publications/swd2026-616-impact-assessment_en' },
  { label: 'Part 1 — Main report (108 pp)', url: 'https://climate.ec.europa.eu/document/download/6dffbc5a-b5f3-4c51-b999-a6243e155e8c_en?filename=swd_2026_616_part_1_en.pdf' },
  { label: 'Part 2 — Annexes 1–7 (127 pp)', url: 'https://climate.ec.europa.eu/document/download/1ab67b2d-b5b7-46d7-abe4-38273a233080_en?filename=swd_2026_616_part_2_en.pdf' },
  { label: 'Part 3 — Annexes 8–11 (315 pp)', url: 'https://climate.ec.europa.eu/document/download/63c0103a-6b5f-4151-b117-b3c4b35b5d0e_en?filename=swd_2026_616_part_3_en.pdf' },
  { label: 'Part 4 — Annexes 12–14 (160 pp)', url: 'https://climate.ec.europa.eu/document/download/42652813-1d08-4a09-8194-80a35592e816_en?filename=swd_2026_616_part_4_en.pdf' },
  { label: 'Part 5 — Annex 15, evaluation (248 pp)', url: 'https://climate.ec.europa.eu/document/download/99598752-a214-4e89-bddd-6aeb10a96d0d_en?filename=swd_2026_616_part_5_en.pdf' },
  { label: 'Supplementary information (techno-economic assumptions, xlsx)', url: 'https://climate.ec.europa.eu/document/download/0b06b0da-d587-4554-aeb2-9eef4de83758_en?filename=swd_2026_616_supplementary_information_en.xlsx' },
];

// ── Techno-economic assumptions (supplementary xlsx, © E3-Modelling / WSP) ──
// Curated flagship rows from the PRIMES input assumptions published alongside
// the impact assessment. Investment cost per unit of capacity; rounded.
export interface TechCostRow {
  tech: string; group: string; unit: string;
  current: number | null; y2030: number | null; y2040: number | null; ultimate: number | null;
  note?: string;
}

export const IA_TECH_COSTS: TechCostRow[] = [
  { group: 'Clean fuels', tech: 'Electrolyser — low-temp. water electrolysis (mid variant)', unit: 'EUR/kW output', current: 2195, y2030: 1155, y2040: 825, ultimate: 590, note: 'Steepest modelled cost decline of any technology.' },
  { group: 'Clean fuels', tech: 'Hydrogen from natural gas SMR (no CCS)', unit: 'EUR/kW output', current: 830, y2030: 750, y2040: 720, ultimate: 720 },
  { group: 'Clean fuels', tech: 'Hydrogen from biomass/waste gasification', unit: 'EUR/kW output', current: 1950, y2030: 1510, y2040: 1250, ultimate: 1180 },
  { group: 'Clean fuels', tech: 'Fischer–Tropsch synthesis (e-fuels)', unit: 'EUR/kW FT output', current: 2040, y2030: 1628, y2040: 1232, ultimate: 880 },
  { group: 'Clean fuels', tech: 'Methanol synthesis', unit: 'EUR/kW output', current: 1685, y2030: 1419, y2040: 1246, ultimate: 830 },
  { group: 'Carbon capture', tech: 'Direct air capture — absorption', unit: 'EUR/unit capacity', current: 850, y2030: 715, y2040: 640, ultimate: 570 },
  { group: 'Carbon capture', tech: 'Direct air capture — adsorption', unit: 'EUR/unit capacity', current: 1385, y2030: 985, y2040: 765, ultimate: 545 },
  { group: 'Power', tech: 'Wind offshore (shallow, near-shore)', unit: 'EUR/kW', current: 3520, y2030: 2050, y2040: 1760, ultimate: 1640, note: '2020 value as "current".' },
  { group: 'Power', tech: 'Gas combined cycle + CCS (post-combustion)', unit: 'EUR/kW', current: 2470, y2030: 2235, y2040: 1938, ultimate: 1790, note: '2020 value as "current"; "ultimate" = 2050.' },
  { group: 'Power', tech: 'Nuclear Gen-III (with economies of scale)', unit: 'EUR/kW', current: 7000, y2030: 6500, y2040: 6000, ultimate: 5500, note: '2020 value as "current"; "ultimate" = 2050.' },
  { group: 'Industry', tech: 'Steel — direct reduction with hydrogen (H2-DRI)', unit: 'EUR/kW th', current: 1466, y2030: 1068, y2040: null, ultimate: 1247, note: '2030/ultimate given as from-values of a range.' },
  { group: 'Industry', tech: 'Steel — electric arc furnace', unit: 'EUR/kW th', current: 2458, y2030: 2212, y2040: null, ultimate: 1966, note: '2030/ultimate given as from-values of a range.' },
];
