/**
 * Validate article-level citations against a policy's consolidated EUR-Lex text.
 *
 * The Policy Navigator renders article-level citations on connection edges
 * (e.g. "Article 5(1)", "Article 30(2)") that were generated by an LLM and
 * carry an "AI-generated links" badge. Until now, nothing checked whether
 * the cited article actually exists in the referenced policy. This module
 * provides a fast, deterministic validation pass:
 *
 *   1. Parse the free-form citation string into a list of normalised refs
 *      ("Article 5", "Article 30(2)", …).
 *   2. For each ref, scan the policy text for an article anchor matching
 *      the same number. Sub-paragraph qualifiers ("(1)") are optional —
 *      we accept the article if the *primary* article number is present.
 *
 * The function is intentionally permissive: it is meant to catch obvious
 * hallucinations (e.g. "Article 99" in a regulation that only has 25
 * articles), not to be a fully spec-compliant citation parser.
 */

export type CitationStatus = 'valid' | 'not-found' | 'unparseable';

export interface CitationCheck {
  /** The slice of the original input that produced this ref. */
  raw: string;
  /** Normalised reference ("Article 5", "Article 30(2)", …) — undefined when the slice could not be parsed. */
  ref?: string;
  /** Primary article number ("5", "30") — undefined when unparseable. */
  number?: string;
  /** Optional sub-paragraph qualifier ("1", "2", "1(a)") if the citation specified one. */
  qualifier?: string;
  status: CitationStatus;
  /** Short snippet of the matching anchor, lifted from the policy text. */
  snippet?: string;
}

export interface CitationValidationResult {
  citations: CitationCheck[];
  validCount: number;
  notFoundCount: number;
  unparseableCount: number;
}

/**
 * Split a free-form article citation string into individual ref slices.
 * Handles the common patterns we see in the connection dataset:
 *
 *   "Article 5(1)"
 *   "Articles 5-7"
 *   "Art. 30(2), Article 31"
 *   "5(1)(a) and 7"
 *
 * The parser does not expand ranges like "5-7" into individual articles
 * — that would over-promise correctness. We treat the range as a single
 * ref tagged on its lowest number and let the caller decide.
 */
function splitCitations(input: string): string[] {
  if (!input) return [];
  // Strip leading "Article(s)" / "Art." so the rest of the parser can
  // assume each chunk is a number-led ref.
  const cleaned = input
    .replace(/articles?/gi, '')
    .replace(/\bart\.?\b/gi, '')
    .replace(/\band\b/gi, ',')
    .replace(/\s+/g, ' ');
  return cleaned
    .split(/[,;]+/)
    .map(s => s.trim())
    .filter(Boolean);
}

/** Parse one slice into a structured ref. Returns undefined on garbage. */
function parseRef(slice: string): { number: string; qualifier?: string } | undefined {
  // Match: leading article number, optional parenthesised qualifier,
  // optional letter sub-qualifier. Reject strings that don't start with
  // a digit so things like "TFEU" don't slip through.
  const m = slice.match(/^\s*(\d{1,4})\s*((?:\(\s*[a-z0-9ivxIVX]+\s*\))*)/);
  if (!m) return undefined;
  const number = m[1];
  const tail = m[2]?.replace(/\s+/g, '');
  const qualifier = tail || undefined;
  return { number, qualifier };
}

/**
 * Look for the article anchor in the policy text. EUR-Lex consolidated
 * texts use "Article N" on its own line as the section header, so an
 * anchored regex catches the canonical case without false positives
 * from prose mentions like "Article 5 of Regulation …".
 */
function findArticleAnchor(text: string, number: string): { snippet?: string } | null {
  // Anchor 1: "Article N" at the start of a line — the canonical heading.
  const headingRe = new RegExp(String.raw`(?:^|\n)\s*Article\s+${number}\b`, 'i');
  const m = text.match(headingRe);
  if (m) {
    const idx = m.index ?? 0;
    const snippet = text.slice(idx, idx + 80).replace(/\s+/g, ' ').trim();
    return { snippet };
  }
  // Anchor 2: any inline "Article N" mention. Less authoritative but a
  // perfectly valid signal that the article exists in the document.
  const inlineRe = new RegExp(String.raw`\bArticle\s+${number}\b`);
  const im = text.match(inlineRe);
  if (im) {
    const idx = im.index ?? 0;
    const snippet = text.slice(idx, idx + 80).replace(/\s+/g, ' ').trim();
    return { snippet };
  }
  return null;
}

export function validateArticleCitations(
  citationString: string | null | undefined,
  policyText: string,
): CitationValidationResult {
  const slices = splitCitations(citationString ?? '');
  const checks: CitationCheck[] = [];
  for (const raw of slices) {
    const parsed = parseRef(raw);
    if (!parsed) {
      checks.push({ raw, status: 'unparseable' });
      continue;
    }
    const ref = parsed.qualifier
      ? `Article ${parsed.number}${parsed.qualifier}`
      : `Article ${parsed.number}`;
    const anchor = findArticleAnchor(policyText, parsed.number);
    if (anchor) {
      checks.push({
        raw,
        ref,
        number: parsed.number,
        qualifier: parsed.qualifier,
        status: 'valid',
        snippet: anchor.snippet,
      });
    } else {
      checks.push({
        raw,
        ref,
        number: parsed.number,
        qualifier: parsed.qualifier,
        status: 'not-found',
      });
    }
  }
  return {
    citations: checks,
    validCount: checks.filter(c => c.status === 'valid').length,
    notFoundCount: checks.filter(c => c.status === 'not-found').length,
    unparseableCount: checks.filter(c => c.status === 'unparseable').length,
  };
}
