// PLACEHOLDER — text below is a structural draft. The DPO and the
// ESABCC secretariat must review and adapt it before launch. Do not rely
// on it as legal advice.

export const metadata = {
  title: 'Privacy notice — ESABCC Method Hub',
  description: 'How the ESABCC Method Hub processes personal data of secretariat staff.',
};

const LAST_REVIEW = '2026-04-22';

export default function PrivacyPage() {
  return (
    <>
      <h1>Privacy notice</h1>
      <p className="text-xs text-[#3D5265]/60">Last reviewed: {LAST_REVIEW}</p>

      <p>
        The ESABCC Method Hub (&ldquo;the platform&rdquo;) is an internal tool
        for the secretariat of the European Scientific Advisory Board on
        Climate Change. This notice explains what personal data the
        platform processes about secretariat staff and how those rights are
        exercised.
      </p>

      <h2>1. Controller</h2>
      <p>
        {/* TODO(legal): replace with the formal controller designation —
            usually the European Environment Agency on behalf of ESABCC. */}
        <em>Controller: TODO — confirm with the EEA Data Protection Officer.</em>
      </p>

      <h2>2. Data Protection Officer</h2>
      <p>
        {/* TODO(legal): the EEA DPO contact must be filled in. */}
        <em>DPO contact: TODO.</em>
      </p>

      <h2>3. Categories of personal data</h2>
      <ul>
        <li>Account data: email address, display name, avatar URL, optional bio.</li>
        <li>Authentication metadata: hashed password, last sign-in timestamp, session tokens (handled by Supabase Auth).</li>
        <li>Content you create: annotations, comments, custom tags, personal and shared reading-list entries, upvotes.</li>
        <li>Activity log: a record of actions you perform (annotation/comment/tag/post/reading-list events) used for the per-user activity view.</li>
        <li>Server-side access logs (IP address, user-agent, timestamp) generated by Vercel and Supabase as sub-processors.</li>
      </ul>

      <h2>4. Purposes and lawful basis</h2>
      <ul>
        <li>
          Operating the internal collaboration features (annotations, comments, reading lists). Lawful basis:
          {' '}<strong>Article 6(1)(e) GDPR</strong> &mdash; performance of a task carried out in the public interest by the secretariat.
        </li>
        <li>
          Account security and abuse prevention (rate limiting, audit log). Lawful basis:
          {' '}<strong>Article 6(1)(f) GDPR</strong> &mdash; legitimate interests of the controller in operating a secure service.
        </li>
        <li>
          AI summarisation of newsletter and policy text. Lawful basis: <strong>Article 6(1)(a) GDPR</strong> &mdash; explicit consent
          captured in your profile (see &ldquo;LLM processing consent&rdquo;).
        </li>
      </ul>

      <h2>5. Recipients and sub-processors</h2>
      <ul>
        <li>Supabase &mdash; managed Postgres + Auth (DPA: TODO link).</li>
        <li>Vercel &mdash; web hosting and edge logging (DPA: TODO link).</li>
        <li>GitHub &mdash; CI / scheduled jobs (DPA: TODO link).</li>
        <li>
          Optional LLM providers (only if you opt in): Anthropic, OpenAI, Google, Microsoft Azure OpenAI.
          ESABCC operates Azure OpenAI in an EU region as the default; the others are US-based and rely on
          Standard Contractual Clauses (SCCs) for transfers.
        </li>
      </ul>

      <h2>6. International transfers</h2>
      <p>
        Data may be transferred outside the EEA only when you opt in to LLM features that use a non-EU
        provider. Those transfers are covered by Standard Contractual Clauses; you can revoke consent at any
        time from your profile.
      </p>

      <h2>7. Retention</h2>
      <ul>
        <li>Activity-log entries: 365 days (configurable via <code>app.activity_log_retention_days</code>).</li>
        <li>Inbound newsletter store: 730 days; sender addresses redacted to domain after 180 days.</li>
        <li>Account data and your content: until you delete your account or it is deleted by an admin.</li>
        <li>Deletion requests: enacted after a 30-day grace period during which you can cancel.</li>
        <li>Server access logs: managed by sub-processors; see their respective DPAs.</li>
      </ul>

      <h2>8. Your rights</h2>
      <p>You may exercise the following rights from the <a href="/profile">Your data</a> section of your profile:</p>
      <ul>
        <li><strong>Access (Art. 15)</strong> &mdash; the activity-log view shows your own actions; the data export contains everything else.</li>
        <li><strong>Rectification (Art. 16)</strong> &mdash; update display name and bio in your profile; for other fields contact the DPO.</li>
        <li><strong>Erasure (Art. 17)</strong> &mdash; &ldquo;Delete my account&rdquo; schedules deletion after a 30-day grace period.</li>
        <li><strong>Portability (Art. 20)</strong> &mdash; &ldquo;Download my data&rdquo; returns a machine-readable JSON copy of your data.</li>
        <li><strong>Objection (Art. 21)</strong> &mdash; contact the DPO to object to any processing based on legitimate interest.</li>
        <li>
          <strong>Complaint</strong> &mdash; you may lodge a complaint with the European Data Protection Supervisor at any time.
        </li>
      </ul>

      <h2>9. Cookies and local storage</h2>
      <p>
        See the <a href="/legal/cookies">cookie notice</a> for the full list. The platform uses only
        strictly-necessary storage by default (authentication session cookie). All other features that use
        local storage require your explicit consent via the consent banner.
      </p>

      <h2>10. Changes</h2>
      <p>
        We update this notice as the platform evolves. The &ldquo;last reviewed&rdquo; date above reflects the most
        recent change.
      </p>
    </>
  );
}
