'use client';

/**
 * Overview Industry — Trade flows — FIGARO dataset access layer.
 * --------------------------------------------------------------
 * Types, loaders and aggregation helpers for the repo-hosted FIGARO extract
 * (`public/data/figaro/*.json`, regenerated by
 * `scripts/fetch-figaro-io-dataset.mjs` from Eurostat `naio_10_fcp_ii4`).
 * The data is served from the MethodHub itself — the client fetches the JSON
 * once and every view (table viewer, analysis dashboard) derives from it.
 */

export const FIGARO_DATASET_URL =
  'https://ec.europa.eu/eurostat/databrowser/view/naio_10_fcp_ii4/default/table?lang=en';
export const IO_JSON_PATH = '/data/figaro/figaro-io-eu27.json';
export const GLOBAL_JSON_PATH = '/data/figaro/figaro-global-flows.json';

export const FIGARO_MATRIX_YEARS = ['2022', '2023'] as const;
export type FigaroYear = (typeof FIGARO_MATRIX_YEARS)[number];

export interface FigaroIoData {
  meta: { dataset: string; title: string; source: string; unit: string; years: string[]; generated: string; note: string };
  /** Code → English label, for industries, VA rows and final-demand columns. */
  industries: Record<string, string>;
  /** Country code → English name. */
  countries: Record<string, string>;
  /** Row axis: 64 industries + 6 value-added/adjustment rows. */
  indAva: string[];
  /** Column axis: 64 industries + 5 final-demand categories. */
  indUse: string[];
  nIndustries: number;
  /** 'EU27' (intra-EU incl. VA rows) + 23 extra-EU partner areas. */
  origins: string[];
  /** matrix[year][origin][rowIdx][colIdx], € million. */
  matrix: Record<FigaroYear, Record<string, number[][]>>;
}

export interface FigaroGlobalData {
  meta: { dataset: string; source: string; unit: string; years: string[]; generated: string; note: string };
  countries: string[];
  countryNames: Record<string, string>;
  euMembers: string[];
  extra: string[];
  industries: string[];
  /** countryFlows[year].int|fin[origIdx][destIdx], € million. */
  countryFlows: Record<FigaroYear, { int: number[][]; fin: number[][] }>;
  /** euExportsByIndustry[year].int|fin[industryIdx][extraDestIdx], € million. */
  euExportsByIndustry: Record<FigaroYear, { int: number[][]; fin: number[][] }>;
}

let ioPromise: Promise<FigaroIoData> | null = null;
let globalPromise: Promise<FigaroGlobalData> | null = null;

export function loadFigaroIo(): Promise<FigaroIoData> {
  if (!ioPromise) {
    ioPromise = fetch(IO_JSON_PATH).then((r) => {
      if (!r.ok) throw new Error(`Failed to load ${IO_JSON_PATH} (HTTP ${r.status})`);
      return r.json();
    });
  }
  return ioPromise;
}

export function loadFigaroGlobal(): Promise<FigaroGlobalData> {
  if (!globalPromise) {
    globalPromise = fetch(GLOBAL_JSON_PATH).then((r) => {
      if (!r.ok) throw new Error(`Failed to load ${GLOBAL_JSON_PATH} (HTTP ${r.status})`);
      return r.json();
    });
  }
  return globalPromise;
}

/* ------------------------------------------------------------- classification */

/** NACE section letter of an A*64 industry code ('C10-12' → 'C'). */
export const sectionOf = (code: string): string => code[0];

export const SECTION_LABELS: Record<string, string> = {
  A: 'Agriculture, forestry & fishing',
  B: 'Mining & quarrying',
  C: 'Manufacturing',
  D: 'Electricity & gas',
  E: 'Water & waste',
  F: 'Construction',
  G: 'Wholesale & retail trade',
  H: 'Transportation & storage',
  I: 'Accommodation & food',
  J: 'Information & communication',
  K: 'Financial & insurance',
  L: 'Real estate',
  M: 'Professional, scientific & technical',
  N: 'Administrative & support',
  O: 'Public administration',
  P: 'Education',
  Q: 'Health & social work',
  R: 'Arts & entertainment',
  S: 'Other services',
  T: 'Households as employers',
  U: 'Extraterritorial bodies',
};

export const FINAL_DEMAND_LABELS: Record<string, string> = {
  P3_S13: 'Government consumption',
  P3_S14: 'Household consumption',
  P3_S15: 'NPISH consumption',
  P51G: 'Gross fixed capital formation',
  P5M: 'Changes in inventories & valuables',
};

export const VA_ROW_LABELS: Record<string, string> = {
  B2A3G: 'Gross operating surplus & mixed income',
  D1: 'Compensation of employees',
  D21X31: 'Taxes less subsidies on products',
  D29X39: 'Other taxes less subsidies on production',
  OP_RES: 'Purchases by residents abroad',
  OP_NRES: 'Purchases by non-residents in the EU',
};

/** Short display label: prefer the concise curated names, fall back to Eurostat's. */
export function shortLabel(data: FigaroIoData, code: string): string {
  const curated = FINAL_DEMAND_LABELS[code] ?? VA_ROW_LABELS[code];
  if (curated) return curated;
  const raw = data.industries[code] ?? code;
  const cut = raw.split(/[;(]/)[0].trim();
  return cut.length > 60 ? `${cut.slice(0, 59)}…` : cut;
}

/* --------------------------------------------------------------- origin scopes */

export type OriginSelection = 'TOTAL' | 'EU27' | 'EXTRA' | string;

export const ORIGIN_SCOPES: { id: OriginSelection; label: string }[] = [
  { id: 'TOTAL', label: 'All origins (total economy)' },
  { id: 'EU27', label: 'Intra-EU (incl. value added)' },
  { id: 'EXTRA', label: 'Extra-EU imports (all partners)' },
];

/**
 * Resolve an origin selection to a 70×69 matrix (€ million). Sums are cheap
 * (24 × 4 830 additions) — memoise at the call site with useMemo.
 */
export function matrixFor(data: FigaroIoData, year: FigaroYear, origin: OriginSelection): number[][] {
  const byOrigin = data.matrix[year];
  if (origin !== 'TOTAL' && origin !== 'EXTRA') return byOrigin[origin] ?? [];
  const codes = data.origins.filter((o) => (origin === 'EXTRA' ? o !== 'EU27' : true));
  const rows = data.indAva.length;
  const cols = data.indUse.length;
  const out: number[][] = Array.from({ length: rows }, () => new Array(cols).fill(0));
  for (const o of codes) {
    const m = byOrigin[o];
    if (!m) continue;
    for (let r = 0; r < rows; r++) {
      const src = m[r];
      const dst = out[r];
      for (let c = 0; c < cols; c++) dst[c] += src[c];
    }
  }
  return out;
}

/* ------------------------------------------------------------------ formatting */

/** € million → compact € billion string. */
export const fmtBn = (mio: number): string => {
  const bn = mio / 1000;
  const abs = Math.abs(bn);
  if (abs >= 1000) return `${(bn / 1000).toFixed(2)} tn`;
  if (abs >= 100) return `${bn.toFixed(0)} bn`;
  if (abs >= 1) return `${bn.toFixed(1)} bn`;
  if (abs >= 0.05) return `${bn.toFixed(2)} bn`;
  return `${mio.toFixed(0)} m`;
};

export const fmtCell = (mio: number): string => {
  const bn = mio / 1000;
  const abs = Math.abs(bn);
  if (abs >= 100) return bn.toFixed(0);
  if (abs >= 10) return bn.toFixed(1);
  if (abs >= 0.05) return bn.toFixed(2);
  return '·';
};
