'use client';

/**
 * Overview Industry — Trade flows — FIGARO input–output data.
 * -----------------------------------------------------------
 * The full FIGARO EU inter-country input–output table, imported into the
 * MethodHub (`public/data/figaro/`) and explorable in place: an analysis
 * dashboard, a filterable table viewer of the complete EU-27 matrix, and the
 * provenance/download panel. Regenerated by
 * `scripts/fetch-figaro-io-dataset.mjs` from Eurostat `naio_10_fcp_ii4`.
 */

import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import FigaroExplorer from './FigaroExplorer';

export default function FigaroPage() {
  return (
    <div className="min-h-screen bg-grey-50 dark:bg-[var(--mh-bg)] dark:text-[var(--mh-fg)]">
      <SiteHeader />

      <main className="mx-auto max-w-wide px-4 py-8">
        <nav className="mb-4 text-sm text-grey-500 dark:text-[var(--mh-muted)]">
          <Link href="/beta/overview-industry" className="hover:underline">
            Overview Industry
          </Link>
          <span className="mx-1">/</span>
          <Link href="/beta/overview-industry/trade-flows" className="hover:underline">
            Trade flows
          </Link>
          <span className="mx-1">/</span>
          <span className="text-grey-700 dark:text-[var(--mh-muted)]">FIGARO IO data</span>
        </nav>

        <header className="mb-6">
          <div className="flex flex-wrap items-center gap-2">
            <span className="rounded bg-[#7A4400] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-white">
              Beta
            </span>
            <span className="rounded border border-primary-lighter bg-surface-blue dark:bg-primary/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-primary">
              FIGARO · naio_10_fcp_ii4
            </span>
            <span className="rounded bg-grey-200 dark:bg-[var(--mh-border)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-tertiary">
              Data hosted on the MethodHub
            </span>
          </div>
          <h1 className="mt-2 text-3xl font-bold text-grey-900 dark:text-[var(--mh-fg)]">
            FIGARO input–output data — table viewer &amp; analysis
          </h1>
          <p className="mt-2 max-w-text text-grey-700 dark:text-[var(--mh-muted)]">
            The complete Eurostat <span className="font-semibold">FIGARO</span> inter-country input–output
            table (industry by industry, 2022–2023), imported into the MethodHub and aggregated to the EU-27
            as one economy: 64 industries + value added on the supply side, 64 industries + final demand on
            the use side, and every origin from intra-EU to each of the 23 partner areas. Browse it as an{' '}
            <span className="font-semibold">analysis dashboard</span> or cell by cell in the{' '}
            <span className="font-semibold">table viewer</span>, slice it, and download any view as CSV — the
            data is served from this site, not from an external link.
          </p>
        </header>

        <section className="rounded-xl border border-grey-200 dark:border-[var(--mh-border)] bg-white dark:bg-[var(--mh-card)] p-4 shadow-sm sm:p-5">
          <FigaroExplorer />
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
