/**
 * Climate Security Ledger — avoided fossil imports (beta module M · 45).
 * Calibration anchors: EU-27 fossil demand, import shares, activity index,
 * border prices, supplier shares and 2030 projection levels.
 *
 * PROVENANCE (read before citing anything)
 * ----------------------------------------
 * Partly generated from live sources, partly AI-compiled — see the split
 * below, which is the whole point of this header. Last refresh: 2026-08-06.
 *
 * The file originally shipped with every figure recalled from the
 * assistant's own knowledge, on the belief that Eurostat was blocked from
 * this sandbox. It is NOT blocked — the dissemination API answers plain
 * HTTPS — so the volume and trade side of the module has been rebuilt from
 * live pulls, and the fact-check that did so is recorded in
 * docs-internal/beta-modules-m45-m52-factcheck-2026-08.md.
 *
 * GENERATED FROM LIVE SOURCES — do not hand-edit, re-run the script:
 *   · YEARS, DEMAND, IMPORT_SHARE, ACTIVITY, RUSSIAN_SHARE_PRE2022,
 *     GAS_SUPPLIER_MIX, RUSSIAN_SHARE_2024, EU_POPULATION_M
 *     ← scripts/refresh-climate-security-eurostat.mjs, from Eurostat
 *       `nrg_cb_gas`, `nrg_cb_oil`, `nrg_cb_sff`, `nrg_ind_id`,
 *       `nrg_ti_gas`, `nrg_ti_oil`, `nrg_ti_sff`, `nama_10_gdp`,
 *       `demo_gind`. Snapshot: public/data/climate-security/
 *       eurostat-snapshot.json.
 *   · PRICES, PRICE_SCENARIO_META
 *     ← scripts/refresh-climate-security-prices.mjs, from the World Bank
 *       Commodity Price Data (Pink Sheet) annual and monthly series and
 *       ECB euro reference rates. Snapshot: price-snapshot.json.
 *
 * STILL AI-COMPILED — pending Secretariat verification:
 *   · PROJ_2030 and IMPORT_SHARE_2030. The EEA publishes GHG aggregates,
 *     not per-fuel 2030 demand, so the per-fuel split is inferred and
 *     carries the widest ranges in this file. It is flagged as such in the
 *     UI and is the outstanding work item for this module.
 *
 * Unit conventions:
 *   · gas in bcm — taken from Eurostat's own million-cubic-metre series,
 *     so no calorific-value conversion enters the volume side; oil in Mt,
 *     hard coal in Mt — the natural units of each trade discussion;
 *   · prices are stored in € million per native volume unit (gas: €m/bcm;
 *     oil and coal: €/t, which is numerically identical to €m/Mt), so
 *     volume × price is always € million;
 *   · shares (import shares, supplier shares) are stored on the 0–100
 *     percent scale, per the repository convention; model.ts divides
 *     by 100.
 */

export type Fuel = 'gas' | 'oil' | 'coal';
export type PriceScenario = 'avg2019' | 'crisis2022' | 'forward';
export type PathKey = 'wem' | 'wam' | 'advised';

/** A value with an explicit disagreement/uncertainty range and a source locator. */
export type SourcedRange = { value: number; lo: number; hi: number; source: string };

export const FUELS: Fuel[] = ['gas', 'oil', 'coal'];

export const FUEL_META: Record<Fuel, { label: string; unit: string; priceUnit: string }> = {
  gas: { label: 'Natural gas', unit: 'bcm', priceUnit: '€m/bcm' },
  oil: { label: 'Oil & petroleum products', unit: 'Mt', priceUnit: '€/t' },
  coal: { label: 'Hard coal', unit: 'Mt', priceUnit: '€/t' },
};

/* EUROSTAT-BEGIN — generated by scripts/refresh-climate-security-eurostat.mjs on 2026-08-06.
 * Do not hand-edit anything between these markers: change the query in the
 * script and re-run it. Every series below is a live Eurostat observation,
 * not an estimate, so the earlier "± 5 %" compile tolerances are gone —
 * what remains is the definitional caveat stated on each entry. */

/** Observation years of the backward-looking leg. */
export const YEARS: number[] = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024];

/**
 * EU-27 fossil demand per year, natural units (gas bcm; oil, coal Mt),
 * straight from Eurostat in each fuel's own reported unit.
 */
export const DEMAND: Record<Fuel, { series: number[]; tolerance: string; source: string }> = {
  gas: {
    //       2015  2016  2017  2018  2019  2020  2021  2022  2023  2024
    series: [361.7, 381.9, 407.8, 399.7, 412.2, 399.6, 415.3, 362.6, 332.6, 334.1],
    tolerance: 'Reported values, not estimates. Definitional caveat: inland consumption (calculated), which includes transformation input and own use.',
    source:
      'Eurostat nrg_cb_gas, EU-27 natural gas inland consumption (calculated), million cubic metres → bcm. Reported in volume by Eurostat, so no calorific-value conversion is applied here. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
  oil: {
    series: [468.7, 472.3, 486.1, 480.7, 479.6, 419.7, 438.2, 448.8, 442.6, 444.7],
    tolerance: 'Reported values, not estimates. Definitional caveat: gross inland deliveries excluding the biofuel portion; including it raises every year by roughly 15–20 Mt.',
    source:
      'Eurostat nrg_cb_oil, EU-27 gross inland deliveries (calculated) of oil and petroleum products excluding the biofuel portion, thousand tonnes → Mt. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
  coal: {
    series: [248.0, 240.8, 232.1, 221.3, 178.8, 144.9, 166.2, 163.7, 128.7, 110.6],
    tolerance: 'Reported values, not estimates. Definitional caveat: hard coal only; lignite is excluded because it is almost entirely domestic and carries no import bill.',
    source:
      'Eurostat nrg_cb_sff, EU-27 hard coal inland consumption (calculated), thousand tonnes → Mt. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
};

/**
 * Import share of demand per fuel and year, percent (0–100 scale).
 * Gas and oil use Eurostat's published import-dependency indicator, which is
 * net imports over gross available energy and therefore moves with stock
 * changes as well as with trade — it is NOT a smooth trend, and the 2022
 * spike and 2024 fall below are both real.
 */
export const IMPORT_SHARE: Record<Fuel, { series: number[]; tolerance: string; source: string }> = {
  gas: {
    series: [74.5, 75.7, 80.2, 83.2, 89.7, 83.6, 83.6, 97.6, 90.0, 85.0],
    tolerance: 'Reported indicator values. Can exceed 100 % in a stock-building year, by construction.',
    source: 'Eurostat nrg_ind_id, EU-27 natural-gas import dependency, percent. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
  oil: {
    series: [96.7, 94.7, 93.7, 94.5, 96.7, 96.8, 91.7, 97.8, 94.9, 96.6],
    tolerance: 'Reported indicator values.',
    source: 'Eurostat nrg_ind_id, EU-27 import dependency for oil and petroleum products excluding the biofuel portion, percent. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
  coal: {
    series: [67.1, 66.6, 70.4, 69.8, 70.1, 60.5, 62.6, 77.4, 71.8, 61.2],
    tolerance: 'Derived quotient of two reported series, so it carries both their definitional caveats; bounded to 0–100 by the generator.',
    source:
      'Eurostat nrg_cb_sff, EU-27 hard-coal imports divided by hard-coal inland consumption. The published nrg_ind_id indicator is NOT used for coal because it covers all solid fossil fuels including lignite, which is domestic. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
};

/**
 * EU-27 activity index (real GDP, chain-linked volumes), 2015 = 100.
 * Used to scale the frozen-intensity counterfactual by actual activity.
 */
export const ACTIVITY: { series: number[]; source: string } = {
  //       2015   2016   2017   2018   2019   2020   2021   2022   2023   2024
  series: [100.0, 101.9, 104.8, 106.9, 108.9, 102.9, 109.4, 113.3, 113.8, 115.2],
  source:
    'Eurostat nama_10_gdp, EU-27 GDP at market prices, chain-linked volumes, index 2015 = 100 (CLV_I15) — the rebased index published by Eurostat itself. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
};
/* EUROSTAT-END */

/* PRICES-BEGIN — generated by scripts/refresh-climate-security-prices.mjs on 2026-08-06.
 * Do not hand-edit: change the script and re-run. All three scenarios are
 * OBSERVED annual averages, none is a forecast, and each lo–hi band is a
 * published range rather than a confidence interval of ours. */

/**
 * Border prices per fuel under the three switchable scenarios, in € million
 * per native volume unit (gas €m/bcm; oil and coal €/t ≡ €m/Mt).
 */
export const PRICES: Record<Fuel, Record<PriceScenario, SourcedRange>> = {
  gas: {
    avg2019: {
      value: 154,
      lo: 115,
      hi: 234,
      source:
        'World Bank Commodity Price Data (Pink Sheet), "Natural gas, Europe" 2019 annual average 4.80 $/mmBtu, converted at 3.412142 mmBtu/MWh, ECB 2019 average 1.1195 USD/EUR and 10.55 TWh/bcm. The lo–hi band is the lowest and highest MONTHLY average inside 2019, not an estimate of our uncertainty. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    crisis2022: {
      value: 1379,
      lo: 931,
      hi: 2394,
      source:
        'World Bank Commodity Price Data (Pink Sheet), "Natural gas, Europe" 2022 annual average 40.34 $/mmBtu, converted at 3.412142 mmBtu/MWh, ECB 2022 average 1.0530 USD/EUR and 10.55 TWh/bcm. The lo–hi band is the lowest and highest MONTHLY average inside 2022, not an estimate of our uncertainty. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    forward: {
      value: 381,
      lo: 302,
      hi: 489,
      source:
        'World Bank Commodity Price Data (Pink Sheet), "Natural gas, Europe" 2025 annual average 11.96 $/mmBtu, converted at 3.412142 mmBtu/MWh, ECB 2025 average 1.1300 USD/EUR and 10.55 TWh/bcm. The lo–hi band is the lowest and highest MONTHLY average inside 2025, not an estimate of our uncertainty. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
  },
  oil: {
    avg2019: {
      value: 419.3,
      lo: 388,
      hi: 466.2,
      source:
        'World Bank Pink Sheet, "Crude oil, Brent" 2019 annual average 64.03 $/bbl, converted at 7.33 bbl/t and ECB 2019 average 1.1195 USD/EUR. The lo–hi band is the lowest and highest monthly average inside 2019. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    crisis2022: {
      value: 694.9,
      lo: 563.1,
      hi: 835.8,
      source:
        'World Bank Pink Sheet, "Crude oil, Brent" 2022 annual average 99.82 $/bbl, converted at 7.33 bbl/t and ECB 2022 average 1.0530 USD/EUR. The lo–hi band is the lowest and highest monthly average inside 2022. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    forward: {
      value: 447.8,
      lo: 406.9,
      hi: 513.8,
      source:
        'World Bank Pink Sheet, "Crude oil, Brent" 2025 annual average 69.04 $/bbl, converted at 7.33 bbl/t and ECB 2025 average 1.1300 USD/EUR. The lo–hi band is the lowest and highest monthly average inside 2025. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
  },
  coal: {
    avg2019: {
      value: 66.9,
      lo: 64.3,
      hi: 69.6,
      source:
        'World Bank Pink Sheet steam-coal markers, 2019 annual averages 77.89 $/t (Australian) and 71.94 $/t (South African), converted at ECB 2019 average 1.1195 USD/EUR; the value is the midpoint and the lo–hi band is the two markers. PROXY: the EU border marker is API 2 (CIF ARA), a proprietary Argus/McCloskey index with no free authoritative annual average — in 2022 it ran above both markers used here, so the crisis-year coal bill is if anything understated. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    crisis2022: {
      value: 278,
      lo: 228.4,
      hi: 327.5,
      source:
        'World Bank Pink Sheet steam-coal markers, 2022 annual averages 344.89 $/t (Australian) and 240.56 $/t (South African), converted at ECB 2022 average 1.0530 USD/EUR; the value is the midpoint and the lo–hi band is the two markers. PROXY: the EU border marker is API 2 (CIF ARA), a proprietary Argus/McCloskey index with no free authoritative annual average — in 2022 it ran above both markers used here, so the crisis-year coal bill is if anything understated. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
    forward: {
      value: 89.9,
      lo: 84,
      hi: 95.9,
      source:
        'World Bank Pink Sheet steam-coal markers, 2025 annual averages 108.39 $/t (Australian) and 94.88 $/t (South African), converted at ECB 2025 average 1.1300 USD/EUR; the value is the midpoint and the lo–hi band is the two markers. PROXY: the EU border marker is API 2 (CIF ARA), a proprietary Argus/McCloskey index with no free authoritative annual average — in 2022 it ran above both markers used here, so the crisis-year coal bill is if anything understated. Live pull 2026-08-06 via scripts/refresh-climate-security-prices.mjs.',
    },
  },
};

export const PRICE_SCENARIO_META: Record<PriceScenario, { label: string; hint: string }> = {
  avg2019: { label: '2019 average', hint: 'the last pre-crisis year — the conservative valuation' },
  crisis2022: { label: '2022 crisis', hint: 'full-year 2022 averages, not the August peak' },
  forward: { label: '2025 average', hint: 'the latest complete calendar year — an observed level, not a forward curve' },
};
/* PRICES-END */

/* EUROSTAT-MIX-BEGIN — generated by scripts/refresh-climate-security-eurostat.mjs on 2026-08-06. */

/**
 * Russian share of EU-27 EXTRA-EU imports per fuel BEFORE the 2022 invasion
 * (2021 reference year), percent. Used to state the "avoided Russian
 * imports at the pre-war mix" line.
 */
export const RUSSIAN_SHARE_PRE2022: Record<Fuel, SourcedRange> = {
  gas: {
    value: 44.1,
    lo: 42.1,
    hi: 46.1,
    source:
      'Eurostat nrg_ti_gas, Russia\'s share of EU-27 extra-EU natural-gas imports in 2021, million cubic metres. Intra-EU partners are excluded so onward pipeline flows are not double counted; the ± 2 pp band covers the "not specified" partner residual. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
  },
  oil: {
    value: 25.3,
    lo: 23.3,
    hi: 27.3,
    source: "Eurostat nrg_ti_oil, Russia's share of EU-27 extra-EU CRUDE OIL imports in 2021, thousand tonnes. Refined products are not included in this share. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.",
  },
  coal: {
    value: 52.5,
    lo: 50.5,
    hi: 54.5,
    source: "Eurostat nrg_ti_sff, Russia's share of EU-27 extra-EU HARD COAL imports in 2021, thousand tonnes. Embargoed from August 2022 by Council Reg. (EU) 2022/576. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.",
  },
};

/**
 * Gas import supplier mix, 2021 vs 2024, percent of EXTRA-EU gas imports
 * (pipeline + LNG). Recorded in both directions on purpose: the fall of the
 * Russian share and the rise of the US LNG share — a NEW dependency — are
 * the same story told even-handedly.
 */
export const GAS_SUPPLIER_MIX: {
  rows: { name: string; share2021: number; share2024: number }[];
  tolerance: string;
  source: string;
} = {
  rows: [
    { name: 'Russia (pipeline + LNG)', share2021: 44.1, share2024: 13.6 },
    { name: 'Norway', share2021: 17, share2024: 30.5 },
    { name: 'United States (LNG)', share2021: 5.8, share2024: 16.7 },
    { name: 'North Africa', share2021: 13.5, share2024: 15 },
    { name: 'Other (UK, Azerbaijan, other LNG, not specified)', share2021: 19.6, share2024: 24.3 },
  ],
  tolerance:
    'Reported trade values, but partner attribution is the country of dispatch, not of production — LNG trans-shipment and re-exported pipeline gas can therefore sit under the wrong flag. The "not specified" residual is left inside the Other row rather than redistributed across the named suppliers.',
  source:
    'Eurostat nrg_ti_gas, EU-27 imports of natural gas by partner, million cubic metres, 2021 and 2024; shares computed over extra-EU partners only (extra-EU totals 347.8 bcm and 277.9 bcm). Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
};

/** Russian share in 2024, per fuel, percent — the post-sanctions residual. */
export const RUSSIAN_SHARE_2024: Record<Fuel, SourcedRange> = {
  gas: {
    value: 13.6,
    lo: 11.6,
    hi: 15.6,
    source: "Eurostat nrg_ti_gas, Russia's share of EU-27 extra-EU natural-gas imports in 2024. Trackers that reallocate LNG trans-shipment report a somewhat higher figure; the difference is a method difference, not an error. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.",
  },
  oil: {
    value: 2.5,
    lo: 1.5,
    hi: 3.5,
    source: "Eurostat nrg_ti_oil, Russia's share of EU-27 extra-EU crude-oil imports in 2024, after the December 2022 crude embargo; the residual is the Druzhba pipeline exemption. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.",
  },
  coal: {
    value: 0.4,
    lo: 0,
    hi: 0.9,
    source: "Eurostat nrg_ti_sff, Russia's share of EU-27 extra-EU hard-coal imports in 2024, under the full embargo in force since August 2022 (Council Reg. (EU) 2022/576). Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.",
  },
};
/* EUROSTAT-MIX-END */

/**
 * 2030 fossil-demand levels per pathway, natural units.
 * WEM/WAM are the EEA with-existing / with-additional-measures projection
 * aggregates. The current EEA indicator update (November 2025) puts them at
 * ≈ −47 % (WEM) and ≈ −54 % (WAM) net GHG vs 1990, against the legislated
 * −55 %. The module previously quoted ≈ −43 % / −49 % from EEA Report
 * 11/2024, which was correct for that edition and is now superseded — the
 * per-fuel levels below were inferred against the OLDER, weaker aggregates
 * and have not been re-inferred, so they understate 2030 progress on both
 * projected pathways. That is the single largest known bias in this file.
 * The advised path is a −55 %-consistent level in the spirit of the
 * Fit-for-55 MIX scenario and the ESABCC 2024 progress-report assessment.
 * CAUTION: EEA publishes GHG aggregates, not per-fuel demand — the per-fuel
 * split below is AI-INFERRED from Commission scenario material and carries
 * the widest ranges in this file.
 */
export const PROJ_2030: {
  levels: Record<PathKey, Record<Fuel, SourcedRange>>;
  source: string;
} = {
  levels: {
    wem: {
      gas: { value: 290, lo: 260, hi: 320, source: 'AI-inferred from EEA WEM aggregate + Commission reference scenarios. 2026-08.' },
      oil: { value: 400, lo: 370, hi: 430, source: 'AI-inferred from EEA WEM aggregate + Commission reference scenarios. 2026-08.' },
      coal: { value: 90, lo: 70, hi: 110, source: 'AI-inferred from EEA WEM aggregate + announced coal phase-out dates. 2026-08.' },
    },
    wam: {
      gas: { value: 250, lo: 220, hi: 280, source: 'AI-inferred from EEA WAM aggregate. 2026-08.' },
      oil: { value: 370, lo: 340, hi: 400, source: 'AI-inferred from EEA WAM aggregate. 2026-08.' },
      coal: { value: 70, lo: 55, hi: 90, source: 'AI-inferred from EEA WAM aggregate + announced coal phase-out dates. 2026-08.' },
    },
    advised: {
      gas: { value: 210, lo: 180, hi: 240, source: 'AI-inferred from the FF55 MIX scenario (≈ −30–37 % gas vs 2015 by 2030) and REPowerEU COM(2022) 230. 2026-08.' },
      oil: { value: 340, lo: 310, hi: 370, source: 'AI-inferred from FF55 MIX transport/oil implications. 2026-08.' },
      coal: { value: 45, lo: 30, hi: 60, source: 'AI-inferred from FF55 MIX power-sector implications. 2026-08.' },
    },
  },
  source:
    'EEA, "Total net greenhouse gas emission trends and projections in Europe", indicator update November 2025: WEM ≈ −47 %, WAM ≈ −54 % net GHG vs 1990 by 2030, against the legislated −55 %. Checked 2026-08-06 and superseding EEA Report 11/2024 (−43 % / −49 %), which is what the per-fuel levels here were inferred against. European Commission FF55 MIX scenario and REPowerEU COM(2022) 230 for the gas split; ESABCC 2024 progress report for the advised-path framing. Per-fuel levels remain AI-inferred order-of-magnitude values pending Secretariat verification, and re-inferring them against the current aggregates is an open work item.',
};

/** Assumed import share of demand in 2030, percent, per fuel. */
export const IMPORT_SHARE_2030: { shares: Record<Fuel, number>; source: string } = {
  shares: { gas: 92, oil: 97, coal: 60 },
  source:
    'Extrapolation of the Eurostat nrg_ind_id trends above (EU gas production keeps declining; oil dependency stable; residual Polish hard-coal production). AI-compiled 2026-08, ± 5 percentage points.',
};

/* EUROSTAT-POP-BEGIN — generated by scripts/refresh-climate-security-eurostat.mjs on 2026-08-06. */
/** EU-27 population, millions, for the €-per-citizen line. */
export const EU_POPULATION_M: { value: number; source: string } = {
  value: 450.1,
  source: 'Eurostat demo_gind, EU-27 average population in 2024, millions. Live pull 2026-08-06 via scripts/refresh-climate-security-eurostat.mjs.',
};
/* EUROSTAT-POP-END */
