// ---------------------------------------------------------------------------
// Code-system + segments snapshots (M·05 user-feedback chunk).
//
// Reviewers asked for a way to take versioned copies of their code system
// and tagged segments — both manual ("save current state before I refactor
// the tree") and automatic ("snapshot every few minutes so I can roll
// back if I accidentally delete a tag").
//
// Snapshots are stored in localStorage under a separate key from the
// main state so the snapshot list is preserved across resets and never
// reaches the server. Each snapshot contains:
//   - codes      : full code system
//   - segments   : every coded segment
//   - capturedAt : ISO timestamp
//   - kind       : 'manual' | 'auto'
//   - label?     : user-supplied (manual) or autogenerated (auto)
//   - note?      : free-form description
//
// Retention:
//   - manual snapshots: capped at MANUAL_LIMIT (50)
//   - auto snapshots:   capped at AUTO_LIMIT   (20) — older ones evicted
// ---------------------------------------------------------------------------

import type { CodeNode, CodedSegment } from './types';

const LS_KEY = 'esabcc_content_analysis_snapshots_v1';
const MANUAL_LIMIT = 50;
const AUTO_LIMIT = 20;

export type SnapshotKind = 'manual' | 'auto';

export interface CodeSystemSnapshot {
  id: string;
  capturedAt: string;
  kind: SnapshotKind;
  label?: string;
  note?: string;
  codes: CodeNode[];
  segments: CodedSegment[];
  /** Lightweight stats so the list UI doesn't have to recount on every render. */
  stats: { codes: number; segments: number };
}

interface SnapshotStore {
  version: 1;
  snapshots: CodeSystemSnapshot[];
}

function readStore(): SnapshotStore {
  if (typeof window === 'undefined') return { version: 1, snapshots: [] };
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return { version: 1, snapshots: [] };
    const parsed = JSON.parse(raw) as SnapshotStore;
    if (parsed?.version === 1 && Array.isArray(parsed.snapshots)) return parsed;
  } catch {
    // corrupt — start fresh
  }
  return { version: 1, snapshots: [] };
}

function writeStore(s: SnapshotStore): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(LS_KEY, JSON.stringify(s));
  } catch {
    // quota exceeded — let the caller decide what to do
  }
}

function newSnapshotId(): string {
  return `snap-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

/** Read every saved snapshot (most-recent-first). */
export function listSnapshots(): CodeSystemSnapshot[] {
  const s = readStore();
  return [...s.snapshots].sort((a, b) => b.capturedAt.localeCompare(a.capturedAt));
}

/** Capture a new snapshot. Caller passes the current codes + segments;
 *  label and note are optional. Auto-snapshots are only kept if they
 *  differ from the most recent snapshot, to avoid filling localStorage
 *  with identical copies during idle periods. */
export function captureSnapshot(input: {
  codes: CodeNode[];
  segments: CodedSegment[];
  kind: SnapshotKind;
  label?: string;
  note?: string;
}): CodeSystemSnapshot | null {
  const s = readStore();
  const last = s.snapshots[s.snapshots.length - 1];
  if (input.kind === 'auto' && last) {
    // Skip if nothing has changed since the last auto snapshot.
    if (
      last.stats.codes === input.codes.length &&
      last.stats.segments === input.segments.length &&
      last.kind === 'auto'
    ) {
      // Cheap structural check: same lengths AND same last-segment id.
      const lastSegId = input.segments[input.segments.length - 1]?.id ?? '';
      const prevLastSegId = last.segments[last.segments.length - 1]?.id ?? '';
      if (lastSegId === prevLastSegId) return null;
    }
  }
  const snap: CodeSystemSnapshot = {
    id: newSnapshotId(),
    capturedAt: new Date().toISOString(),
    kind: input.kind,
    label: input.label,
    note: input.note,
    codes: input.codes,
    segments: input.segments,
    stats: { codes: input.codes.length, segments: input.segments.length },
  };
  s.snapshots.push(snap);
  // Enforce per-kind retention.
  const manual = s.snapshots.filter(x => x.kind === 'manual');
  const auto = s.snapshots.filter(x => x.kind === 'auto');
  while (manual.length > MANUAL_LIMIT) manual.shift();
  while (auto.length > AUTO_LIMIT) auto.shift();
  s.snapshots = [...manual, ...auto].sort((a, b) => a.capturedAt.localeCompare(b.capturedAt));
  writeStore(s);
  return snap;
}

export function deleteSnapshot(id: string): void {
  const s = readStore();
  s.snapshots = s.snapshots.filter(x => x.id !== id);
  writeStore(s);
}

export function getSnapshot(id: string): CodeSystemSnapshot | null {
  const s = readStore();
  return s.snapshots.find(x => x.id === id) ?? null;
}
