/**
 * Overview Industry — Trade flows (data model).
 * ---------------------------------------------
 * An input–output view of EU-27 manufacturing trade: for every NACE Rev. 2
 * Section C division (10–33) it maps
 *   • OUTPUT  → where EU manufacturing sells (intra-EU vs extra-EU, real
 *               destination shares),
 *   • INPUT   → what it must import and from where — at three depths:
 *               (1) the imported-intermediate-input mix straight out of the
 *                   EU-27 input–output use table (which products, € bn, what
 *                   share of all inputs is imported),
 *               (2) origin countries of those imports from the FIGARO
 *                   inter-country input–output framework, and
 *               (3) a curated critical-materials layer (EC/JRC) naming the
 *                   specific feedstocks below the 2-digit radar, and
 *   • RISK    → the hotspots where imports are both large and concentrated in
 *               a single supplier (carbon-leakage / CBAM / CRMA front line).
 *
 * DATA ARCHITECTURE (three layers, see the Methodology view for the full story):
 *
 *   Layer 1 — TRADE BACKBONE (statistical, all 24 divisions)
 *     Eurostat `ext_tec01`, EU-27, 2023 + 2024: extra-/intra-EU imports and
 *     exports by the NACE activity of the trading ENTERPRISE. Fetched live and
 *     regenerated by `scripts/fetch-trade-flows-io-data.mjs` into
 *     `eurostat-io.generated.ts`.
 *
 *   Layer 2 — INPUT–OUTPUT LAYER (statistical, PRODUCT-based, 2023)
 *     • EU-27 use table at basic prices (`naio_10_cp1610`): each industry's
 *       intermediate inputs by product, split domestic vs imported.
 *     • FIGARO application datasets (`naio_10_fgti`, `naio_10_fgte`,
 *       `naio_10_fgfoee`): import origins, export destinations and the foreign
 *       value added embedded in exports, by counterpart country.
 *     Enterprise-based (layer 1) and product-based (layer 2) numbers
 *     deliberately DIFFER — C19 is the textbook case (refiners import crude,
 *     but crude is a MINING product) — and the module explains that instead of
 *     hiding it.
 *
 *   Layer 3 — DEPENDENCY LAYER (curated, "as reported by <source>")
 *     Critical-raw-materials shares (EC/JRC, CRMA), strategic-dependency
 *     reviews (SWD(2021) 352) and named per-sector inputs. These are NOT
 *     derivable from official statistics at this granularity; every figure
 *     carries its source and should be read as that source's assessment.
 *
 * SOURCING RULE (hard): every figure carries a real, working source link.
 * Nothing is invented.
 *
 * Reuses the `Source` / `Sourced` primitives from the Clean Tech catalogue so
 * the two sub-pages share one evidence model.
 */

import type { Source } from '../cleantech-catalogue';
import {
  TEC_BACKBONE,
  FIGARO_IMPORT_ORIGINS,
  FIGARO_EXPORT_DESTINATIONS,
  FIGARO_FVA,
  INDUSTRY_INPUT_MIX,
  INPUT_MIX_TOTAL_C,
  ENERGY_IMPORT_DEPENDENCY,
  type TecFlows,
  type FigaroIndustryFlow,
  type FigaroFva,
  type IndustryInputMix,
} from './eurostat-io.generated';

export type { Source } from '../cleantech-catalogue';
export type {
  TecFlows,
  FigaroIndustryFlow,
  FigaroFva,
  IndustryInputMix,
  FigaroPartner,
  FvaOrigin,
  ImportedInput,
} from './eurostat-io.generated';
export { INPUT_MIX_TOTAL_C, ENERGY_IMPORT_DEPENDENCY } from './eurostat-io.generated';

/* ------------------------------------------------------------- shared sources */

export const EUROSTAT_TEC: Source = {
  org: 'Eurostat',
  title: 'Trade by NACE Rev. 2 activity and enterprise size class (ext_tec01)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/ext_tec01/default/table?lang=en',
  year: '2024',
};

export const EUROSTAT_USE_TABLE: Source = {
  org: 'Eurostat',
  title: 'EU-27 use table at basic prices (naio_10_cp1610)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/naio_10_cp1610/default/table?lang=en',
  year: '2023',
};

export const EUROSTAT_FIGARO_IMPORTS: Source = {
  org: 'Eurostat (FIGARO)',
  title: 'Imports by industry — FIGARO application (naio_10_fgti)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/naio_10_fgti/default/table?lang=en',
  year: '2023',
};

export const EUROSTAT_FIGARO_EXPORTS: Source = {
  org: 'Eurostat (FIGARO)',
  title: 'Exports by industry — FIGARO application (naio_10_fgte)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/naio_10_fgte/default/table?lang=en',
  year: '2023',
};

export const EUROSTAT_FIGARO_FVA: Source = {
  org: 'Eurostat (FIGARO)',
  title: 'Foreign value added in exports by country of origin — FIGARO application (naio_10_fgfoee)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/naio_10_fgfoee/default/table?lang=en',
  year: '2023',
};

export const EUROSTAT_ENERGY_DEP: Source = {
  org: 'Eurostat',
  title: 'Energy imports dependency (nrg_ind_id)',
  url: 'https://ec.europa.eu/eurostat/databrowser/view/nrg_ind_id/default/table?lang=en',
  year: '2024',
};

export const OECD_TIVA_EU: Source = {
  org: 'OECD TiVA (2023 ed., ICIO)',
  title: 'GVC indicators for the European Union (data year 2020)',
  url: 'https://www.oecd.org/content/dam/oecd/en/topics/policy-sub-issues/trade-in-value-added/tiva-2023-EU27_2020.pdf',
  year: '2020',
};

export const CRMA_SOURCE: Source = {
  org: 'European Union',
  title: 'Critical Raw Materials Act — Regulation (EU) 2024/1252',
  url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1252',
  year: '2024',
};

export const SWD_2021_352: Source = {
  org: 'European Commission',
  title: 'SWD(2021) 352 — Strategic dependencies and capacities',
  url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A52021SC0352',
  year: '2021',
};

/* ------------------------------------------------------------ trade branches */

/**
 * Coarse trade grouping for colour-coding the figure. Broader than the Clean
 * Tech emission branches because trade covers all 24 Section C divisions, not
 * only the energy-intensive ones.
 */
export type TradeBranch =
  | 'Metals'
  | 'Non-metallic minerals'
  | 'Chemicals, pharma & refining'
  | 'Electronics & electrical'
  | 'Machinery & transport equipment'
  | 'Consumer & light manufacturing';

export const TRADE_BRANCH_COLORS: Record<TradeBranch, string> = {
  Metals: '#3D5265',
  'Non-metallic minerals': '#B83230',
  'Chemicals, pharma & refining': '#6667AB',
  'Electronics & electrical': '#00928F',
  'Machinery & transport equipment': '#004B7F',
  'Consumer & light manufacturing': '#FF9933',
};

/* ----------------------------------------------------- per-division trade row */

/**
 * 2023 is the REFERENCE YEAR: it is the latest year covered by the whole
 * input–output layer (FIGARO + use table), so all four views line up on it.
 * 2024 backbone data exists and is exposed for the year toggle / deltas.
 */
export const TEC_YEARS = ['2023', '2024'] as const;
export type TecYear = (typeof TEC_YEARS)[number];
export const REFERENCE_YEAR: TecYear = '2023';
export const LATEST_YEAR: TecYear = '2024';

export interface DivisionTrade {
  /** NACE Rev. 2 division code, e.g. 'C24'. */
  code: string;
  /** Short label. */
  label: string;
  branch: TradeBranch;
  /** One-line characterisation of the trade / dependency story. */
  note: string;
  /** Eurostat ext_tec01 flows (€ bn) by year — enterprise-based attribution. */
  flows: Record<TecYear, TecFlows>;
}

interface DivisionMeta {
  code: string;
  label: string;
  branch: TradeBranch;
  note: string;
}

const DIVISION_META: DivisionMeta[] = [
  { code: 'C10', label: 'Food products', branch: 'Consumer & light manufacturing',
    note: 'Large net exporter; imports are agri-commodities (cocoa, coffee, fish, oilseeds) the EU cannot grow.' },
  { code: 'C11', label: 'Beverages', branch: 'Consumer & light manufacturing',
    note: 'Strong surplus — wine & spirits are premium EU exports; little import dependency.' },
  { code: 'C12', label: 'Tobacco products', branch: 'Consumer & light manufacturing',
    note: 'Small, roughly balanced; raw-leaf imports from Brazil, US, Africa.' },
  { code: 'C13', label: 'Textiles', branch: 'Consumer & light manufacturing',
    note: 'Import-exposed on yarn & fabric; China and Turkey dominate extra-EU supply.' },
  { code: 'C14', label: 'Wearing apparel', branch: 'Consumer & light manufacturing',
    note: 'Net importer of finished garments — China, Bangladesh, Turkey; a classic offshored value chain.' },
  { code: 'C15', label: 'Leather & footwear', branch: 'Consumer & light manufacturing',
    note: 'Finished footwear imported from Asia; EU keeps a luxury-goods export edge.' },
  { code: 'C16', label: 'Wood & cork products', branch: 'Consumer & light manufacturing',
    note: 'Mostly intra-EU; net exporter, low extra-EU import reliance.' },
  { code: 'C17', label: 'Paper & paper products', branch: 'Consumer & light manufacturing',
    note: 'Net exporter but dependent on imported market pulp (Brazil, US, Nordics) and recovered fibre.' },
  { code: 'C18', label: 'Printing & recorded media', branch: 'Consumer & light manufacturing',
    note: 'Small, service-like; overwhelmingly intra-EU.' },
  { code: 'C19', label: 'Coke & refined petroleum', branch: 'Chemicals, pharma & refining',
    note: 'Largest single import bill in manufacturing — refiners import crude & fuels; the EU energy-dependency front line.' },
  { code: 'C20', label: 'Chemicals & chemical products', branch: 'Chemicals, pharma & refining',
    note: 'Net exporter of specialty chemicals, but base-chemical feedstock (naphtha, gas, phosphate, potash) is imported.' },
  { code: 'C21', label: 'Pharmaceuticals', branch: 'Chemicals, pharma & refining',
    note: "Manufacturing's biggest surplus — but active ingredients (APIs) and precursors lean heavily on India & China." },
  { code: 'C22', label: 'Rubber & plastics', branch: 'Chemicals, pharma & refining',
    note: 'Net exporter; natural rubber fully imported (SE Asia), plastics resins partly imported.' },
  { code: 'C23', label: 'Non-metallic minerals (cement, glass, ceramics)', branch: 'Non-metallic minerals',
    note: 'Bulky, mostly local; but CBAM-exposed (cement) and reliant on imported magnesia, graphite, borates.' },
  { code: 'C24', label: 'Basic metals', branch: 'Metals',
    note: 'Roughly balanced trade but deeply input-dependent — iron ore, coking coal, ferro-alloys, primary aluminium; CBAM core.' },
  { code: 'C25', label: 'Fabricated metal products', branch: 'Metals',
    note: 'Net exporter; downstream of basic metals, so inherits their input risk.' },
  { code: 'C26', label: 'Computer, electronic & optical', branch: 'Electronics & electrical',
    note: 'Semiconductor & electronics dependency — chips from Taiwan/Korea/China; a strategic-autonomy priority.' },
  { code: 'C27', label: 'Electrical equipment', branch: 'Electronics & electrical',
    note: 'Net exporter, but batteries and rare-earth permanent magnets are China-concentrated inputs.' },
  { code: 'C28', label: 'Machinery & equipment n.e.c.', branch: 'Machinery & transport equipment',
    note: "Europe's export champion — a €165 bn extra-EU surplus in 2023; capital goods to the world." },
  { code: 'C29', label: 'Motor vehicles & parts', branch: 'Machinery & transport equipment',
    note: 'Huge two-way trade; strong surplus, but exposed on batteries, magnets and chips for the EV transition.' },
  { code: 'C30', label: 'Other transport equipment (aero, rail, ships)', branch: 'Machinery & transport equipment',
    note: 'Aerospace-led surplus; titanium and specialty inputs are the dependency.' },
  { code: 'C31', label: 'Furniture', branch: 'Consumer & light manufacturing',
    note: 'Net exporter; modest extra-EU import reliance (China for low-end).' },
  { code: 'C32', label: 'Other manufacturing (medical, instruments, jewellery)', branch: 'Consumer & light manufacturing',
    note: 'Includes medical devices (surplus) and jewellery; mixed dependency.' },
  { code: 'C33', label: 'Repair & installation of machinery', branch: 'Machinery & transport equipment',
    note: 'Service-like; one of the few manufacturing divisions in extra-EU deficit.' },
];

const ZERO_FLOWS: TecFlows = { impExt: 0, expExt: 0, impInt: 0, expInt: 0 };

/**
 * The 24-division backbone. Values come from the generated Eurostat extract
 * (`ext_tec01`, EU-27, € bn) — regenerate with
 * `node scripts/fetch-trade-flows-io-data.mjs`.
 */
export const DIVISION_TRADE: DivisionTrade[] = DIVISION_META.map((m) => ({
  ...m,
  flows: {
    '2023': TEC_BACKBONE[m.code]?.['2023'] ?? ZERO_FLOWS,
    '2024': TEC_BACKBONE[m.code]?.['2024'] ?? ZERO_FLOWS,
  },
}));

/**
 * Official Section C aggregate row of ext_tec01, by year. NOTE: this does NOT
 * equal the sum of the 24 published divisions (2023 extra-EU imports: €975.7 bn
 * aggregate vs €927.1 bn summed) — the aggregate additionally covers trade that
 * cannot be allocated to a specific division (enterprise-register gaps,
 * confidentiality). Both are exposed; the methodology view explains the gap.
 */
export const SECTION_C_TEC: Record<TecYear, TecFlows> = {
  '2023': TEC_BACKBONE['C']['2023'],
  '2024': TEC_BACKBONE['C']['2024'],
};

/** Sum of the 24 published divisions, by year (for the aggregation-gap note). */
export const SECTION_C_DIVISION_SUM: Record<TecYear, TecFlows> = (() => {
  const sum = (year: TecYear): TecFlows => {
    const t = { impExt: 0, expExt: 0, impInt: 0, expInt: 0 };
    for (const d of DIVISION_TRADE) {
      t.impExt += d.flows[year].impExt;
      t.expExt += d.flows[year].expExt;
      t.impInt += d.flows[year].impInt;
      t.expInt += d.flows[year].expInt;
    }
    return {
      impExt: Math.round(t.impExt * 10) / 10,
      expExt: Math.round(t.expExt * 10) / 10,
      impInt: Math.round(t.impInt * 10) / 10,
      expInt: Math.round(t.expInt * 10) / 10,
    };
  };
  return { '2023': sum('2023'), '2024': sum('2024') };
})();

/* --------------------------------------------- FIGARO / use-table resolution */

/**
 * FIGARO application datasets and the EU-27 use table publish some divisions
 * only as groups. Map a division to the industry code each source carries.
 */
const FIGARO_GROUP: Record<string, string> = {
  C10: 'C10-C12', C11: 'C10-C12', C12: 'C10-C12',
  C13: 'C13-C15', C14: 'C13-C15', C15: 'C13-C15',
  C31: 'C31_C32', C32: 'C31_C32',
};
const USE_TABLE_GROUP: Record<string, string> = {
  C10: 'C10-12', C11: 'C10-12', C12: 'C10-12',
  C13: 'C13-15', C14: 'C13-15', C15: 'C13-15',
  C31: 'C31_32', C32: 'C31_32',
};

export const figaroIndustryFor = (code: string): string => FIGARO_GROUP[code] ?? code;
export const useTableIndustryFor = (code: string): string => USE_TABLE_GROUP[code] ?? code;

/** True when the IO layer only covers this division as part of a group. */
export const isGroupedInIO = (code: string): boolean => code in FIGARO_GROUP;

/** Human label for a grouped IO industry, e.g. 'C10-C12 (food, beverages & tobacco)'. */
export const IO_GROUP_LABELS: Record<string, string> = {
  'C10-C12': 'C10–C12 · food, beverages & tobacco',
  'C13-C15': 'C13–C15 · textiles, apparel & leather',
  C31_C32: 'C31–C32 · furniture & other manufacturing',
};

/** Extra-EU import origins of this division's PRODUCTS (FIGARO, 2023). */
export function importOriginsFor(code: string): FigaroIndustryFlow | undefined {
  return FIGARO_IMPORT_ORIGINS.find((f) => f.industry === figaroIndustryFor(code));
}

/** Extra-EU export destinations of this division's PRODUCTS (FIGARO, 2023). */
export function exportDestinationsFor(code: string): FigaroIndustryFlow | undefined {
  return FIGARO_EXPORT_DESTINATIONS.find((f) => f.industry === figaroIndustryFor(code));
}

/** Foreign value added embedded in this division's extra-EU exports (FIGARO, 2023). */
export function fvaFor(code: string): FigaroFva | undefined {
  return FIGARO_FVA.find((f) => f.industry === figaroIndustryFor(code));
}

/** Imported-intermediate-input mix of this division (EU-27 use table, 2023). */
export function inputMixFor(code: string): IndustryInputMix | undefined {
  return INDUSTRY_INPUT_MIX.find((f) => f.industry === useTableIndustryFor(code));
}

/** Section C-wide FIGARO rows (industry code 'C'). */
export const FIGARO_C_IMPORTS = FIGARO_IMPORT_ORIGINS.find((f) => f.industry === 'C');
export const FIGARO_C_EXPORTS = FIGARO_EXPORT_DESTINATIONS.find((f) => f.industry === 'C');
export const FIGARO_C_FVA = FIGARO_FVA.find((f) => f.industry === 'C');

/**
 * Division-specific caveats where the grouped IO figures hide a known skew.
 * These are qualitative pointers, sourced in the curated layer below.
 */
export const IO_GROUP_SKEW_NOTES: Record<string, string> = {
  C14: 'Within C13–C15, finished-apparel imports are far more concentrated in China, Bangladesh, Türkiye and India than the group average.',
  C31: 'Within C31–C32, furniture imports are strongly China-weighted; C32 (medical devices, instruments) leans US/CH.',
};

/* ----------------------------------------------------- critical raw materials */

export interface CriticalMaterial {
  material: string;
  /** Strategic Raw Material under the CRMA (Annex I), vs merely Critical (Annex II). */
  strategic: boolean;
  /** EU import reliance, % (share of demand met by imports); null where not cleanly published. */
  euImportReliance: number | null;
  topSupplier: string;
  /** Dominant supplier's share of EU supply, %; null where obscured in trade codes. */
  supplierShare: number | null;
  usedIn: string;
  note: string;
  src: Source;
}

/**
 * CURATED LAYER — critical & strategic raw materials the EU manufactures with
 * but barely produces. Framing: Critical Raw Materials Act, Reg. (EU)
 * 2024/1252 — 34 critical + 17 strategic raw materials. `euImportReliance`
 * follows the EC criticality methodology: IR = (imports − exports) /
 * (domestic production + imports − exports). `supplierShare` is the EC/JRC
 * "share of EU supply" (sourcing stage) unless the source says otherwise; that
 * differs from customs trade shares, which the source notes cross-check.
 * Read every figure as "as reported by <source>".
 */
export const CRITICAL_MATERIALS: CriticalMaterial[] = [
  { material: 'Heavy rare earths (HREE)', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 100, usedIn: 'Permanent magnets — motors, wind, EVs (C27, C28, C29)', note: 'China 100% of EU supply; no EU separation/magnet capacity at scale', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Light rare earths (LREE)', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 85, usedIn: 'NdFeB magnets, catalysts (C27, C29)', note: 'China ~85% of LREE sourcing; ~98% of EU rare-earth supply overall', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Magnesium (metal)', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 93, usedIn: 'Aluminium alloying, die-casting (C24, C29)', note: 'EC ~93% (Eurostat trade 92%); negligible EU primary output', src: { org: 'European Commission', title: 'COM(2020) 474 — Critical Raw Materials Resilience', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52020DC0474', year: '2020' } },
  { material: 'Borate / boron', strategic: true, euImportReliance: 100, topSupplier: 'Türkiye', supplierShare: 98, usedIn: 'Glass, ceramics, agrochemicals, magnets (C20, C23)', note: 'Türkiye 98–99% of EU supply — the reserve base is Turkish', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Cobalt', strategic: true, euImportReliance: 76, topSupplier: 'DR Congo (mining)', supplierShare: 63, usedIn: 'Batteries, superalloys (C27, C29, C20)', note: 'DRC ~63% of global mine supply; ~60% refined in China', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Natural graphite', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 47, usedIn: 'Li-ion battery anodes, refractories (C27, C29)', note: 'EC ~47% EU supply; China dominant in spherical/processed graphite', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Gallium', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 71, usedIn: 'Semiconductors, LEDs, GaN/RF chips (C26)', note: 'China ~71% of EU imports, ~80–90% of global refined; export-controlled since 2023', src: { org: 'Eurostat', title: 'International trade in critical raw materials', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=International_trade_in_critical_raw_materials', year: '2025' } },
  { material: 'Germanium', strategic: true, euImportReliance: 100, topSupplier: 'China', supplierShare: 45, usedIn: 'Fibre optics, IR optics, semiconductors (C26, C27)', note: 'China ~45% of EU imports, ~80% global; export-controlled since 2023', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Lithium', strategic: true, euImportReliance: 100, topSupplier: 'Chile', supplierShare: 70, usedIn: 'EV / grid batteries (C27, C29)', note: 'Chile ~70% of EU lithium carbonate imports; battery-grade refining in China', src: { org: 'Eurostat', title: 'International trade in critical raw materials', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=International_trade_in_critical_raw_materials', year: '2025' } },
  { material: 'Platinum-group metals', strategic: true, euImportReliance: 100, topSupplier: 'South Africa', supplierShare: 71, usedIn: 'Autocatalysts, electrolysers, glass (C20, C29)', note: 'South Africa 71% of EU platinum; higher for Ir/Rh/Ru', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Tungsten', strategic: true, euImportReliance: null, topSupplier: 'China', supplierShare: 68, usedIn: 'Cutting tools, hard metals, defence (C25, C28)', note: 'China ~68% of EU ferro-tungsten; EU retains some primary/recycled capacity', src: { org: 'Eurostat', title: 'International trade in critical raw materials', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=International_trade_in_critical_raw_materials', year: '2025' } },
  { material: 'Niobium', strategic: false, euImportReliance: 100, topSupplier: 'Brazil', supplierShare: 92, usedIn: 'HSLA-steel micro-alloying, superalloys (C24, C30)', note: 'Brazil ~92% of global supply; no EU production', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Silicon metal', strategic: true, euImportReliance: 63, topSupplier: 'China', supplierShare: 76, usedIn: 'Aluminium alloys, silicones, PV/semis (C20, C24, C26)', note: 'China dominant globally; EU keeps some smelter capacity', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { material: 'Scandium', strategic: false, euImportReliance: 100, topSupplier: 'China', supplierShare: 66, usedIn: 'Al-Sc aerospace alloys, SOFCs (C24, C30)', note: 'China ~66% of EU supply; very thin global market', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
];

/* --------------------------------------------------- energy / feedstock reliance */

export interface EnergyDependency {
  item: string;
  naceRelevance: string;
  /** Import dependency, %; null where no single clean figure exists. */
  dependencyPct: number | null;
  year: string;
  note: string;
  src: Source;
}

const energyPct = (siec: string, year: string): number | null =>
  ENERGY_IMPORT_DEPENDENCY[siec]?.byYear[year] ?? null;

/**
 * Energy & feedstock import dependency — the input side of C19 (refining) and
 * C20 (chemicals). The three headline rows are LIVE Eurostat `nrg_ind_id`
 * values (net imports / gross available energy); the Russia-share row is a
 * curated Commission figure.
 */
export const ENERGY_FEEDSTOCK_DEPENDENCY: EnergyDependency[] = [
  { item: 'Overall net energy-import dependency', naceRelevance: 'All C (esp. C19, C20, C24)', dependencyPct: energyPct('TOTAL', '2024'), year: '2024', note: `Peaked at ${energyPct('TOTAL', '2022') ?? 62.5}% in 2022 (post-invasion shock); ${energyPct('TOTAL', '2023') ?? 58.3}% in 2023`, src: EUROSTAT_ENERGY_DEP },
  { item: 'Oil & petroleum products (excl. biofuels)', naceRelevance: 'C19 (refining)', dependencyPct: energyPct('O4000XBIO', '2024'), year: '2024', note: 'EU domestic crude output is marginal; USA now the top crude supplier post-embargo', src: EUROSTAT_ENERGY_DEP },
  { item: 'Natural gas', naceRelevance: 'C20 (feedstock & process heat)', dependencyPct: energyPct('G3000', '2024'), year: '2024', note: `${energyPct('G3000', '2022') ?? 97.6}% at the 2022 peak; Norway pipeline + US LNG replaced most Russian volumes`, src: EUROSTAT_ENERGY_DEP },
  { item: 'Russian gas share of EU gas imports', naceRelevance: 'C20, C24', dependencyPct: 15, year: '2023', note: 'Fell 45% (2021) → 24% (2022) → ~15% (2023) after the supply shock', src: { org: 'European Commission (DG ENER)', title: 'EU energy security and gas supplies', url: 'https://energy.ec.europa.eu/news/focus-eu-energy-security-and-gas-supplies-2024-02-15_en', year: '2024' } },
];

/* ------------------------------------------------------- strategic dependencies */

export interface StrategicDependency {
  family: string;
  naceDivision: string;
  ecosystem: string;
  euImportReliance: number | null;
  topSupplier: string;
  supplierShare: number | null;
  vulnerability: string;
  src: Source;
}

/**
 * CURATED LAYER — EU strategic dependencies at product/family level. Source:
 * EC SWD(2021) 352, which mapped 137 products in sensitive ecosystems where
 * the EU is highly import-dependent (~6% of extra-EU goods imports); 34 judged
 * "highly vulnerable"; 99 of the 137 sit in the energy-intensive ecosystem.
 */
export const STRATEGIC_DEPENDENCIES: StrategicDependency[] = [
  { family: 'Rare-earth magnets (NdFeB)', naceDivision: 'C27/C29', ecosystem: 'Energy-intensive / raw materials', euImportReliance: 100, topSupplier: 'China', supplierShare: 98, vulnerability: 'Heavy REE 100% from China, magnets ~98%; no EU magnet-making at scale, very low substitutability', src: SWD_2021_352 },
  { family: 'Magnesium (metal)', naceDivision: 'C24', ecosystem: 'Energy-intensive industries', euImportReliance: 100, topSupplier: 'China', supplierShare: 93, vulnerability: 'Near-zero EU primary production; essential aluminium alloying agent; single-country concentration', src: SWD_2021_352 },
  { family: 'Active pharmaceutical ingredients (APIs)', naceDivision: 'C21', ecosystem: 'Health', euImportReliance: null, topSupplier: 'China / India', supplierShare: null, vulnerability: 'High offshore concentration of fine-chemical/API synthesis; flagged sensitive-ecosystem dependency (not per-product quantified in the SWD)', src: SWD_2021_352 },
  { family: 'Semiconductors / integrated circuits', naceDivision: 'C26', ecosystem: 'Digital', euImportReliance: null, topSupplier: 'Taiwan / East Asia', supplierShare: null, vulnerability: 'Advanced-node fabrication concentrated in East Asia; critical digital-transition dependency', src: SWD_2021_352 },
  { family: 'Borates / boron', naceDivision: 'C20/C23', ecosystem: 'Energy-intensive industries', euImportReliance: 100, topSupplier: 'Türkiye', supplierShare: 98, vulnerability: 'Turkey holds dominant global reserves; almost no EU alternative; glass, ceramics, agrochemicals', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { family: 'Platinum-group metals', naceDivision: 'C20/C29', ecosystem: 'Energy-intensive / mobility', euImportReliance: 100, topSupplier: 'South Africa', supplierShare: 71, vulnerability: 'South Africa 71% of EU platinum (more for Ir/Rh/Ru); catalysts, autocatalysts, electrolysers; no EU mining', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
];

/* -------------------------------------------------------------- risk quadrant */

export interface RiskHotspot {
  label: string;
  naceDivision: string;
  /** 0–1: share of EU demand met by imports (EC criticality-methodology IR where available). */
  importReliance: number;
  /** 0–1: single largest supplier's share (concentration proxy; see methodology). */
  supplierConcentration: number;
  supplier: string;
  src: Source;
}

/**
 * CURATED LAYER — the high-risk matrix that drives the risk-quadrant chart.
 * Two 0–1 axes: import reliance × supplier concentration. The top-right corner
 * (high on both) is where a single foreign supplier can choke an EU value
 * chain — derived from the critical-materials, strategic-dependency and energy
 * datasets above. Axis definitions and caveats: see the Methodology view.
 */
export const RISK_HOTSPOTS: RiskHotspot[] = [
  { label: 'Rare-earth magnets (NdFeB)', naceDivision: 'C27/C29', importReliance: 1.0, supplierConcentration: 1.0, supplier: 'China', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Magnesium metal', naceDivision: 'C24', importReliance: 1.0, supplierConcentration: 0.93, supplier: 'China', src: { org: 'European Commission', title: 'COM(2020) 474 — Critical Raw Materials Resilience', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52020DC0474', year: '2020' } },
  { label: 'Borate / boron', naceDivision: 'C20/C23', importReliance: 1.0, supplierConcentration: 0.98, supplier: 'Türkiye', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Niobium (steel micro-alloy)', naceDivision: 'C24', importReliance: 1.0, supplierConcentration: 0.92, supplier: 'Brazil', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Silicon metal', naceDivision: 'C20/C24/C26', importReliance: 0.63, supplierConcentration: 0.76, supplier: 'China', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Gallium (chip feedstock)', naceDivision: 'C26', importReliance: 1.0, supplierConcentration: 0.71, supplier: 'China', src: { org: 'Eurostat', title: 'International trade in critical raw materials', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=International_trade_in_critical_raw_materials', year: '2025' } },
  { label: 'Platinum-group metals', naceDivision: 'C20/C29', importReliance: 1.0, supplierConcentration: 0.71, supplier: 'South Africa', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Lithium (battery)', naceDivision: 'C27/C29', importReliance: 1.0, supplierConcentration: 0.70, supplier: 'Chile', src: { org: 'Eurostat', title: 'International trade in critical raw materials', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=International_trade_in_critical_raw_materials', year: '2025' } },
  { label: 'Cobalt (batteries)', naceDivision: 'C27/C29', importReliance: 0.76, supplierConcentration: 0.63, supplier: 'DR Congo (mine)', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Natural graphite (anodes)', naceDivision: 'C27/C29', importReliance: 1.0, supplierConcentration: 0.47, supplier: 'China', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Germanium', naceDivision: 'C26/C27', importReliance: 1.0, supplierConcentration: 0.45, supplier: 'China', src: { org: 'European Commission (DG GROW)', title: 'Critical raw materials', url: 'https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en', year: '2023' } },
  { label: 'Semiconductors (advanced logic)', naceDivision: 'C26', importReliance: 0.90, supplierConcentration: 0.60, supplier: 'Taiwan', src: { org: 'European Commission', title: 'SWD(2021) 352 — Strategic dependencies', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A52021SC0352', year: '2021' } },
  { label: 'Titanium metal (aerospace)', naceDivision: 'C30/C25', importReliance: 1.0, supplierConcentration: 0.50, supplier: 'China / mixed', src: CRMA_SOURCE },
  { label: 'Crude oil / refined feedstock', naceDivision: 'C19', importReliance: 0.97, supplierConcentration: 0.16, supplier: 'USA (crude/products)', src: { org: 'Eurostat', title: 'Energy production and imports', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_production_and_imports', year: '2024' } },
  { label: 'Natural gas (chemicals feedstock)', naceDivision: 'C20', importReliance: 0.90, supplierConcentration: 0.30, supplier: 'Norway', src: { org: 'Eurostat', title: 'Energy production and imports', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_production_and_imports', year: '2024' } },
];

/* --------------------------------------- curated critical imported inputs */

export interface SectorInput {
  name: string;
  suppliers: string;
  src: Source;
}
export interface SectorInputs {
  code: string;
  label: string;
  inputs: SectorInput[];
}

const IO_S = {
  crm2023: { org: 'European Commission (RMIS)', title: 'Study on the Critical Raw Materials for the EU 2023', url: 'https://rmis.jrc.ec.europa.eu/analysis/criticality/crm_list', year: '2023' } as Source,
  eurostatEnergy: { org: 'Eurostat (Statistics Explained)', title: 'EU imports of energy products — latest developments', url: 'https://ec.europa.eu/eurostat/statistics-explained/index.php?title=EU_imports_of_energy_products_-_latest_developments', year: '2024' } as Source,
  eurlexFert: { org: 'European Commission', title: 'Ensuring availability and affordability of fertilisers (COM/2022/590)', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:52022DC0590(01)', year: '2022' } as Source,
  cokingJRC: { org: 'JRC (RMIS)', title: 'Coking coal — supply-security briefing', url: 'https://rmis.jrc.ec.europa.eu/uploads/2200629_JRC129975_briefing_coking_coal.pdf', year: '2022' } as Source,
  scrreenAlu: { org: 'SCRREEN / EC', title: 'Aluminium and Bauxite CRM factsheet', url: 'https://scrreen.eu/wp-content/uploads/2023/01/ALUMINIUM-AND-BAUXITE_CRM_2020_Factsheets_critical_Final.pdf', year: '2020' } as Source,
  ironExports: { org: "World's Top Exports", title: 'Iron-ore exports by country', url: 'https://www.worldstopexports.com/iron-ore-exports-country/', year: '2024' } as Source,
  cepi: { org: 'CEPI', title: 'Key Statistics 2023 — European pulp & paper industry', url: 'https://www.cepi.org/wp-content/uploads/2024/09/Key-Statistics-2023-FINAL-2.pdf', year: '2023' } as Source,
  acea: { org: 'ACEA', title: 'EU battery supply chain and import reliance', url: 'https://www.acea.auto/files/ACEA_Fact_sheet-EU_battery_supply_chain_and_import_reliance.pdf', year: '2024' } as Source,
  iai: { org: 'Istituto Affari Internazionali (IAI)', title: 'Beyond the European Chips Act — EU supply-chain dependencies', url: 'https://www.iai.it/en/publications/c41/beyond-european-chips-act-eu-supply-chain-dependencies-china-taiwan-and-united', year: '2023' } as Source,
  ieaMagnets: { org: 'IEA', title: "China's share in rare-earth magnet production, 2024", url: 'https://www.iea.org/data-and-statistics/charts/china-s-share-in-rare-earth-magnet-production-2024', year: '2024' } as Source,
  dgAgri: { org: 'European Commission (DG AGRI)', title: 'Agri-food trade statistical factsheet — extra-EU', url: 'https://agriculture.ec.europa.eu/data-and-analysis/markets/trade/trade-statistics_en', year: '2024' } as Source,
};

/**
 * CURATED LAYER — named critical imported inputs by sector: the granular,
 * below-2-digit story the use table cannot see (the use table knows C24 buys
 * €36 bn of imported mining products; this layer names the ores and who ships
 * them). Supplier shares are "as reported by" each source.
 */
export const SECTOR_IO_INPUTS: SectorInputs[] = [
  { code: 'C24', label: 'Basic metals', inputs: [
    { name: 'Iron ore', suppliers: 'Brazil, Canada, South Africa, Ukraine (EU mines almost none)', src: IO_S.ironExports },
    { name: 'Coking / metallurgical coal', suppliers: 'Australia, USA, Canada, Mozambique, Colombia (Russia halted since Aug 2022)', src: IO_S.cokingJRC },
    { name: 'Ferro-alloys / manganese ore', suppliers: 'South Africa, Gabon', src: IO_S.crm2023 },
    { name: 'Nickel', suppliers: 'Indonesia, Russia, Philippines, Canada', src: IO_S.crm2023 },
    { name: 'Primary aluminium', suppliers: 'Russia (~33%), Mozambique (~17%), Iceland (~14%)', src: IO_S.scrreenAlu },
    { name: 'Bauxite / alumina', suppliers: 'Guinea (~70%), Brazil (~14%), Sierra Leone (~10%)', src: IO_S.scrreenAlu },
  ] },
  { code: 'C20', label: 'Chemicals', inputs: [
    { name: 'Natural gas (ammonia feedstock & energy)', suppliers: 'Norway (pipeline), US LNG, Algeria', src: IO_S.eurostatEnergy },
    { name: 'Naphtha / crude-derived feedstock', suppliers: 'Derived from imported crude oil (see C19)', src: IO_S.eurostatEnergy },
    { name: 'Phosphate rock', suppliers: 'Morocco (~28%), Russia (~23%); EU imports ~68% of phosphate nutrient', src: IO_S.eurlexFert },
    { name: 'Potash', suppliers: 'Russia + Belarus (~64% combined), Canada; EU imports ~85% of potash nutrient', src: IO_S.eurlexFert },
  ] },
  { code: 'C19', label: 'Coke & refined petroleum', inputs: [
    { name: 'Crude oil', suppliers: 'USA (~18%), Norway (~14–16%), Kazakhstan (~9%), Saudi Arabia, Libya, Nigeria, Iraq (Russia embargoed Dec 2022)', src: IO_S.eurostatEnergy },
  ] },
  { code: 'C23', label: 'Other non-metallic minerals', inputs: [
    { name: 'Natural graphite', suppliers: 'China (dominant supplier of EU imports)', src: IO_S.crm2023 },
    { name: 'Magnesite / magnesia (refractories)', suppliers: 'China (~90%+ of supply)', src: IO_S.crm2023 },
    { name: 'Borates', suppliers: 'Türkiye (~98%)', src: IO_S.crm2023 },
    { name: 'Feldspar', suppliers: 'Türkiye (leading supplier)', src: IO_S.crm2023 },
  ] },
  { code: 'C26', label: 'Computer, electronic & optical', inputs: [
    { name: 'Semiconductors / chips', suppliers: 'Taiwan (>60% of market; TSMC >90% of high-end), South Korea, China, Malaysia (assembly/test)', src: IO_S.iai },
    { name: 'Rare-earth elements', suppliers: 'China (~70% of EU imports; ~100% of heavy REEs)', src: IO_S.crm2023 },
    { name: 'Silicon metal', suppliers: 'China (leading global producer)', src: IO_S.crm2023 },
  ] },
  { code: 'C27', label: 'Electrical equipment', inputs: [
    { name: 'Permanent magnets / rare earths (NdFeB)', suppliers: 'China (~94% of magnet production)', src: IO_S.ieaMagnets },
    { name: 'Semiconductors', suppliers: 'Taiwan, South Korea', src: IO_S.iai },
    { name: 'Copper (wiring / windings)', suppliers: 'Chile, Peru (concentrate); refined imports', src: IO_S.crm2023 },
  ] },
  { code: 'C29', label: 'Motor vehicles', inputs: [
    { name: 'Li-ion battery cells & materials', suppliers: 'China (>85% of EU battery imports, 2024), South Korea', src: IO_S.acea },
    { name: 'Permanent magnets / rare earths (traction motors)', suppliers: 'China (~94% of magnets)', src: IO_S.ieaMagnets },
    { name: 'Automotive semiconductors', suppliers: 'Taiwan, plus EU/US designers', src: IO_S.iai },
  ] },
  { code: 'C28', label: 'Machinery & equipment n.e.c.', inputs: [
    { name: 'Semiconductors / electronic controls', suppliers: 'Taiwan, South Korea', src: IO_S.iai },
    { name: 'Rare-earth magnets (motors)', suppliers: 'China', src: IO_S.ieaMagnets },
    { name: 'Basic & fabricated metals', suppliers: 'Partly imported via C24 upstream', src: IO_S.scrreenAlu },
  ] },
  { code: 'C17', label: 'Paper & paper products', inputs: [
    { name: 'Wood / pulp fibre', suppliers: '~94% EU-grown; imported market pulp mainly Brazil, USA, Canada', src: IO_S.cepi },
    { name: 'Recovered paper', suppliers: '~96% sourced within the EU', src: IO_S.cepi },
  ] },
  { code: 'C10', label: 'Food products', inputs: [
    { name: 'Oilseeds / protein feed (soy)', suppliers: 'Brazil, USA, Argentina', src: IO_S.dgAgri },
    { name: 'Tropical commodities (palm oil, coffee, cocoa)', suppliers: 'Indonesia/Malaysia (palm), West Africa & Latin America (cocoa, coffee)', src: IO_S.dgAgri },
  ] },
];

/* -------------------------------------------------------------- headline facts */

export interface HeadlineFact {
  label: string;
  value: string;
  detail: string;
  src: Source;
}

const c23 = SECTION_C_TEC['2023'];
const c24 = SECTION_C_TEC['2024'];
const surplus23 = Math.round(c23.expExt - c23.impExt);
const surplus24 = Math.round(c24.expExt - c24.impExt);

/** Headline, evidenced facts for the summary strip — all computed from the live extracts. */
export const HEADLINE_FACTS: HeadlineFact[] = [
  {
    label: 'Extra-EU manufacturing trade surplus',
    value: `+€${surplus23} bn`,
    detail: `NACE C exported €${Math.round(c23.expExt)} bn and imported €${Math.round(c23.impExt)} bn outside the EU in 2023 (+€${surplus24} bn in 2024 as the energy import bill fell) — a large surplus that masks acute input dependencies.`,
    src: EUROSTAT_TEC,
  },
  {
    label: 'Foreign value added in exports',
    value: `${FIGARO_C_FVA?.fvaPct ?? 22.4}%`,
    detail: `Of every €100 of extra-EU manufacturing exports, ~€${Math.round(FIGARO_C_FVA?.fvaPct ?? 22)} is value added created abroad and embedded via imported inputs (FIGARO input–output framework, 2023, EU-27 as one economy).`,
    src: EUROSTAT_FIGARO_FVA,
  },
  {
    label: 'Imported intermediate inputs',
    value: `${INPUT_MIX_TOTAL_C.importedShare}%`,
    detail: `EU-27 manufacturing consumed €${(INPUT_MIX_TOTAL_C.totalBn / 1000).toFixed(1)} tn of intermediate inputs in 2023; €${Math.round(INPUT_MIX_TOTAL_C.importedBn)} bn of it imported (use table at basic prices).`,
    src: EUROSTAT_USE_TABLE,
  },
  {
    label: "China's share of extra-EU imports",
    value: `${FIGARO_C_IMPORTS?.partners.find((p) => p.code === 'CN')?.pctOfExtra ?? 24}%`,
    detail: 'Largest single origin of extra-EU imports of manufactured products (FIGARO, 2023) — and far more concentrated in specific inputs: magnets, batteries, gallium, graphite.',
    src: EUROSTAT_FIGARO_IMPORTS,
  },
];
