/**
 * EU Policy Hierarchy — mandate & status annotation layers (WP-1 / WP-2).
 *
 * GENERATED: compiled by Sonnet agents (orchestrated via a Fable workflow,
 * July 2026). MANDATE assigns every instrument to one of the Board-mandate
 * rings (core / adjacent / context) with a one-line "why the Board cares"
 * hook; STATUS marks instruments the 2025-26 legislative agenda is moving
 * (proposals, revisions, omnibus reopenings, announced reviews).
 * Both layers are AI-drafted working annotations pending Secretariat review.
 */
import type { InstrumentStatus, MandateRelevance } from './data';

export const MANDATE: Record<string, { relevance: MandateRelevance; hook: string }> = {
  // ── primary-law
  "primary-law-teu": { relevance: "context", hook: "Founding treaty allocating EU-versus-member-state competences that determines how far binding EU climate action can reach." },
  "primary-law-tfeu": { relevance: "adjacent", hook: "Contains the Article 191/194 legal bases for EU environment, climate and energy legislation the Board evaluates." },
  "primary-law-charter": { relevance: "context", hook: "Fundamental-rights framework increasingly invoked in climate litigation testing the legality of EU and national climate measures." },
  "primary-law-euratom": { relevance: "adjacent", hook: "Governs nuclear safety and investment rules shaping the low-carbon electricity mix underlying climate-neutrality power pathways." },
  "primary-law-protocol-2-subsidiarity": { relevance: "context", hook: "Subsidiarity/proportionality test that can be invoked to block or narrow proposed EU climate and energy legislation." },
  "primary-law-protocol-1-national-parliaments": { relevance: "context", hook: "Gives national parliaments an early-warning window that can delay or force revision of EU climate proposals." },
  "primary-law-charter-explanations": { relevance: "context", hook: "Interpretive guidance for Charter rights that courts apply when adjudicating climate-related litigation against EU measures." },
  "primary-law-treaty-lisbon": { relevance: "adjacent", hook: "Amending treaty that created the TFEU energy title and made combating climate change an explicit EU objective." },
  "primary-law-iia-better-law-making-2016": { relevance: "context", hook: "Sets evaluation and fitness-check procedures now invoked to justify omnibus simplification of green and climate law." },
  "primary-law-comitology-regulation": { relevance: "context", hook: "Committee procedures governing how strict ETS, CBAM and RED implementing and delegated acts ultimately turn out." },
  "primary-law-better-regulation-communication": { relevance: "context", hook: "Methodological basis for the Commission's 2025 omnibus packages simplifying and reopening CBAM, CSRD and taxonomy rules." },
  "primary-law-better-regulation-guidelines": { relevance: "context", hook: "Impact-assessment methodology staff apply when Commission proposes to amend, simplify or repeal climate and energy law." },
  "primary-law-better-regulation-toolbox": { relevance: "context", hook: "Operational checklists implementing those guidelines when drafting amendments or simplification packages touching climate and energy files." },
  "primary-law-iia-transparency-register": { relevance: "context", hook: "Lobbying-disclosure register that exposes industry influence on ETS, CBAM and green-deal simplification negotiations." },
  "primary-law-framework-agreement-ep-commission": { relevance: "context", hook: "Legislative-planning and information-rights framework shaping Parliament's oversight of Commission climate and energy proposals." },
  // ── climate-energy
  "climate-energy-climate-law": { relevance: "core", hook: "Enshrines the binding 2050 climate-neutrality and 2030 -55% targets that anchor the Board's entire assessment mandate." },
  "climate-energy-ets-directive": { relevance: "core", hook: "Core carbon-pricing instrument covering power, industry and aviation whose cap trajectory the Board tracks against targets." },
  "climate-energy-msr": { relevance: "core", hook: "Manages ETS allowance surplus, directly setting the carbon-price signal that drives decarbonisation investment." },
  "climate-energy-ets2": { relevance: "core", hook: "Extends carbon pricing to buildings and road transport, the two largest under-priced non-ETS emission sources." },
  "climate-energy-effort-sharing-lulucf": { relevance: "core", hook: "Sets binding non-ETS national targets and land-sector removals accounting central to the EU's net GHG balance." },
  "climate-energy-cbam": { relevance: "core", hook: "Prevents carbon leakage as free ETS allowances phase out, safeguarding the integrity of EU emissions cuts." },
  "climate-energy-red3": { relevance: "core", hook: "Sets the binding 42.5% renewables target underpinning power-sector and industrial decarbonisation pathways to 2030." },
  "climate-energy-energy-efficiency-package": { relevance: "core", hook: "Sets binding energy-savings and near-zero-energy building standards that cut demand-side emissions across the EU." },
  "climate-energy-governance": { relevance: "core", hook: "Requires National Energy and Climate Plans that form the Board's primary evidence base for progress assessment." },
  "climate-energy-methane": { relevance: "core", hook: "Mandates MRV and abatement of methane across fossil fuel supply chains, a high-impact near-term mitigation lever." },
  "climate-energy-scf": { relevance: "adjacent", hook: "Cushions ETS2 carbon-cost impacts on vulnerable households, determining the carbon-pricing mechanism's political durability, not mitigation itself." },
  "climate-energy-electricity-market": { relevance: "core", hook: "Sets market rules for integrating variable renewables and cross-border flexibility essential to a decarbonised power system." },
  "climate-energy-hydrogen-gas-package": { relevance: "core", hook: "Recasts gas-market rules to build hydrogen infrastructure and phase down fossil-gas dependency central to decarbonisation." },
  "climate-energy-green-deal": { relevance: "core", hook: "Launches the overarching climate-neutrality strategy framing all subsequent EU climate and energy legislation." },
  "climate-energy-fit-for-55": { relevance: "core", hook: "Presents the legislative package delivering the 2030 -55% target, the architecture the Board evaluates instrument-by-instrument." },
  "climate-energy-2040-target": { relevance: "core", hook: "Proposes the 90% 2040 target that will set the Board's next benchmark for trajectory-coherence assessment." },
  "climate-energy-repowereu": { relevance: "core", hook: "Accelerated renewables and efficiency deployment to cut fossil fuel use, reshaping the EU's decarbonisation pace and ambition." },
  "climate-energy-paris-decision": { relevance: "core", hook: "Legally binds the EU to the Paris Agreement, the international commitment underpinning every EU climate target." },
  "climate-energy-cbam-implementing-reg": { relevance: "core", hook: "Sets transitional reporting rules underpinning CBAM's carbon-leakage prevention before definitive-phase charges begin in 2026." },
  "climate-energy-red-rfnbo-delegated-act": { relevance: "core", hook: "Defines when hydrogen counts as renewable, gating industrial and transport decarbonisation credited toward RED III targets." },
  "climate-energy-2030-target-plan-ia": { relevance: "core", hook: "Underlying evidence base for the 55% 2030 target the Board must track member-state progress against." },
  "climate-energy-2040-target-ia": { relevance: "core", hook: "Analytical basis for the proposed 90% 2040 target that will frame the Board's next assessment cycle." },
  // ── environment
  "environment-birds-directive": { relevance: "adjacent", hook: "Species-protection rules affect permitting speed and siting of wind farms and grid infrastructure for the transition." },
  "environment-habitats-directive": { relevance: "adjacent", hook: "Natura 2000 protections shape renewable and grid permitting and safeguard carbon-rich forest and wetland ecosystems." },
  "environment-nature-restoration-regulation": { relevance: "adjacent", hook: "Peatland and wetland restoration targets directly increase carbon-sink capacity credited under the LULUCF Regulation." },
  "environment-water-framework-directive": { relevance: "adjacent", hook: "River-basin management addresses drought and flood adaptation, and ecological-flow rules constrain hydropower permitting." },
  "environment-urban-wastewater-directive": { relevance: "adjacent", hook: "Pushes treatment plants toward energy neutrality, cutting a significant source of methane and power-sector emissions." },
  "environment-air-quality-directive": { relevance: "adjacent", hook: "Tighter air-pollution limits drive faster fossil-fuel combustion phase-down, reinforcing decarbonisation of transport, power and industry." },
  "environment-industrial-emissions-directive": { relevance: "adjacent", hook: "Permitting conditions include energy-efficiency BAT requirements that shape abatement costs for ETS-covered industrial installations." },
  "environment-industrial-emissions-directive-revision": { relevance: "adjacent", hook: "Brings large livestock farms, a major methane source, and battery-manufacturing facilities under permitting for the first time." },
  "environment-reach-regulation": { relevance: "context", hook: "Chemicals-compliance burden sits in the same deregulation debate now also driving omnibus simplification of CBAM and CSRD." },
  "environment-waste-framework-directive": { relevance: "adjacent", hook: "Waste-hierarchy and recycling targets cut landfill methane and the embodied emissions of virgin material production." },
  "environment-packaging-waste-regulation": { relevance: "adjacent", hook: "Packaging reduction and recyclability targets lower embodied-carbon material demand across EU packaging supply chains." },
  "environment-ecodesign-espr-regulation": { relevance: "adjacent", hook: "Sets product carbon-footprint and durability requirements cutting embodied and use-phase emissions across nearly all EU products." },
  "environment-batteries-regulation": { relevance: "adjacent", hook: "Sets carbon-footprint and recycled-content rules for batteries, a critical enabler of EV and storage decarbonisation." },
  "environment-deforestation-regulation": { relevance: "adjacent", hook: "Cuts EU-driven imported deforestation, a major global source of land-use GHG emissions and lost carbon-sink capacity." },
  "environment-eia-directive": { relevance: "adjacent", hook: "Impact-assessment requirements are a key permitting-speed bottleneck for wind, solar and grid infrastructure rollout." },
  "environment-sea-directive": { relevance: "adjacent", hook: "Requires assessment of energy and spatial plans, including renewable-deployment and grid plans, affecting adoption speed." },
  "environment-environmental-liability-directive": { relevance: "context", hook: "General polluter-liability regime not extended to GHG emissions, unlike proposed climate-harm corporate due-diligence liability." },
  "environment-8eap-decision": { relevance: "adjacent", hook: "Monitoring framework tracks EU progress toward climate neutrality alongside biodiversity and pollution-reduction priorities through 2030." },
  "environment-circular-economy-action-plan": { relevance: "adjacent", hook: "Circular-economy strategy cuts resource-intensive industrial emissions by reducing virgin material extraction and waste." },
  "environment-zero-pollution-action-plan": { relevance: "adjacent", hook: "Air-pollution reduction targets share combustion sources with GHG emissions, reinforcing decarbonisation co-benefits across sectors." },
  "environment-biodiversity-strategy-2030": { relevance: "adjacent", hook: "30%-protection targets safeguard forest, peatland and wetland carbon sinks central to LULUCF removals and adaptation resilience." },
  "environment-nature-restoration-impact-assessment": { relevance: "adjacent", hook: "Assesses the carbon-sink and adaptation benefits used to justify binding EU ecosystem-restoration targets." },
  // ── trade
  "trade-anti-dumping": { relevance: "adjacent", hook: "Duties on underpriced imports, such as solar panels and EVs, can raise costs and slow clean-tech deployment." },
  "trade-anti-subsidy": { relevance: "adjacent", hook: "Countervailing duties, as imposed on Chinese EVs, directly affect the price and uptake of imported low-carbon technology." },
  "trade-enforcement": { relevance: "context", hook: "A generic WTO-enforcement tool whose suspended concessions could target climate-related trade disputes, shaping legal feasibility, not climate substance." },
  "trade-fdi-screening": { relevance: "adjacent", hook: "Screening covers energy and raw-materials infrastructure investment, shaping foreign capital access to Europe's grid and clean-tech supply chains." },
  "trade-foreign-subsidies": { relevance: "adjacent", hook: "Already used to investigate Chinese wind-turbine and solar bids, directly affecting EU renewable procurement and manufacturing competition." },
  "trade-ipi": { relevance: "context", hook: "A generic procurement-reciprocity tool whose scope can include renewable-energy tenders, but carries no dedicated climate provisions." },
  "trade-aci": { relevance: "context", hook: "Enables EU countermeasures against economic coercion, including retaliation targeting climate measures like CBAM, shaping room to defend them." },
  "trade-gsp": { relevance: "adjacent", hook: "GSP+ tariff preferences are conditioned on partner countries ratifying core environmental and climate conventions." },
  "trade-dual-use": { relevance: "context", hook: "Controls dual-use exports; no climate provisions, but forms part of the technology-security backdrop shaping industrial and energy strategy." },
  "trade-conflict-minerals": { relevance: "context", hook: "Due-diligence rules cover tin, tantalum, tungsten and gold electronics minerals, not the battery and magnet metals critical to clean tech." },
  "trade-forced-labour": { relevance: "adjacent", hook: "Enforcement targets forced-labour-tainted polysilicon supply chains, directly affecting EU solar-panel import volumes and costs." },
  "trade-ceta": { relevance: "adjacent", hook: "CETA's sustainable-development chapter and Canada's role as a critical-raw-materials partner tie the deal to clean-tech supply chains." },
  "trade-eu-uk-tca": { relevance: "adjacent", hook: "Includes energy-market cooperation and a carbon-pricing level-playing-field clause directly tied to UK-EU climate policy alignment." },
  "trade-wto": { relevance: "context", hook: "Founding EU WTO membership; its GATT rules frame the legal space in which climate-trade tools like CBAM must operate." },
  "trade-policy-review": { relevance: "adjacent", hook: "Names sustainability, including climate and Paris-alignment conditionality, as a pillar shaping the EU's future trade agreements." },
  "trade-global-gateway": { relevance: "adjacent", hook: "Funds overseas renewable-energy, grid and critical-raw-material infrastructure underpinning the EU's import routes for the clean-energy transition." },
  "trade-economic-security": { relevance: "adjacent", hook: "Identifies clean-tech and critical-raw-material import dependencies as strategic vulnerabilities, shaping de-risking policy central to the transition." },
  "trade-fdi-screening-impl": { relevance: "context", hook: "Purely procedural notification forms for FDI-screening cooperation; no independent climate content beyond the parent regulation's scope." },
  "trade-foreign-subsidies-impl": { relevance: "context", hook: "Sets investigation procedure only; the climate-relevant substance sits in the parent Foreign Subsidies Regulation, not here." },
  "trade-foreign-subsidies-ia": { relevance: "context", hook: "Analyses general market-distortion policy options behind the FSR, predating the wind-turbine and solar cases that later made it climate-relevant." },
  // ── competitiveness
  "competitiveness-chips-act": { relevance: "adjacent", hook: "Chip fabs are highly energy-intensive, and semiconductors are essential inputs for EVs, smart grids and renewable-power electronics." },
  "competitiveness-nzia": { relevance: "adjacent", hook: "Sets manufacturing targets and streamlined permitting for solar, wind, batteries, heat pumps and electrolysers scaling the net-zero transition." },
  "competitiveness-nzia-impact-assessment": { relevance: "adjacent", hook: "Assesses costs and options behind NZIA's targets for scaling EU manufacturing of solar, wind, battery and electrolyser technology." },
  "competitiveness-crma": { relevance: "adjacent", hook: "Sets targets to secure critical raw materials, such as lithium and rare earths, essential to batteries, wind turbines and grids." },
  "competitiveness-crma-impact-assessment": { relevance: "adjacent", hook: "Assesses the policy options behind securing lithium, cobalt and rare-earth supply chains that clean-tech manufacturing depends on." },
  "competitiveness-imera": { relevance: "context", hook: "A generic emergency toolbox that could be invoked for critical-raw-material or energy supply shocks, but has no dedicated climate provisions." },
  "competitiveness-late-payment-directive": { relevance: "context", hook: "Speeds payment to SMEs, including clean-tech suppliers, but carries no substantive climate provisions of its own." },
  "competitiveness-services-directive": { relevance: "context", hook: "Removes barriers to cross-border services, including renewable-installation and energy-efficiency services, without dedicated climate provisions." },
  "competitiveness-transparency-directive": { relevance: "context", hook: "Requires notifying draft technical rules, including national energy-efficiency or building standards, before adoption — a procedural check only." },
  "competitiveness-reg-1-2003": { relevance: "context", hook: "General cartel-enforcement law; sets the antitrust backdrop within which green-tech joint ventures and consortia must operate." },
  "competitiveness-merger-regulation": { relevance: "context", hook: "Requires clearance of mergers above turnover thresholds, including consolidation among renewable-energy and grid companies, with no climate-specific test." },
  "competitiveness-merger-implementing-regulation": { relevance: "context", hook: "Sets merger-notification procedure and forms; purely administrative, with no climate content of its own." },
  "competitiveness-gber": { relevance: "adjacent", hook: "Contains a dedicated climate-and-energy state-aid chapter letting states subsidise renewables and efficiency without prior Commission clearance." },
  "competitiveness-ceeag": { relevance: "core", hook: "Sets the framework governing how much states can subsidise renewables, efficiency and industrial decarbonisation, central to funding the transition." },
  "competitiveness-horizon-europe": { relevance: "adjacent", hook: "Its Climate, Energy and Mobility cluster funds the research underpinning clean-tech scale-up, alongside many non-climate research areas." },
  "competitiveness-investeu": { relevance: "adjacent", hook: "Its Sustainable Infrastructure window guarantees private investment mobilised for renewable-energy and clean-tech projects." },
  "competitiveness-step": { relevance: "adjacent", hook: "One of STEP's three funding pillars targets clean-tech manufacturing, alongside digital and biotech, to keep production in Europe." },
  "competitiveness-industrial-strategy-2020": { relevance: "adjacent", hook: "Frames the twin green-and-digital transformation of EU industry, setting direction for later climate-industrial measures like NZIA." },
  "competitiveness-green-deal-industrial-plan": { relevance: "adjacent", hook: "Blueprint for permitting, funding and skills to scale net-zero manufacturing — the strategy that produced the Net-Zero Industry Act." },
  "competitiveness-competitiveness-compass": { relevance: "adjacent", hook: "Names decarbonisation as one of three pillars for closing the EU's competitiveness gap, tying energy costs to climate policy." },
  "competitiveness-clean-industrial-deal": { relevance: "adjacent", hook: "Ties EU industrial competitiveness directly to energy costs and decarbonisation investment, shaping the pace of industrial electrification." },
  "competitiveness-draghi-report": { relevance: "adjacent", hook: "Analyses the EU's energy-cost gap versus rivals and proposes reforms shaping the affordability and pace of decarbonisation." },
  // ── health
  "health-eu4health": { relevance: "context", hook: "Funds health-system resilience and crisis-preparedness capacity underpinning delivery of climate-adaptation health measures like heat-health response." },
  "health-cbht": { relevance: "adjacent", hook: "Its cross-border health-threat surveillance mandate covers climate-sensitive risks like heatwaves and vector-borne disease, material to adaptation tracking." },
  "health-ecdc": { relevance: "adjacent", hook: "ECDC's strengthened surveillance mandate tracks climate-sensitive disease spread, such as vector-borne and heat-related illness, feeding adaptation assessment." },
  "health-hera": { relevance: "context", hook: "Builds EU medical-countermeasure and emergency-response capacity; institutional preparedness infrastructure with no direct climate mandate." },
  "health-ehds": { relevance: "context", hook: "Creates shared EU health-data infrastructure; no climate provisions, though it could eventually support climate-health impact research." },
  "health-mdr": { relevance: "context", hook: "Sets market-access and safety rules for medical devices; no climate or energy-transition content relevant to the Board." },
  "health-ivdr": { relevance: "context", hook: "Sets safety and performance rules for diagnostic devices; no material climate or energy provisions for the Board to weigh." },
  "health-medicinal-products-dir": { relevance: "context", hook: "Governs medicine authorisation, manufacturing and labelling; a product-safety framework with no climate content." },
  "health-pharma-reform-proposal": { relevance: "context", hook: "Recasts pharma rules for access and supply security; its environmental provisions target water pollution, not GHG or energy." },
  "health-clinical-trials": { relevance: "context", hook: "Harmonises clinical-trial approval procedures EU-wide; a purely procedural instrument with no climate relevance." },
  "health-tobacco-products": { relevance: "context", hook: "Regulates tobacco manufacturing and sale for public health; unrelated to emissions, energy or climate adaptation." },
  "health-general-food-law": { relevance: "context", hook: "Sets food-safety and traceability principles and creates EFSA; no GHG, energy or agricultural-emissions provisions." },
  "health-official-controls": { relevance: "context", hook: "Sets enforcement rules for food, feed and animal-health compliance checks; a control instrument with no climate content." },
  "health-hta": { relevance: "context", hook: "Creates joint EU clinical assessment of health technologies; a market-access procedure with no climate relevance." },
  "health-cancer-plan": { relevance: "context", hook: "Cancer prevention targets pollutant exposure, lending health co-benefit framing to decarbonisation politics, but sets no GHG measures itself." },
  "health-pharma-strategy": { relevance: "context", hook: "Sets a medicines-access and innovation strategy; no material climate or energy-transition provisions." },
  "health-amr-recommendation": { relevance: "context", hook: "One Health AMR recommendation flags environmental drivers of resistance spread but carries no binding climate or GHG provisions." },
  "health-eu4health-ia": { relevance: "context", hook: "Impact assessment behind EU4Health funding design; a procedural document with no climate content of its own." },
  "health-mdr-implementing": { relevance: "context", hook: "Sets technical specs for reprocessing single-use medical devices; a narrow implementing measure with no climate relevance." },
  // ── security
  "security-teu": { relevance: "context", hook: "Establishes CFSP and mutual-defence competence, the institutional basis for EU external climate diplomacy, but sets no emissions or energy provisions." },
  "security-tfeu": { relevance: "context", hook: "Provides the treaty basis for security and border policy; no direct climate content but frames competing legislative priorities and institutional bandwidth." },
  "security-security-union-strategy": { relevance: "context", hook: "Sets 2020-2025 priorities on terrorism, crime and cybercrime, competing for Commission legislative and political bandwidth against the climate agenda." },
  "security-strategic-compass": { relevance: "context", hook: "Sets EU military ambition and capability targets through 2030, driving defence spending that competes fiscally with climate-transition investment." },
  "security-white-paper-defence": { relevance: "adjacent", hook: "Blueprint to scale EU defence spending and industrial output by 2030, adding energy-intensive manufacturing capacity the Board must weigh against clean-tech ramp-up." },
  "security-edf": { relevance: "adjacent", hook: "Co-finances collaborative defence R&D and production, expanding energy- and material-intensive industrial capacity that competes with net-zero manufacturing for inputs." },
  "security-edf-ia": { relevance: "adjacent", hook: "Assesses the industrial-capacity and resource options behind the Defence Fund, the same energy-intensive production trade-offs the Board must track." },
  "security-asap": { relevance: "adjacent", hook: "Temporarily scales up ammunition and missile production, raising energy-intensive metals and explosives output that competes with clean-tech industrial capacity." },
  "security-edirpa": { relevance: "adjacent", hook: "Incentivises joint defence procurement, driving the same energy- and materials-intensive defence-industrial ramp-up relevant to net-zero manufacturing capacity." },
  "security-ukraine-facility": { relevance: "adjacent", hook: "Finances Ukraine's reconstruction through 2027, determining whether rebuilt energy infrastructure locks in fossil assets or leapfrogs to clean systems." },
  "security-sanctions-russia": { relevance: "adjacent", hook: "Core sanctions regime restricting Russian oil and gas trade, reshaping EU fossil-fuel dependency and accelerating the REPowerEU energy shift." },
  "security-sanctions-decision": { relevance: "adjacent", hook: "CFSP decision underpinning the Russia sanctions regime that curtailed EU fossil-fuel imports and reshaped the bloc's energy-transition trajectory." },
  "security-cyber-solidarity": { relevance: "context", hook: "Builds EU capacity to respond to major cyber incidents; not energy-sector specific, so it shapes institutional resilience rather than the climate trajectory." },
  "security-europol": { relevance: "context", hook: "Strengthens police cooperation and data powers; no climate content, relevant only as part of the security acquis competing for legislative capacity." },
  "security-frontex": { relevance: "context", hook: "Expands border-guard capacity and standing corps; no climate provisions, though migration pressure is partly driven by climate impacts abroad." },
  "security-sbc": { relevance: "context", hook: "Codifies Schengen border-control rules; no GHG content, relevant only via the political salience of migration debates crowding out climate legislation." },
  "security-sbc-2024-revision": { relevance: "context", hook: "Updates border-check rules for crises and instrumentalised migration; no climate provisions, shapes only the EU's institutional crisis-response bandwidth." },
  "security-migration-pact-communication": { relevance: "context", hook: "Launches the migration and asylum reform package; no climate provisions, but migration and climate-adaptation politics increasingly compete for Council attention." },
  "security-amm": { relevance: "context", hook: "Reforms asylum-responsibility allocation among states; no climate content, relevant only as a rival claim on Council and Parliament legislative capacity." },
  "security-screening": { relevance: "context", hook: "Introduces mandatory pre-entry migrant screening; no GHG or energy provisions, relevant only to the political bandwidth available for climate files." },
  "security-firearms": { relevance: "context", hook: "Harmonises civilian firearms trade to curb trafficking; no climate content and no plausible feasibility channel for the Board's mandate." },
  "security-cer": { relevance: "adjacent", hook: "Requires resilience of critical infrastructure, explicitly including energy, against physical and hybrid threats to grids underpinning the transition." },
  // ── digital
  "digital-gdpr": { relevance: "context", hook: "Sets EU data-protection rules; no climate content, but compliance costs shape feasibility of smart-meter and EV data flows enabling flexibility." },
  "digital-eprivacy-directive": { relevance: "context", hook: "Regulates cookies and e-communications privacy; no climate provisions, though consent rules affect smart-metering and demand-response digital services' rollout." },
  "digital-dsa": { relevance: "context", hook: "Imposes content-moderation duties on platforms; no GHG provisions, but curbing climate disinformation's spread shapes public support for climate policy." },
  "digital-dma": { relevance: "context", hook: "Opens gatekeeper platforms to competition; no climate content, though contestability affects market access for clean-tech apps and energy services." },
  "digital-ai-act": { relevance: "adjacent", hook: "Requires general-purpose AI providers to report energy consumption, tying the AI Act to the electricity-demand surge from compute-intensive models." },
  "digital-data-act": { relevance: "adjacent", hook: "Grants access to data from connected devices, including smart meters and EVs, unlocking demand-response and smart-charging flexibility for the grid." },
  "digital-dga": { relevance: "context", hook: "Creates voluntary data-sharing mechanisms; no direct GHG provisions, though it underpins the still-nascent Green Deal data space's institutional design." },
  "digital-nis2": { relevance: "adjacent", hook: "Sets cybersecurity obligations for essential entities explicitly including electricity, gas and district heating, protecting the digitalised grid the transition depends on." },
  "digital-cra": { relevance: "context", hook: "Sets cybersecurity requirements for digital products generally; no energy-sector carve-out, so its climate link is weaker than sector-specific NIS2/CER rules." },
  "digital-cybersecurity-act": { relevance: "context", hook: "Establishes ENISA and an ICT certification scheme; no climate content, a horizontal institutional instrument rather than an energy-sector measure." },
  "digital-eidas2": { relevance: "context", hook: "Creates the EU Digital Identity Wallet; no climate provisions, a pure digital-governance instrument outside the Board's coherence remit." },
  "digital-decade-decision": { relevance: "context", hook: "Sets 2030 digital targets for skills and infrastructure; no specific energy or GHG provisions despite growing data-centre electricity demand." },
  "digital-open-data-directive": { relevance: "context", hook: "Promotes reuse of public-sector data, including environmental datasets, but sets no binding climate provisions itself." },
  "digital-platform-work-directive": { relevance: "context", hook: "Regulates gig-platform working conditions and algorithmic management; no climate nexus, included only for completeness of the digital domain." },
  "digital-gigabit-infrastructure-act": { relevance: "context", hook: "Speeds up gigabit-network rollout by easing civil-works duplication; no material GHG provisions despite telecom's growing electricity footprint." },
  "digital-shaping-digital-future": { relevance: "context", hook: "Sets the Commission's overarching digital strategy; no specific climate content, a framing communication rather than a binding instrument." },
  "digital-2030-digital-compass": { relevance: "context", hook: "Outlines digital-transformation targets and pillars for 2030; no material climate provisions of its own." },
  "digital-ai-continent-action-plan": { relevance: "adjacent", hook: "Plans to expand EU AI computing infrastructure, a major new electricity load the power system and renewables build-out must accommodate." },
  "digital-dsa-transparency-delegated-act": { relevance: "context", hook: "Specifies platform transparency-report templates under the DSA; a technical implementing measure with no independent climate content." },
  "digital-nis2-implementing-regulation": { relevance: "context", hook: "Sets technical cybersecurity rules for digital-infrastructure providers like cloud and DNS services, not the energy-sector entities NIS2 also covers." },
  "digital-ai-act-gpai-code-of-practice": { relevance: "adjacent", hook: "Operationalises AI Act energy-consumption reporting for general-purpose AI models, the compliance channel for tracking AI's growing power demand." },
  "digital-ai-act-impact-assessment": { relevance: "adjacent", hook: "Assesses the policy options behind the AI Act, including the compute and energy-demand trade-offs the Board can track downstream." },
  // ── transport
  "transport-co2-cars-vans": { relevance: "core", hook: "Sets binding fleet-wide CO2 targets for new cars and vans, the core EU tool for road-transport decarbonisation." },
  "transport-co2-cars-vans-2023": { relevance: "core", hook: "Locks in a 100% CO2 cut for new cars and vans by 2035, the contested anchor of transport decarbonisation." },
  "transport-co2-cars-ia": { relevance: "core", hook: "Analytical backbone for the car/van CO2 targets; its assumptions underpin the Board's assessment of the 2035 target's credibility." },
  "transport-co2-cars-reporting-ir": { relevance: "core", hook: "Sets the MRV rules ensuring car/van CO2 compliance data the Board relies on is accurate and comparable." },
  "transport-hdv-co2": { relevance: "core", hook: "Sets binding CO2-cut targets for trucks, buses and trailers, core climate architecture for heavy road freight." },
  "transport-afir": { relevance: "core", hook: "Mandates EU-wide recharging and refuelling infrastructure along TEN-T corridors, enabling road-transport electrification and decarbonisation." },
  "transport-refueleu-aviation": { relevance: "core", hook: "Mandates rising sustainable-aviation-fuel shares at EU airports, the EU's core lever for aviation decarbonisation." },
  "transport-fueleu-maritime": { relevance: "core", hook: "Caps the GHG intensity of shipping fuel used at EU ports, the core maritime decarbonisation instrument." },
  "transport-tent": { relevance: "adjacent", hook: "Sets deadlines and priorities for freight/passenger corridors and military mobility; corridor choices shape modal shift and transport emissions." },
  "transport-eurovignette": { relevance: "adjacent", hook: "Lets states set heavy-vehicle tolls by CO2 emissions, a material carbon-price lever layered on infrastructure financing." },
  "transport-its": { relevance: "context", hook: "Deploys digital traffic-management systems; efficiency data could support emissions monitoring but carries no binding climate provisions." },
  "transport-ses": { relevance: "adjacent", hook: "Optimises EU airspace and flight routing, cutting fuel burn from route inefficiency, a material aviation-emissions lever." },
  "transport-rail-recast": { relevance: "adjacent", hook: "Opens rail networks to competition, supporting the modal shift from road and air to the lowest-carbon transport mode." },
  "transport-rail-market-pillar": { relevance: "adjacent", hook: "Opens domestic rail passenger markets to competition, reinforcing modal-shift potential toward low-carbon rail transport." },
  "transport-weights-dimensions": { relevance: "adjacent", hook: "Allows aerodynamic and low-emission truck features within weight/dimension limits, a material fuel-efficiency provision for road freight." },
  "transport-euro7": { relevance: "adjacent", hook: "Sets pollutant and battery-durability rules for vehicles, shaping EV lifecycle standards alongside its air-quality mandate." },
  "transport-driving-licence": { relevance: "context", hook: "Harmonises driving-licence categories and mutual recognition; an administrative measure with no climate content." },
  "transport-smart-mobility-strategy": { relevance: "core", hook: "The Commission's overarching roadmap to make EU transport smart, sustainable and resilient by 2050, framing sectoral decarbonisation." },
  "transport-automotive-action-plan": { relevance: "adjacent", hook: "Industrial support for the auto sector's green transition, material to whether the contested 2035 CO2 target survives." },
  // ── agriculture-food
  "agriculture-food-cap-strategic-plans": { relevance: "adjacent", hook: "CAP eco-schemes, conditionality and land-management choices set within these plans materially drive agricultural GHG emissions and carbon-sink trends." },
  "agriculture-food-cap-horizontal": { relevance: "context", hook: "Finances and audits CAP payments, including enforcement of climate-relevant conditionality standards, but sets no substantive climate rules itself." },
  "agriculture-food-cmo": { relevance: "context", hook: "Organises agricultural product markets and marketing standards; a market-structure instrument with no climate or GHG content." },
  "agriculture-food-organic": { relevance: "adjacent", hook: "Cuts synthetic fertiliser and pesticide use, lowering N2O emissions and supporting soil-carbon co-benefits versus conventional farming." },
  "agriculture-food-pesticides-sud": { relevance: "context", hook: "Cuts pesticide risk to health and ecosystems through integrated pest management; no material direct GHG consequences." },
  "agriculture-food-sur-proposal-withdrawn": { relevance: "context", hook: "Its 2024 withdrawal under farm-lobby pressure signals the political limits on green agri-legislation the Board must weigh." },
  "agriculture-food-fertilising-products": { relevance: "adjacent", hook: "Opens the market to recycled and organic fertilisers, cutting reliance on high-GHG synthetic nitrogen fertiliser production and use." },
  "agriculture-food-cfp": { relevance: "context", hook: "Sets fish-stock quotas and sustainability rules for fisheries management; no material GHG or energy-transition provisions." },
  "agriculture-food-emfaf": { relevance: "context", hook: "Funds fisheries, aquaculture and blue-economy investment; a fiscal channel that could but does not mandate fleet decarbonisation." },
  "agriculture-food-animal-health-law": { relevance: "context", hook: "Consolidates disease-prevention and biosecurity rules for livestock; no material climate or GHG provisions." },
  "agriculture-food-plant-health": { relevance: "context", hook: "Sets biosecurity measures against pests entering the EU; climate-driven pest range shifts make it relevant background, not core." },
  "agriculture-food-ngt-proposal": { relevance: "adjacent", hook: "Eases rules for gene-edited crops, potentially enabling drought-tolerant, lower-input varieties material to agricultural adaptation and emissions." },
  "agriculture-food-farm-to-fork": { relevance: "adjacent", hook: "Sets EU targets to cut fertiliser and pesticide use, with material consequences for agricultural GHG emissions and land use." },
  "agriculture-food-vision-agriculture-food": { relevance: "adjacent", hook: "Signals a 2025 pivot toward farm competitiveness and income, testing whether CAP conditionality's climate ambition survives the shift." },
  "agriculture-food-strategic-dialogue": { relevance: "adjacent", hook: "Stakeholder consensus on trading off farm competitiveness against environmental ambition, shaping the CAP's post-2027 climate trajectory." },
  "agriculture-food-cap-ia-swd": { relevance: "adjacent", hook: "Assesses design options for CAP eco-schemes and conditionality, the mechanisms carrying most of the sector's climate ambition." },
  "agriculture-food-cfp-implementing-act": { relevance: "context", hook: "Sets technical data-collection and control rules for fisheries enforcement; no climate content of its own." },
  // ── economy-social
  "economy-social-sgp-preventive": { relevance: "context", hook: "Fiscal adjustment plans under the reformed SGP constrain the public investment space available for the climate transition." },
  "economy-social-sgp-corrective": { relevance: "context", hook: "Excessive-deficit enforcement shapes the fiscal headroom member states have for climate and energy investment." },
  "economy-social-budgetary-frameworks-dir": { relevance: "context", hook: "Strengthens national budget-framework rules underpinning fiscal surveillance, indirectly bounding space for climate-related public spending." },
  "economy-social-rrf": { relevance: "adjacent", hook: "Requires member states to earmark at least 37% of recovery spending for climate objectives under a 'do no significant harm' test." },
  "economy-social-cpr": { relevance: "adjacent", hook: "Sets the climate-mainstreaming and 'do no significant harm' rules governing roughly 30% of cohesion-fund spending EU-wide." },
  "economy-social-taxonomy": { relevance: "adjacent", hook: "Defines which economic activities count as climate-aligned, determining which investments qualify as green-labelled sustainable finance." },
  "economy-social-sfdr": { relevance: "adjacent", hook: "Forces financial firms to disclose climate and sustainability risk integration, channelling capital flows toward or away from the transition." },
  "economy-social-csrd": { relevance: "adjacent", hook: "Mandates corporate GHG-emissions and climate-transition-plan disclosure, creating the data backbone for tracking corporate decarbonisation." },
  "economy-social-csddd": { relevance: "adjacent", hook: "Requires large companies to adopt Paris-aligned climate transition plans and address environmental harm across value chains." },
  "economy-social-green-bond": { relevance: "adjacent", hook: "Sets a voluntary 'green bond' label requiring proceeds to fund Taxonomy-aligned climate and environmental projects." },
  "economy-social-omnibus-i": { relevance: "adjacent", hook: "Would narrow CSRD, CSDDD and Taxonomy reporting scope, directly weakening the EU's climate-risk and transition-plan disclosure architecture." },
  "economy-social-mica": { relevance: "adjacent", hook: "Requires crypto-asset issuers to disclose the energy consumption and environmental impact of their consensus mechanisms." },
  "economy-social-crr": { relevance: "context", hook: "General bank capital rules shape systemic lending capacity for climate investment, without dedicated climate-risk provisions in this base act." },
  "economy-social-crd4": { relevance: "context", hook: "Governs bank supervision and governance alongside CRR, determining institutional capacity to finance the transition, without climate-specific rules." },
  "economy-social-minimum-wage": { relevance: "context", hook: "Statutory minimum-wage floors affect the social acceptability of rising ETS2 carbon costs falling on low-income households." },
  "economy-social-pay-transparency": { relevance: "context", hook: "Equal-pay disclosure rule with no climate link, included only as part of the EU's social-policy backdrop." },
  "economy-social-jtf": { relevance: "core", hook: "Directly funds regions and workers exiting carbon-intensive industries, a core financing pillar of the EU's decarbonisation pathway." },
  "economy-social-epsr": { relevance: "context", hook: "General social-rights proclamation with no climate content, relevant only as the normative backdrop for 'just transition' framing." },
  "economy-social-sustainable-finance-strategy": { relevance: "adjacent", hook: "Sets Commission actions to scale sustainable finance and manage climate-related financial risk, underpinning transition capital flows." },
  "economy-social-savings-investments-union": { relevance: "context", hook: "A general capital-markets deepening strategy that may indirectly channel savings into green investment, with no dedicated climate provisions." },
  "economy-social-taxonomy-climate-da": { relevance: "core", hook: "Defines the technical criteria for what counts as climate mitigation or adaptation — the operational core of green finance classification." },
  "economy-social-csddd-impact-assessment": { relevance: "adjacent", hook: "Analyses costs and options behind CSDDD's due-diligence and climate-transition-plan requirements before their adoption." },
};

export const STATUS: Record<string, { status: InstrumentStatus; note: string; sourceRef?: string; confident: boolean }> = {
  // ── climate-energy
  "climate-energy-climate-law": { status: "under-revision", note: "Commission proposed amending the Climate Law to embed a binding 2040 target with flexibilities.", confident: false },
  "climate-energy-ets-directive": { status: "under-revision", note: "ETS Directive under Phase-5 review; Commission tabled amending proposal in July 2026.", sourceRef: "COM(2026) 616", confident: true },
  "climate-energy-cbam": { status: "under-revision", note: "Simplification (de minimis threshold) and possible scope extension under discussion around the 2026 definitive phase.", confident: false },
  // ── environment
  "environment-reach-regulation": { status: "watch", note: "Long-announced REACH revision repeatedly delayed since 2022; still pending.", confident: false },
  // ── health
  "health-mdr": { status: "watch", note: "Targeted revision of MDR transition/enforcement rules under discussion.", confident: false },
  "health-ivdr": { status: "watch", note: "Targeted revision alongside the MDR reform reportedly under discussion.", confident: false },
  "health-pharma-reform-proposal": { status: "proposal", note: "Still a Commission proposal; co-legislator adoption not confirmed as of mid-2026.", confident: false },
  // ── digital
  "digital-gdpr": { status: "reopened", note: "Digital Omnibus (late 2025) proposed simplifications to some GDPR obligations.", confident: false },
  "digital-eprivacy-directive": { status: "reopened", note: "Digital Omnibus reportedly touches cookie/ePrivacy consent rules as part of simplification.", confident: false },
  "digital-ai-act": { status: "reopened", note: "Digital Omnibus proposed delaying/simplifying some AI Act high-risk-system obligations.", confident: false },
  "digital-data-act": { status: "reopened", note: "Digital Omnibus reportedly proposed simplification of Data Act obligations.", confident: false },
  // ── transport
  "transport-automotive-action-plan": { status: "proposal", note: "Marked '(proposal)' in title, though largely a strategic communication rather than pending legislation.", confident: false },
  // ── agriculture-food
  "agriculture-food-cap-strategic-plans": { status: "watch", note: "MFF 2028-34 proposal would restructure CAP funding into unified national plans.", confident: false },
  "agriculture-food-ngt-proposal": { status: "proposal", note: "Gene-editing rules in late-stage negotiation; exact adoption status uncertain.", confident: false },
  // ── economy-social
  "economy-social-rrf": { status: "watch", note: "RRF structure referenced as a model in the proposed MFF 2028-34 reshaping of EU funds.", confident: false },
  "economy-social-cpr": { status: "watch", note: "MFF 2028-34 proposal would fold cohesion funds into unified national partnership plans.", confident: false },
  "economy-social-taxonomy": { status: "reopened", note: "Reporting obligations under the Taxonomy simplified via the Omnibus I package.", sourceRef: "COM(2025) 81", confident: true },
  "economy-social-sfdr": { status: "under-revision", note: "Commission working on SFDR simplification/revision alongside the sustainable-finance omnibus effort.", confident: false },
  "economy-social-csrd": { status: "reopened", note: "Reporting scope and thresholds narrowed by Omnibus I simplification package, still in trilogue.", sourceRef: "COM(2025) 81", confident: true },
  "economy-social-csddd": { status: "reopened", note: "Due-diligence obligations delayed and narrowed by the Omnibus I package.", sourceRef: "COM(2025) 81", confident: true },
  "economy-social-omnibus-i": { status: "proposal", note: "The package itself is an unadopted Commission proposal, still in trilogue.", sourceRef: "COM(2025) 81", confident: true },
  "economy-social-jtf": { status: "watch", note: "Just Transition Fund reportedly folded into the proposed MFF 2028-34 national partnership plans.", confident: false },
  "economy-social-taxonomy-climate-da": { status: "reopened", note: "Technical screening and reporting templates simplified alongside Omnibus I taxonomy changes.", confident: false },
};
