/**
 * EU Policy Hierarchy — cross-module bridges (WP-7).
 *
 * GENERATED deterministically by joining this module's CELEX numbers against
 * src/data/policies.ts (Policy Navigator) and src/data/sectoral-policies.ts.
 * No AI judgement involved — pure key join; regenerate when either side changes.
 */

export const NAVIGATOR_BRIDGE: Record<string, { policyId: string; domain: string }> = {
  "climate-energy-climate-law": { policyId: "eu-climate-law", domain: "climate" },
  "climate-energy-ets-directive": { policyId: "eu-ets-directive", domain: "climate" },
  "climate-energy-effort-sharing-regulation": { policyId: "effort-sharing-regulation", domain: "climate" },
  "climate-energy-lulucf-regulation": { policyId: "lulucf-regulation", domain: "climate" },
  "climate-energy-cbam": { policyId: "cbam-regulation", domain: "finance" },
  "climate-energy-eed-recast": { policyId: "energy-efficiency-directive", domain: "energy" },
  "climate-energy-epbd-recast": { policyId: "epbd-recast", domain: "energy" },
  "climate-energy-governance": { policyId: "governance-regulation", domain: "cross-cutting" },
  "climate-energy-methane": { policyId: "methane-regulation", domain: "energy" },
  "climate-energy-scf": { policyId: "social-climate-fund", domain: "finance" },
  "climate-energy-hydrogen-gas-directive": { policyId: "hydrogen-gas-package", domain: "energy" },
  "climate-energy-green-deal": { policyId: "eu-green-deal", domain: "cross-cutting" },
  "climate-energy-fit-for-55": { policyId: "fit-for-55", domain: "cross-cutting" },
  "climate-energy-repowereu": { policyId: "repowereu-plan", domain: "energy" },
  "climate-energy-fgas-regulation": { policyId: "f-gas-regulation", domain: "climate" },
  "climate-energy-eu-adaptation-strategy": { policyId: "eu-adaptation-strategy", domain: "climate" },
  "environment-birds-directive": { policyId: "birds-directive", domain: "environment" },
  "environment-habitats-directive": { policyId: "habitats-directive", domain: "environment" },
  "environment-nature-restoration-regulation": { policyId: "nature-restoration-law", domain: "climate" },
  "environment-water-framework-directive": { policyId: "water-framework-directive", domain: "environment" },
  "environment-air-quality-directive": { policyId: "air-quality-directive", domain: "environment" },
  "environment-industrial-emissions-directive": { policyId: "industrial-emissions-directive", domain: "industry" },
  "environment-reach-regulation": { policyId: "reach-regulation", domain: "environment" },
  "environment-waste-framework-directive": { policyId: "waste-framework-directive", domain: "circular_economy" },
  "environment-packaging-waste-regulation": { policyId: "packaging-waste-regulation", domain: "circular_economy" },
  "environment-ecodesign-espr-regulation": { policyId: "ecodesign-sustainable-products", domain: "circular_economy" },
  "environment-batteries-regulation": { policyId: "batteries-regulation", domain: "circular_economy" },
  "environment-deforestation-regulation": { policyId: "deforestation-regulation", domain: "agriculture" },
  "environment-eia-directive": { policyId: "eia-directive", domain: "environment" },
  "environment-8eap-decision": { policyId: "eighth-environment-action-programme", domain: "environment" },
  "environment-zero-pollution-action-plan": { policyId: "zero-pollution-action-plan", domain: "environment" },
  "environment-marine-strategy-framework-directive": { policyId: "marine-strategy-framework-directive", domain: "environment" },
  "trade-foreign-subsidies": { policyId: "foreign-subsidies-regulation", domain: "trade" },
  "trade-ipi": { policyId: "ipi-regulation", domain: "trade" },
  "trade-aci": { policyId: "anti-coercion-instrument", domain: "trade" },
  "trade-eu-uk-tca": { policyId: "eu-uk-tca", domain: "trade" },
  "competitiveness-chips-act": { policyId: "european-chips-act", domain: "digital" },
  "competitiveness-nzia": { policyId: "net-zero-industry-act", domain: "industry" },
  "competitiveness-crma": { policyId: "critical-raw-materials-act", domain: "industry" },
  "competitiveness-merger-regulation": { policyId: "eu-merger-regulation", domain: "trade" },
  "competitiveness-horizon-europe": { policyId: "horizon-europe", domain: "cross-cutting" },
  "competitiveness-investeu": { policyId: "investeu-regulation", domain: "finance" },
  "competitiveness-competitiveness-compass": { policyId: "competitiveness-compass", domain: "cross-cutting" },
  "health-cbht": { policyId: "cross-border-health-threats", domain: "health" },
  "health-ehds": { policyId: "ehds", domain: "health" },
  "health-mdr": { policyId: "medical-devices-regulation", domain: "health" },
  "health-clinical-trials": { policyId: "clinical-trials-regulation", domain: "health" },
  "health-general-food-law": { policyId: "general-food-law", domain: "agriculture" },
  "security-edf": { policyId: "european-defence-fund", domain: "security" },
  "security-cer": { policyId: "critical-entities-resilience", domain: "cross-cutting" },
  "digital-gdpr": { policyId: "gdpr", domain: "digital" },
  "digital-eprivacy-directive": { policyId: "eprivacy-directive", domain: "digital" },
  "digital-dsa": { policyId: "digital-services-act", domain: "digital" },
  "digital-dma": { policyId: "digital-markets-act", domain: "digital" },
  "digital-ai-act": { policyId: "ai-act", domain: "digital" },
  "digital-data-act": { policyId: "data-act", domain: "digital" },
  "digital-nis2": { policyId: "nis2-directive", domain: "security" },
  "digital-cra": { policyId: "cyber-resilience-act", domain: "digital" },
  "digital-platform-work-directive": { policyId: "platform-workers-directive", domain: "digital" },
  "digital-gigabit-infrastructure-act": { policyId: "gigabit-infrastructure-act", domain: "digital" },
  "transport-co2-cars-vans": { policyId: "co2-cars-regulation", domain: "transport" },
  "transport-hdv-co2": { policyId: "co2-hdv-regulation", domain: "transport" },
  "transport-afir": { policyId: "afir-regulation", domain: "transport" },
  "transport-refueleu-aviation": { policyId: "refueleu-aviation", domain: "transport" },
  "transport-fueleu-maritime": { policyId: "fueleu-maritime", domain: "transport" },
  "transport-tent": { policyId: "ten-t-regulation", domain: "transport" },
  "transport-euro7": { policyId: "euro-7-regulation", domain: "transport" },
  "agriculture-food-cap-strategic-plans": { policyId: "cap-strategic-plans", domain: "agriculture" },
  "agriculture-food-organic": { policyId: "organic-farming-regulation", domain: "agriculture" },
  "agriculture-food-farm-to-fork": { policyId: "farm-to-fork-strategy", domain: "agriculture" },
  "economy-social-cpr": { policyId: "common-provisions-regulation", domain: "cross-cutting" },
  "economy-social-taxonomy": { policyId: "taxonomy-regulation", domain: "finance" },
  "economy-social-sfdr": { policyId: "sfdr", domain: "finance" },
  "economy-social-csrd": { policyId: "csrd", domain: "finance" },
  "economy-social-csddd": { policyId: "csddd", domain: "trade" },
  "economy-social-green-bond": { policyId: "green-bonds-regulation", domain: "finance" },
  "economy-social-mica": { policyId: "mica-regulation", domain: "finance" },
  "economy-social-crr": { policyId: "crr-regulation", domain: "finance" },
  "economy-social-jtf": { policyId: "just-transition-fund", domain: "cross-cutting" },
};

export const SECTOR_BRIDGE: Record<string, string[]> = {
  "climate-energy-climate-law": ["cross-cutting"],
  "climate-energy-ets-directive": ["industry", "power", "transport-aviation", "transport-maritime"],
  "climate-energy-ets2": ["buildings", "industry", "transport-maritime", "transport-road"],
  "climate-energy-effort-sharing-regulation": ["agriculture", "buildings", "industry", "transport-road", "waste"],
  "climate-energy-lulucf-regulation": ["lulucf"],
  "climate-energy-cbam": ["industry"],
  "climate-energy-red3": ["buildings", "industry", "power", "transport-road"],
  "climate-energy-eed-recast": ["buildings", "cross-cutting", "industry", "power"],
  "climate-energy-epbd-recast": ["buildings"],
  "climate-energy-governance": ["cross-cutting"],
  "climate-energy-methane": ["cross-cutting", "industry", "waste"],
  "climate-energy-scf": ["buildings", "transport-road"],
  "climate-energy-fit-for-55": ["cross-cutting"],
  "environment-nature-restoration-regulation": ["agriculture", "lulucf"],
  "environment-industrial-emissions-directive-revision": ["industry"],
  "environment-waste-framework-directive": ["cross-cutting", "waste"],
  "environment-ecodesign-espr-regulation": ["buildings", "cross-cutting", "industry"],
  "environment-deforestation-regulation": ["agriculture", "cross-cutting", "lulucf"],
  "competitiveness-nzia": ["industry"],
  "competitiveness-crma": ["industry"],
  "transport-co2-cars-vans-2023": ["transport-road"],
  "transport-hdv-co2": ["transport-road"],
  "transport-afir": ["transport-maritime", "transport-road"],
  "transport-refueleu-aviation": ["transport-aviation"],
  "transport-fueleu-maritime": ["transport-maritime"],
  "transport-eurovignette": ["transport-road"],
  "agriculture-food-cap-strategic-plans": ["agriculture", "lulucf"],
  "agriculture-food-farm-to-fork": ["agriculture"],
  "economy-social-taxonomy": ["cross-cutting"],
  "economy-social-jtf": ["cross-cutting"],
};
