/**
 * EU Policy Hierarchy — lead Commission service per instrument (chef de file).
 *
 * GENERATED: compiled by Sonnet agents (one per branch group, July 2026).
 * First code = lead DG; second/third only where a service genuinely co-leads
 * or owns implementation. ["NONE"] marks primary law no DG owns.
 * AI-drafted attribution pending Secretariat review — DG responsibilities
 * shift with Commission reorganisations.
 */

export const LEAD_DGS: Record<string, string[]> = {
  // ── primary-law
  "primary-law-teu": ["NONE"],
  "primary-law-tfeu": ["NONE"],
  "primary-law-charter": ["NONE"],
  "primary-law-euratom": ["NONE"],
  "primary-law-protocol-2-subsidiarity": ["NONE"],
  "primary-law-protocol-1-national-parliaments": ["NONE"],
  "primary-law-charter-explanations": ["NONE"],
  "primary-law-treaty-lisbon": ["NONE"],
  "primary-law-iia-better-law-making-2016": ["SG"],
  "primary-law-comitology-regulation": ["SG"],
  "primary-law-better-regulation-communication": ["SG"],
  "primary-law-better-regulation-guidelines": ["SG"],
  "primary-law-better-regulation-toolbox": ["SG"],
  "primary-law-iia-transparency-register": ["SG"],
  "primary-law-framework-agreement-ep-commission": ["SG"],
  // ── climate-energy
  "climate-energy-climate-law": ["CLIMA"],
  "climate-energy-ets-directive": ["CLIMA"],
  "climate-energy-msr": ["CLIMA"],
  "climate-energy-ets2": ["CLIMA"],
  "climate-energy-effort-sharing-regulation": ["CLIMA"],
  "climate-energy-lulucf-regulation": ["CLIMA", "AGRI"],
  "climate-energy-cbam": ["CLIMA", "TAXUD"],
  "climate-energy-red3": ["ENER"],
  "climate-energy-eed-recast": ["ENER"],
  "climate-energy-epbd-recast": ["ENER"],
  "climate-energy-governance": ["ENER", "CLIMA"],
  "climate-energy-methane": ["ENER", "CLIMA"],
  "climate-energy-scf": ["CLIMA", "EMPL"],
  "climate-energy-electricity-regulation": ["ENER"],
  "climate-energy-electricity-directive": ["ENER"],
  "climate-energy-hydrogen-gas-directive": ["ENER"],
  "climate-energy-hydrogen-gas-regulation": ["ENER"],
  "climate-energy-green-deal": ["SG", "CLIMA"],
  "climate-energy-fit-for-55": ["CLIMA", "ENER"],
  "climate-energy-2040-target": ["CLIMA"],
  "climate-energy-repowereu": ["ENER", "CLIMA"],
  "climate-energy-paris-decision": ["CLIMA"],
  "climate-energy-cbam-implementing-reg": ["CLIMA", "TAXUD"],
  "climate-energy-red-rfnbo-delegated-act": ["ENER"],
  "climate-energy-2030-target-plan-ia": ["CLIMA"],
  "climate-energy-2040-target-ia": ["CLIMA"],
  "climate-energy-energy-taxation-directive": ["TAXUD"],
  "climate-energy-fgas-regulation": ["CLIMA"],
  "climate-energy-ccs-directive": ["CLIMA"],
  "climate-energy-industrial-carbon-management-strategy": ["CLIMA"],
  "climate-energy-eu-adaptation-strategy": ["CLIMA"],
  // ── environment
  "environment-birds-directive": ["ENV"],
  "environment-habitats-directive": ["ENV"],
  "environment-nature-restoration-regulation": ["ENV"],
  "environment-water-framework-directive": ["ENV"],
  "environment-urban-wastewater-directive": ["ENV"],
  "environment-air-quality-directive": ["ENV"],
  "environment-industrial-emissions-directive": ["ENV"],
  "environment-industrial-emissions-directive-revision": ["ENV"],
  "environment-reach-regulation": ["ENV", "GROW"],
  "environment-waste-framework-directive": ["ENV"],
  "environment-packaging-waste-regulation": ["ENV"],
  "environment-ecodesign-espr-regulation": ["GROW", "ENV"],
  "environment-batteries-regulation": ["ENV", "GROW"],
  "environment-deforestation-regulation": ["ENV"],
  "environment-eia-directive": ["ENV"],
  "environment-sea-directive": ["ENV"],
  "environment-environmental-liability-directive": ["ENV"],
  "environment-8eap-decision": ["ENV"],
  "environment-circular-economy-action-plan": ["ENV", "GROW"],
  "environment-zero-pollution-action-plan": ["ENV"],
  "environment-biodiversity-strategy-2030": ["ENV"],
  "environment-nature-restoration-impact-assessment": ["ENV"],
  "environment-marine-strategy-framework-directive": ["ENV", "MARE"],
  // ── trade
  "trade-anti-dumping": ["TRADE"],
  "trade-anti-subsidy": ["TRADE"],
  "trade-enforcement": ["TRADE"],
  "trade-fdi-screening": ["TRADE"],
  "trade-foreign-subsidies": ["COMP", "TRADE"],
  "trade-ipi": ["TRADE"],
  "trade-aci": ["TRADE"],
  "trade-gsp": ["TRADE"],
  "trade-dual-use": ["TRADE"],
  "trade-conflict-minerals": ["TRADE"],
  "trade-forced-labour": ["TRADE", "GROW"],
  "trade-ceta": ["TRADE"],
  "trade-eu-uk-tca": ["SG", "TRADE"],
  "trade-wto": ["TRADE"],
  "trade-policy-review": ["TRADE"],
  "trade-global-gateway": ["EEAS", "TRADE"],
  "trade-economic-security": ["TRADE", "EEAS"],
  "trade-fdi-screening-impl": ["TRADE"],
  "trade-foreign-subsidies-impl": ["COMP", "TRADE"],
  "trade-foreign-subsidies-ia": ["COMP", "TRADE"],
  // ── competitiveness
  "competitiveness-chips-act": ["CNECT", "GROW"],
  "competitiveness-nzia": ["GROW", "CLIMA"],
  "competitiveness-nzia-impact-assessment": ["GROW", "CLIMA"],
  "competitiveness-crma": ["GROW", "TRADE"],
  "competitiveness-crma-impact-assessment": ["GROW", "TRADE"],
  "competitiveness-imera": ["GROW"],
  "competitiveness-late-payment-directive": ["GROW"],
  "competitiveness-services-directive": ["GROW"],
  "competitiveness-transparency-directive": ["GROW"],
  "competitiveness-reg-1-2003": ["COMP"],
  "competitiveness-merger-regulation": ["COMP"],
  "competitiveness-merger-implementing-regulation": ["COMP"],
  "competitiveness-gber": ["COMP"],
  "competitiveness-ceeag": ["COMP"],
  "competitiveness-horizon-europe": ["RTD"],
  "competitiveness-investeu": ["ECFIN"],
  "competitiveness-step": ["ECFIN", "GROW"],
  "competitiveness-industrial-strategy-2020": ["GROW"],
  "competitiveness-green-deal-industrial-plan": ["GROW", "CLIMA"],
  "competitiveness-competitiveness-compass": ["SG", "GROW"],
  "competitiveness-clean-industrial-deal": ["GROW", "CLIMA"],
  "competitiveness-draghi-report": ["SG"],
  // ── health
  "health-eu4health": ["SANTE"],
  "health-cbht": ["SANTE", "HERA"],
  "health-ecdc": ["SANTE"],
  "health-hera": ["HERA", "SANTE"],
  "health-ehds": ["SANTE", "CNECT"],
  "health-mdr": ["SANTE"],
  "health-ivdr": ["SANTE"],
  "health-medicinal-products-dir": ["SANTE"],
  "health-pharma-reform-proposal": ["SANTE"],
  "health-clinical-trials": ["SANTE"],
  "health-tobacco-products": ["SANTE"],
  "health-general-food-law": ["SANTE"],
  "health-official-controls": ["SANTE"],
  "health-hta": ["SANTE"],
  "health-cancer-plan": ["SANTE"],
  "health-pharma-strategy": ["SANTE"],
  "health-amr-recommendation": ["SANTE", "AGRI"],
  "health-eu4health-ia": ["SANTE"],
  "health-mdr-implementing": ["SANTE"],
  // ── security
  "security-security-union-strategy": ["HOME"],
  "security-strategic-compass": ["EEAS"],
  "security-white-paper-defence": ["DEFIS", "EEAS"],
  "security-edf": ["DEFIS"],
  "security-edf-ia": ["DEFIS"],
  "security-asap": ["DEFIS"],
  "security-edirpa": ["DEFIS"],
  "security-ukraine-facility": ["ECFIN"],
  "security-sanctions-russia": ["FISMA", "TRADE"],
  "security-sanctions-decision": ["EEAS"],
  "security-cyber-solidarity": ["CNECT"],
  "security-europol": ["HOME"],
  "security-frontex": ["HOME"],
  "security-sbc": ["HOME"],
  "security-sbc-2024-revision": ["HOME"],
  "security-migration-pact-communication": ["HOME"],
  "security-amm": ["HOME"],
  "security-screening": ["HOME"],
  "security-firearms": ["GROW", "HOME"],
  "security-cer": ["HOME"],
  "security-safe-regulation": ["DEFIS"],
  // ── digital
  "digital-gdpr": ["JUST"],
  "digital-eprivacy-directive": ["CNECT", "JUST"],
  "digital-dsa": ["CNECT"],
  "digital-dma": ["CNECT", "COMP"],
  "digital-ai-act": ["CNECT"],
  "digital-data-act": ["CNECT"],
  "digital-dga": ["CNECT"],
  "digital-nis2": ["CNECT"],
  "digital-cra": ["CNECT"],
  "digital-cybersecurity-act": ["CNECT"],
  "digital-eidas2": ["CNECT"],
  "digital-decade-decision": ["CNECT"],
  "digital-open-data-directive": ["CNECT"],
  "digital-platform-work-directive": ["EMPL"],
  "digital-gigabit-infrastructure-act": ["CNECT"],
  "digital-shaping-digital-future": ["CNECT"],
  "digital-2030-digital-compass": ["CNECT"],
  "digital-ai-continent-action-plan": ["CNECT"],
  "digital-dsa-transparency-delegated-act": ["CNECT"],
  "digital-nis2-implementing-regulation": ["CNECT"],
  "digital-ai-act-gpai-code-of-practice": ["CNECT"],
  "digital-ai-act-impact-assessment": ["CNECT"],
  // ── transport
  "transport-co2-cars-vans": ["CLIMA"],
  "transport-co2-cars-vans-2023": ["CLIMA"],
  "transport-co2-cars-ia": ["CLIMA"],
  "transport-co2-cars-reporting-ir": ["CLIMA"],
  "transport-hdv-co2": ["CLIMA"],
  "transport-afir": ["MOVE", "ENER"],
  "transport-refueleu-aviation": ["MOVE"],
  "transport-fueleu-maritime": ["MOVE"],
  "transport-tent": ["MOVE"],
  "transport-eurovignette": ["MOVE"],
  "transport-its": ["MOVE"],
  "transport-ses": ["MOVE"],
  "transport-rail-recast": ["MOVE"],
  "transport-rail-market-pillar": ["MOVE"],
  "transport-weights-dimensions": ["MOVE"],
  "transport-euro7": ["GROW", "ENV"],
  "transport-driving-licence": ["MOVE"],
  "transport-smart-mobility-strategy": ["MOVE"],
  "transport-automotive-action-plan": ["GROW", "MOVE"],
  // ── agriculture-food
  "agriculture-food-cap-strategic-plans": ["AGRI"],
  "agriculture-food-cap-horizontal": ["AGRI"],
  "agriculture-food-cmo": ["AGRI"],
  "agriculture-food-organic": ["AGRI"],
  "agriculture-food-pesticides-sud": ["SANTE", "AGRI"],
  "agriculture-food-sur-proposal-withdrawn": ["SANTE", "AGRI"],
  "agriculture-food-fertilising-products": ["GROW"],
  "agriculture-food-cfp": ["MARE"],
  "agriculture-food-emfaf": ["MARE"],
  "agriculture-food-animal-health-law": ["SANTE"],
  "agriculture-food-plant-health": ["SANTE"],
  "agriculture-food-ngt-proposal": ["SANTE", "AGRI"],
  "agriculture-food-farm-to-fork": ["SANTE", "AGRI"],
  "agriculture-food-vision-agriculture-food": ["AGRI"],
  "agriculture-food-strategic-dialogue": ["AGRI"],
  "agriculture-food-cap-ia-swd": ["AGRI"],
  "agriculture-food-fisheries-control-regulation": ["MARE"],
  // ── economy-social
  "economy-social-sgp-preventive": ["ECFIN"],
  "economy-social-sgp-corrective": ["ECFIN"],
  "economy-social-budgetary-frameworks-dir": ["ECFIN"],
  "economy-social-rrf": ["ECFIN"],
  "economy-social-cpr": ["REGIO", "EMPL"],
  "economy-social-taxonomy": ["FISMA"],
  "economy-social-sfdr": ["FISMA"],
  "economy-social-csrd": ["FISMA"],
  "economy-social-csddd": ["JUST"],
  "economy-social-green-bond": ["FISMA"],
  "economy-social-omnibus-i": ["FISMA", "JUST"],
  "economy-social-mica": ["FISMA"],
  "economy-social-crr": ["FISMA"],
  "economy-social-crd4": ["FISMA"],
  "economy-social-minimum-wage": ["EMPL"],
  "economy-social-pay-transparency": ["EMPL"],
  "economy-social-jtf": ["REGIO"],
  "economy-social-epsr": ["EMPL"],
  "economy-social-sustainable-finance-strategy": ["FISMA"],
  "economy-social-savings-investments-union": ["FISMA"],
  "economy-social-taxonomy-climate-da": ["FISMA"],
  "economy-social-csddd-impact-assessment": ["JUST"],
};
