/**
 * EU Policy Hierarchy — per-lens relevance rationales.
 *
 * GENERATED: compiled by Sonnet agents (one per branch group, July 2026).
 * For every lens tag on every instrument, one concrete clause completing
 * "<Lens>-relevant because …" — shown in the dot tooltips and, when a lens
 * is active, inline on matching rows. AI-drafted, pending review.
 */
import type { LensId } from './data';

export const LENS_RATIONALES: Record<string, Partial<Record<LensId, string>>> = {
  // ── primary-law
  "primary-law-charter": { health: "Article 35 guarantees a right to preventive healthcare and medical treatment across EU law" },
  "primary-law-euratom": { security: "governs nuclear safety standards and cooperation underpinning member states' energy supply security" },
  "primary-law-iia-better-law-making-2016": { competitiveness: "mandates impact assessments that screen new EU rules for unnecessary business compliance burden" },
  "primary-law-better-regulation-communication": { competitiveness: "commits the Commission to cutting cumulative red tape and administrative costs on firms" },
  "primary-law-better-regulation-guidelines": { competitiveness: "requires quantified cost-benefit analysis of SME and competitiveness impacts before new rules" },
  "primary-law-better-regulation-toolbox": { competitiveness: "supplies checklists forcing drafters to quantify compliance costs imposed on businesses" },
  // ── climate-energy
  "climate-energy-climate-law": { climate: "legally binds the EU to climate neutrality by 2050 and a 55% 2030 cut" },
  "climate-energy-ets-directive": { climate: "caps and progressively cuts allowances covering power, heavy industry and aviation emissions", competitiveness: "sets the carbon price EU industry pays, shaping production costs versus non-EU rivals" },
  "climate-energy-msr": { climate: "withdraws surplus allowances from the market to keep the carbon price effective for abatement", competitiveness: "stabilises carbon-price volatility that industry relies on for long-term investment planning" },
  "climate-energy-ets2": { climate: "puts a carbon price on fuels for heating and driving, cutting buildings and transport emissions", competitiveness: "raises fuel costs for households and hauliers, affecting transport and construction sector expenses" },
  "climate-energy-effort-sharing-regulation": { climate: "sets binding annual national caps on transport, buildings, agriculture and waste emissions" },
  "climate-energy-lulucf-regulation": { climate: "requires forestry and land-use carbon sinks to offset residual national emissions" },
  "climate-energy-cbam": { climate: "prices embedded carbon in imported steel, cement and fertiliser to prevent carbon leakage abroad", competitiveness: "levels the playing field for EU manufacturers against carbon-unpriced foreign competitors" },
  "climate-energy-red3": { climate: "mandates a 42.5% renewable share, displacing fossil combustion emissions", competitiveness: "drives investment in EU solar, wind and grid manufacturing supply chains", security: "cuts reliance on imported fossil fuels by expanding domestic renewable generation" },
  "climate-energy-eed-recast": { climate: "mandates binding EU-wide energy savings, cutting overall demand-side emissions", competitiveness: "lowers industrial energy bills through mandatory efficiency and public-sector measures", security: "cuts overall energy demand, reducing exposure to volatile imported fuel supplies" },
  "climate-energy-epbd-recast": { climate: "phases out fossil-fuel boilers, cutting the building sector's heating emissions", competitiveness: "creates demand for EU renovation, insulation and heat-pump manufacturing industries", security: "reduces gas-fired heating demand, lowering dependence on imported gas" },
  "climate-energy-governance": { climate: "tracks member states' National Energy and Climate Plans against binding EU targets" },
  "climate-energy-methane": { climate: "requires measurement and cuts of potent methane emissions from oil, gas and coal", health: "cuts methane-driven ground-level ozone formation that damages respiratory health" },
  "climate-energy-scf": { climate: "cushions ETS2 carbon-cost impacts to sustain political support for the new fuels carbon price" },
  "climate-energy-electricity-regulation": { climate: "sets market rules enabling large-scale grid integration of variable renewable generation", competitiveness: "enables cross-border electricity trading that lowers wholesale prices for industry", security: "mandates capacity mechanisms ensuring supply adequacy during demand peaks" },
  "climate-energy-electricity-directive": { climate: "underpins retail market rules needed for consumer uptake of renewable electricity tariffs", competitiveness: "harmonises distribution-system access, enabling single-market competition among suppliers", security: "sets supply-continuity and switching rules protecting consumers from retail disruption" },
  "climate-energy-hydrogen-gas-directive": { climate: "unbundles gas infrastructure to enable third-party access for low-carbon hydrogen networks", competitiveness: "opens pipeline access to competitors, lowering barriers for hydrogen market entrants", security: "diversifies gas supply routes by integrating decarbonised gas into existing networks" },
  "climate-energy-hydrogen-gas-regulation": { climate: "sets tariff rules enabling cross-border trade in hydrogen and decarbonised gas", competitiveness: "standardises technical rules, lowering barriers to cross-border infrastructure investment", security: "coordinates cross-border network planning to secure hydrogen and gas supply routes" },
  "climate-energy-green-deal": { climate: "launches the EU's overarching strategy to reach climate neutrality by 2050", competitiveness: "frames a green-growth strategy to sustain EU industrial competitiveness through the transition", health: "links decarbonisation to a zero-pollution ambition protecting public health" },
  "climate-energy-fit-for-55": { climate: "bundles the legislative package delivering the binding 55% 2030 emissions cut", competitiveness: "packages carbon-pricing and industrial measures that reshape EU firms' transition costs" },
  "climate-energy-2040-target": { climate: "recommends a 90% net emissions cut anchoring EU ambition beyond 2030", competitiveness: "signals the long-term investment horizon industry needs for decarbonisation planning" },
  "climate-energy-repowereu": { climate: "accelerates renewables and savings measures that cut fossil fuel combustion emissions", competitiveness: "mobilises investment in EU energy infrastructure and clean-tech manufacturing capacity", security: "ends EU dependence on Russian fossil fuels through diversification and savings" },
  "climate-energy-paris-decision": { climate: "formally commits the EU to Paris Agreement temperature and mitigation goals under UNFCCC" },
  "climate-energy-cbam-implementing-reg": { climate: "operationalises reporting of embedded emissions during CBAM's pre-2026 transitional phase", competitiveness: "sets compliance obligations importers must meet before carbon charges apply in 2026" },
  "climate-energy-red-rfnbo-delegated-act": { climate: "sets additionality criteria ensuring hydrogen counted as renewable displaces fossil generation", competitiveness: "gives investors legal certainty needed to scale EU renewable hydrogen production", security: "enables domestic renewable hydrogen production to substitute imported fossil fuels" },
  "climate-energy-2030-target-plan-ia": { climate: "quantifies emissions pathways and economic costs behind the 55% 2030 target" },
  "climate-energy-2040-target-ia": { climate: "models emissions trajectories underpinning the proposed 90% 2040 target", competitiveness: "estimates industrial costs and competitiveness impacts of the 2040 target options" },
  "climate-energy-energy-taxation-directive": { climate: "sets minimum energy tax rates that shape fossil fuel consumption incentives", competitiveness: "harmonises tax floors affecting relative energy costs across member state industries" },
  "climate-energy-fgas-regulation": { climate: "phases down high-global-warming-potential F-gases used in refrigeration and heat pumps" },
  "climate-energy-ccs-directive": { climate: "sets a safety framework permitting geological CO2 storage to cut industrial emissions", competitiveness: "provides legal certainty enabling private investment in EU carbon-storage infrastructure" },
  "climate-energy-industrial-carbon-management-strategy": { climate: "scales carbon capture needed to cut emissions from hard-to-abate industrial processes", competitiveness: "builds CO2 transport and storage infrastructure supporting industrial decarbonisation investment" },
  "climate-energy-eu-adaptation-strategy": { climate: "builds resilience of infrastructure and ecosystems to unavoidable climate-change impacts" },
  // ── environment
  "environment-nature-restoration-regulation": { climate: "restores wetlands, forests and peatlands that act as carbon sinks" },
  "environment-water-framework-directive": { climate: "builds water ecosystem resilience against climate-driven droughts and flooding", health: "ensures good chemical status of drinking water sources and bathing waters" },
  "environment-urban-wastewater-directive": { climate: "pushes treatment plants toward energy neutrality, cutting sector emissions", health: "mandates micropollutant removal protecting drinking water and public health" },
  "environment-air-quality-directive": { climate: "aligns pollutant controls with measures that also cut CO2 from combustion sources", health: "tightens PM2.5 and NO2 limits that cause respiratory and cardiovascular disease" },
  "environment-industrial-emissions-directive": { competitiveness: "sets best-available-techniques permitting costs for industrial operators", health: "curbs pollutant releases from large industrial and farming installations harming residents" },
  "environment-industrial-emissions-directive-revision": { competitiveness: "imposes new permitting compliance costs on battery and mining facilities", health: "extends permitting to livestock farms and mining, limiting pollution exposure nearby" },
  "environment-reach-regulation": { competitiveness: "imposes registration and authorisation costs on chemical manufacturers and downstream users", health: "requires risk assessment of chemicals to prevent toxic exposure to consumers" },
  "environment-waste-framework-directive": { climate: "cuts landfill methane and incineration emissions by prioritising prevention and recycling", competitiveness: "sets recycling targets shaping costs and markets for the waste management sector" },
  "environment-packaging-waste-regulation": { climate: "cuts material-production emissions by curbing packaging waste and overpackaging", competitiveness: "mandates recyclability and reuse targets reshaping packaging manufacturers' product design" },
  "environment-ecodesign-espr-regulation": { climate: "extends product lifespans, cutting emissions from manufacturing and resource extraction", competitiveness: "sets durability and repairability requirements reshaping product design across EU industry" },
  "environment-batteries-regulation": { climate: "mandates carbon-footprint disclosure driving lower-emission battery production", competitiveness: "sets recycled-content rules shaping EU battery manufacturing supply chains", security: "reduces reliance on imported raw materials through recycling and due-diligence rules" },
  "environment-deforestation-regulation": { climate: "bans imports linked to deforestation, protecting carbon-absorbing forests", competitiveness: "imposes due-diligence compliance costs on traders of cattle, soy and timber" },
  "environment-eia-directive": { competitiveness: "requires environmental assessment before approval, affecting permitting timelines for developers" },
  "environment-environmental-liability-directive": { health: "makes polluters financially liable for remedying environmental damage that harms residents" },
  "environment-8eap-decision": { climate: "sets EU environmental priorities including climate mitigation monitoring through 2030", health: "frames zero-pollution monitoring targets aimed at protecting public health" },
  "environment-circular-economy-action-plan": { climate: "cuts material-extraction and production emissions through circular resource use", competitiveness: "sets strategy shaping resource-efficient product design and secondary-material markets" },
  "environment-zero-pollution-action-plan": { climate: "links pollution-reduction measures with emissions cuts across sectors", health: "targets near-zero air, water and soil pollution harm to human health by 2050" },
  "environment-biodiversity-strategy-2030": { climate: "protects ecosystems that sequester carbon and buffer climate-change impacts", health: "safeguards ecosystem services like clean water and pest and disease regulation" },
  "environment-nature-restoration-impact-assessment": { climate: "evaluates costs and benefits of binding ecosystem restoration carbon-sink targets" },
  "environment-marine-strategy-framework-directive": { climate: "maintains marine ecosystems that sequester carbon and buffer coastal climate impacts", health: "protects marine water quality underpinning seafood safety and coastal public health" },
  // ── trade
  "trade-anti-dumping": { competitiveness: "imposes duties countering dumped imports that undercut EU producers' prices" },
  "trade-anti-subsidy": { competitiveness: "levies countervailing duties offsetting foreign subsidies that distort EU market competition" },
  "trade-enforcement": { competitiveness: "suspends trade concessions to enforce rulings protecting EU exporters' market access", security: "gives the EU a retaliation tool against partners violating binding trade rulings" },
  "trade-fdi-screening": { competitiveness: "protects EU firms' strategic assets from acquisition-driven loss of control", security: "screens foreign investment in critical infrastructure and technology for public-order risks" },
  "trade-foreign-subsidies": { competitiveness: "lets Commission unwind subsidised bids and acquisitions distorting the single market" },
  "trade-ipi": { competitiveness: "restricts procurement access for countries blocking EU firms from their own tenders" },
  "trade-aci": { competitiveness: "shields EU businesses from trade restrictions imposed as political pressure", security: "authorises countermeasures against economic coercion targeting the Union or a member state" },
  "trade-dual-use": { security: "controls exports of items usable in weapons proliferation or military programmes" },
  "trade-conflict-minerals": { security: "requires due diligence cutting mineral supply chains that fund armed conflict" },
  "trade-forced-labour": { competitiveness: "levels the playing field against imports produced with exploitative labour costs", security: "bans market access for goods tied to forced-labour supply chains" },
  "trade-ceta": { competitiveness: "removes most EU-Canada tariffs, widening market access for exporters" },
  "trade-eu-uk-tca": { competitiveness: "sets tariff-free goods trade terms governing the EU's largest bilateral relationship", security: "establishes law-enforcement and security cooperation frameworks with the UK post-Brexit" },
  "trade-wto": { competitiveness: "locks EU membership into multilateral rules underpinning global market access" },
  "trade-policy-review": { climate: "commits trade policy to supporting sustainability and Paris-aligned objectives", competitiveness: "sets strategy balancing open markets with defending EU industry assertively" },
  "trade-global-gateway": { climate: "funds clean-energy and low-carbon infrastructure investment in partner countries", competitiveness: "opens infrastructure markets abroad for EU firms and technology", security: "counters reliance on rival powers' infrastructure financing in strategic regions" },
  "trade-economic-security": { competitiveness: "targets economic dependencies that expose EU industry to coercion or disruption", security: "frames de-risking of dependencies the EU treats as security vulnerabilities" },
  "trade-fdi-screening-impl": { security: "standardises forms enabling cross-border cooperation on FDI security screening cases" },
  "trade-foreign-subsidies-impl": { competitiveness: "sets procedural deadlines and thresholds for foreign-subsidy market investigations" },
  "trade-foreign-subsidies-ia": { competitiveness: "quantifies market distortion from foreign subsidies justifying the regulation's remedies" },
  // ── competitiveness
  "competitiveness-chips-act": { competitiveness: "funds fabs and design capacity to grow EU semiconductor manufacturing share", security: "reduces dependence on foreign chip supply critical to defence and infrastructure" },
  "competitiveness-nzia": { climate: "targets 40% domestic production capacity for net-zero technologies by 2030", competitiveness: "streamlines permitting to scale EU manufacturing of solar, wind and battery tech" },
  "competitiveness-nzia-impact-assessment": { climate: "assesses options for scaling clean-tech production needed for decarbonisation", competitiveness: "weighs manufacturing-capacity costs and benefits behind the Act's production targets" },
  "competitiveness-crma": { climate: "secures materials like lithium and cobalt needed for the energy transition", competitiveness: "sets extraction and processing targets reducing EU reliance on single suppliers", security: "diversifies critical raw material sourcing away from concentrated foreign suppliers" },
  "competitiveness-crma-impact-assessment": { climate: "examines material needs for scaling clean-energy technology deployment", competitiveness: "assesses supply-risk options behind raw-material sourcing and processing targets", security: "evaluates dependency risks from concentrated critical raw material supply chains" },
  "competitiveness-imera": { competitiveness: "creates emergency toolbox keeping goods and services flowing in single-market crises", security: "lets the EU fast-track responses to supply-chain shocks and shortages" },
  "competitiveness-late-payment-directive": { competitiveness: "cuts cash-flow strain on SMEs by penalising persistently late-paying business partners" },
  "competitiveness-services-directive": { competitiveness: "removes licensing barriers letting service providers establish and trade across borders" },
  "competitiveness-transparency-directive": { competitiveness: "requires notification of draft technical rules preventing fragmented national markets" },
  "competitiveness-reg-1-2003": { competitiveness: "empowers enforcement against cartels and dominance abuse distorting EU markets" },
  "competitiveness-merger-regulation": { competitiveness: "requires Commission clearance blocking mergers that would harm market competition" },
  "competitiveness-merger-implementing-regulation": { competitiveness: "sets notification deadlines ensuring predictable, efficient merger review procedures" },
  "competitiveness-gber": { climate: "exempts renewable and energy-efficiency aid from prior Commission clearance", competitiveness: "exempts categories of state aid from approval, speeding investment support" },
  "competitiveness-ceeag": { climate: "sets conditions letting states subsidise renewable energy and decarbonisation projects", competitiveness: "bounds green subsidies to prevent distortive competition between member states" },
  "competitiveness-horizon-europe": { climate: "finances clean-tech research supporting the EU's decarbonisation pathway", competitiveness: "funds R&I projects strengthening EU industrial and technological competitiveness" },
  "competitiveness-investeu": { climate: "channels guaranteed investment toward renewable energy and green infrastructure projects", competitiveness: "guarantees mobilise private capital for strategic industrial investment projects" },
  "competitiveness-step": { climate: "prioritises funding for clean technology manufacturing capacity", competitiveness: "redirects EU funds to keep critical tech production based in Europe", security: "curbs reliance on foreign suppliers for critical digital and biotech inputs" },
  "competitiveness-industrial-strategy-2020": { competitiveness: "sets vision guiding industry through green and digital transformation" },
  "competitiveness-green-deal-industrial-plan": { climate: "accelerates clean-tech manufacturing capacity needed for the net-zero transition", competitiveness: "proposes faster permitting and funding to scale net-zero industry" },
  "competitiveness-competitiveness-compass": { competitiveness: "sets 2025 roadmap closing the EU's productivity gap with rivals" },
  "competitiveness-clean-industrial-deal": { climate: "ties decarbonisation measures directly to industrial demand and investment", competitiveness: "links lower energy costs and investment to industrial competitiveness" },
  "competitiveness-draghi-report": { competitiveness: "diagnoses investment and energy-cost gaps holding back EU productivity", security: "flags strategic dependencies on rivals as risks to EU autonomy" },
  // ── health
  "health-eu4health": { security: "builds EU crisis preparedness capacity to respond to future health emergencies", health: "funds strengthening of national health systems and disease prevention programmes for 2021-2027" },
  "health-cbht": { security: "coordinates joint EU early-warning and response systems against health emergencies", health: "mandates EU-level surveillance of cross-border disease threats to protect public health" },
  "health-ecdc": { security: "strengthens EU-level threat assessment and outbreak response coordination", health: "expands disease surveillance and monitoring capacity across member states" },
  "health-hera": { security: "secures supply of critical medical countermeasures against biological emergencies", health: "coordinates development and stockpiling of vaccines and medical countermeasures" },
  "health-ehds": { competitiveness: "creates a single market for health data reuse fuelling digital health innovation", health: "enables cross-border access to electronic health records improving care coordination" },
  "health-mdr": { competitiveness: "harmonises market-access rules enabling single-market trade in medical devices", health: "sets safety and performance requirements protecting patients using medical devices" },
  "health-ivdr": { competitiveness: "sets EU-wide conformity assessment enabling single-market access for diagnostics makers", health: "ensures diagnostic tests meet safety and performance standards before reaching patients" },
  "health-medicinal-products-dir": { competitiveness: "harmonises manufacturing and labelling rules enabling EU-wide pharmaceutical market access", health: "governs authorisation and monitoring of medicines to ensure patient safety" },
  "health-pharma-reform-proposal": { competitiveness: "seeks to boost pharmaceutical innovation and strengthen EU supply security", health: "aims to improve patient access to medicines across member states" },
  "health-clinical-trials": { competitiveness: "streamlines cross-border trial approval reducing costs for drug developers", health: "harmonises trial oversight protecting participant safety and data reliability" },
  "health-tobacco-products": { health: "restricts tobacco manufacturing and sale to cut smoking-related disease" },
  "health-general-food-law": { health: "sets traceability and safety principles preventing unsafe food reaching consumers" },
  "health-official-controls": { health: "mandates inspections verifying compliance with food and feed safety rules" },
  "health-hta": { competitiveness: "reduces duplicative national assessments cutting costs for technology developers", health: "creates joint clinical assessments speeding patient access to new health technologies" },
  "health-cancer-plan": { health: "sets EU strategy on cancer prevention, screening and treatment across the disease pathway" },
  "health-pharma-strategy": { competitiveness: "seeks to strengthen EU pharmaceutical innovation capacity and cut import dependency", health: "aims to ensure affordable, timely patient access to needed medicines" },
  "health-amr-recommendation": { security: "coordinates One Health surveillance guarding against resistant-pathogen outbreaks", health: "recommends measures curbing antimicrobial resistance that threatens treatable infections" },
  "health-eu4health-ia": { health: "assesses policy options for strengthening EU health system funding" },
  "health-mdr-implementing": { health: "sets technical specifications ensuring safe reprocessing of single-use medical devices" },
  // ── security
  "security-security-union-strategy": { security: "sets 2020-2025 EU priorities for countering terrorism, organised crime and cybercrime" },
  "security-strategic-compass": { security: "sets EU military ambition levels and capability targets through 2030" },
  "security-white-paper-defence": { competitiveness: "aims to build EU defence-industrial readiness and production capacity", security: "blueprints scaling up EU defence spending and capabilities by 2030" },
  "security-edf": { competitiveness: "builds cross-border defence-industrial cooperation among member states' firms", security: "co-finances collaborative defence research and capability development projects" },
  "security-edf-ia": { competitiveness: "assesses expected industrial and economic effects of the EDF proposal", security: "analyses options for establishing an EU collaborative defence capability fund" },
  "security-asap": { competitiveness: "scales up EU ammunition manufacturing capacity and supply chains", security: "boosts ammunition and missile production to resupply Ukraine and member states" },
  "security-edirpa": { competitiveness: "coordinates member-state defence spending to build industrial economies of scale", security: "incentivises joint procurement strengthening EU defence industry cooperation" },
  "security-ukraine-facility": { security: "channels multiannual EU funding for Ukraine's recovery, reconstruction and reform" },
  "security-sanctions-russia": { security: "imposes economic restrictive measures on Russia over its aggression against Ukraine" },
  "security-sanctions-decision": { security: "sets out CFSP restrictive measures against Russia later implemented by regulation" },
  "security-cyber-solidarity": { competitiveness: "funds shared cybersecurity infrastructure and services across the single market", security: "builds EU capacity to detect and respond to large-scale cyber incidents" },
  "security-europol": { security: "establishes Europol's mandate and data powers supporting cross-border law enforcement cooperation" },
  "security-frontex": { security: "strengthens the European Border and Coast Guard's standing corps and operational powers" },
  "security-sbc": { security: "codifies rules for controlling the EU's internal and external Schengen borders" },
  "security-sbc-2024-revision": { security: "updates border-check rules for instrumentalised migration and health-related crises" },
  "security-migration-pact-communication": { security: "launches the reform package on asylum responsibility allocation and border management" },
  "security-amm": { security: "reforms responsibility allocation and mandatory solidarity for asylum among member states" },
  "security-screening": { security: "mandates pre-entry identity and security screening of irregular migrants at external borders" },
  "security-firearms": { security: "harmonises rules on civilian firearms to curb illicit trafficking across the EU" },
  "security-cer": { competitiveness: "sets common resilience standards reducing disruption risk for cross-border operators", security: "requires resilience measures for critical infrastructure against physical and hybrid threats" },
  "security-safe-regulation": { competitiveness: "provides EU loans building scale in the European defence-industrial base", security: "finances joint defence-industrial procurement and capability scale-up through 2030" },
  // ── digital
  "digital-gdpr": { competitiveness: "harmonises data-protection compliance costs for firms across the single market", security: "sets binding rules protecting personal data from breaches and misuse" },
  "digital-eprivacy-directive": { security: "regulates cookies and tracking to protect confidentiality of electronic communications" },
  "digital-dsa": { competitiveness: "sets uniform due-diligence rules for platforms operating across the single market", security: "imposes obligations on platforms to curb illegal content and systemic risks" },
  "digital-dma": { competitiveness: "keeps gatekeeper-dominated digital markets contestable for smaller competitors" },
  "digital-ai-act": { competitiveness: "creates a single EU framework for AI development reducing regulatory fragmentation", security: "imposes risk-based safeguards on high-risk AI systems in safety-critical uses" },
  "digital-data-act": { competitiveness: "opens access to connected-device data spurring new data-driven business models" },
  "digital-dga": { competitiveness: "enables voluntary data-sharing mechanisms fostering data-driven innovation across sectors" },
  "digital-nis2": { competitiveness: "harmonises cyber-resilience obligations reducing compliance fragmentation across member states", security: "sets cybersecurity risk-management and incident-reporting duties for essential entities" },
  "digital-cra": { competitiveness: "sets a common product-security baseline enabling single-market access for manufacturers", security: "mandates cybersecurity requirements for connected products sold in the EU" },
  "digital-cybersecurity-act": { security: "establishes ENISA's mandate and an EU-wide ICT certification scheme" },
  "digital-eidas2": { competitiveness: "enables interoperable digital identity and trust services across the single market", security: "creates a trusted EU Digital Identity Wallet with secure authentication standards" },
  "digital-decade-decision": { competitiveness: "sets EU-wide 2030 targets for digital skills, infrastructure and business uptake" },
  "digital-open-data-directive": { competitiveness: "promotes reuse of public-sector data fuelling new digital services and firms" },
  "digital-platform-work-directive": { competitiveness: "regulates algorithmic management shaping compliance costs for platform-based businesses" },
  "digital-gigabit-infrastructure-act": { competitiveness: "speeds deployment of gigabit networks underpinning digital-economy infrastructure" },
  "digital-shaping-digital-future": { competitiveness: "sets the Commission's overarching strategy driving Europe's digital-economy transformation" },
  "digital-2030-digital-compass": { competitiveness: "outlines EU pillars and targets guiding digital industrial transformation to 2030" },
  "digital-ai-continent-action-plan": { competitiveness: "boosts EU AI computing infrastructure and data access to scale industrial capacity" },
  "digital-dsa-transparency-delegated-act": { competitiveness: "standardises platform transparency reporting reducing compliance uncertainty across the market" },
  "digital-nis2-implementing-regulation": { security: "sets detailed technical cybersecurity and incident-reporting requirements for specific digital providers" },
  "digital-ai-act-gpai-code-of-practice": { competitiveness: "helps AI model providers demonstrate compliance easing market access under the AI Act", security: "guides providers on mitigating systemic risks from general-purpose AI models" },
  "digital-ai-act-impact-assessment": { competitiveness: "assesses economic costs and benefits of policy options for regulating AI" },
  // ── transport
  "transport-co2-cars-vans": { climate: "sets fleet-wide CO2 targets forcing manufacturers to cut vehicle emissions", competitiveness: "drives EV manufacturing investment shaping automakers' product strategy" },
  "transport-co2-cars-vans-2023": { climate: "mandates a 100% CO2 cut for new cars and vans by 2035", competitiveness: "sets a binding deadline steering EU automakers' electrification investment" },
  "transport-co2-cars-ia": { climate: "analyses options for tightening post-2025 vehicle CO2 targets", competitiveness: "weighs industrial and cost impacts of stricter car CO2 rules" },
  "transport-co2-cars-reporting-ir": { climate: "standardises manufacturer CO2 data reporting enabling accurate emissions tracking" },
  "transport-hdv-co2": { climate: "strengthens CO2 targets cutting emissions from trucks, buses and trailers", competitiveness: "pushes EU truckmakers toward zero-emission vehicle development" },
  "transport-afir": { climate: "mandates recharging infrastructure enabling zero-emission vehicle uptake", competitiveness: "ensures consistent charging networks supporting EV market growth across states", security: "builds resilient alternative-fuel infrastructure along strategic TEN-T corridors" },
  "transport-refueleu-aviation": { climate: "mandates rising sustainable aviation fuel shares cutting aviation emissions", competitiveness: "creates demand certainty spurring EU sustainable fuel production capacity" },
  "transport-fueleu-maritime": { climate: "caps greenhouse gas intensity of shipping fuel used at EU ports", competitiveness: "drives investment in low-carbon marine fuel supply chains" },
  "transport-tent": { climate: "prioritises rail and low-carbon modes across the network", competitiveness: "sets deadlines completing core transport corridors boosting single-market connectivity", security: "incorporates military mobility requirements into network design" },
  "transport-eurovignette": { climate: "lets tolls reflect CO2 emissions incentivising cleaner heavy vehicles", competitiveness: "harmonises road-charging rules affecting freight operators' costs" },
  "transport-its": { competitiveness: "creates common framework for deploying intelligent transport systems across member states" },
  "transport-ses": { climate: "reduces flight inefficiencies cutting fuel burn and emissions", competitiveness: "streamlines air navigation services cutting costs and delays for airlines", security: "ensures resilient, coordinated air traffic management across borders" },
  "transport-rail-recast": { competitiveness: "opens rail network access enabling cross-border competition and single-market integration" },
  "transport-rail-market-pillar": { competitiveness: "opens domestic rail passenger markets to competition boosting sector efficiency" },
  "transport-weights-dimensions": { climate: "allows low-emission vehicle features reducing freight transport emissions", competitiveness: "updates truck weight limits enabling adoption of aerodynamic efficiency features" },
  "transport-euro7": { climate: "complements CO2 rules by limiting non-CO2 vehicle emissions", competitiveness: "sets battery durability rules shaping vehicle manufacturers' design standards", health: "sets tailpipe pollutant limits reducing air pollution harmful to public health" },
  "transport-driving-licence": { competitiveness: "harmonises licence categories enabling cross-border labour mobility for drivers" },
  "transport-smart-mobility-strategy": { climate: "sets milestones for decarbonising EU transport by 2050", competitiveness: "charts roadmap for digital and resilient transport sector growth" },
  "transport-automotive-action-plan": { climate: "aligns industrial support with the sector's transition to zero-emission vehicles", competitiveness: "outlines support measures sustaining EU automotive industry competitiveness" },
  // ── agriculture-food
  "agriculture-food-cap-strategic-plans": { climate: "lets states fund environmental and climate schemes within national CAP plans", competitiveness: "sustains farm income support underpinning EU agricultural production capacity" },
  "agriculture-food-cap-horizontal": { competitiveness: "governs financing and auditing rules ensuring reliable CAP payment flows to farmers" },
  "agriculture-food-cmo": { competitiveness: "sets market organisation and trade rules underpinning EU agricultural markets" },
  "agriculture-food-organic": { climate: "promotes farming practices that reduce synthetic input use and emissions", health: "sets labelling rules ensuring consumer trust in organic food claims" },
  "agriculture-food-pesticides-sud": { climate: "promotes integrated pest management reducing chemical-intensive farming's footprint", health: "requires training and equipment checks cutting pesticide exposure risks" },
  "agriculture-food-sur-proposal-withdrawn": { climate: "would have set binding EU-wide pesticide-reduction targets curbing agri-chemical pollution", competitiveness: "withdrawal followed farmer opposition over compliance costs and yield impacts", health: "would have cut pesticide exposure risks to farmers and consumers" },
  "agriculture-food-fertilising-products": { climate: "enables recycled and organic-based fertilisers cutting reliance on emissions-intensive synthetic inputs", competitiveness: "creates single EU market enabling cross-border trade in fertiliser products", health: "sets safety standards limiting contaminants in fertilisers reaching soil and food" },
  "agriculture-food-cfp": { climate: "manages fish stocks sustainably safeguarding marine ecosystems from overfishing", competitiveness: "sets quotas sustaining the economic viability of the EU fishing fleet", security: "secures long-term food and resource supply from EU fishing waters" },
  "agriculture-food-emfaf": { climate: "funds transition toward sustainable, low-impact fisheries and aquaculture practices", competitiveness: "finances investment supporting the EU's blue economy and fleet modernisation" },
  "agriculture-food-animal-health-law": { security: "strengthens EU-wide prevention capacity against cross-border animal disease outbreaks", health: "consolidates rules for detecting and controlling zoonotic diseases in animals" },
  "agriculture-food-plant-health": { competitiveness: "protects crop yields and trade by preventing plant disease outbreaks", security: "sets protective measures against pests entering or spreading within EU borders", health: "guards against pest and disease spread that can affect food safety" },
  "agriculture-food-ngt-proposal": { climate: "enables climate-resilient, lower-input crop varieties through gene-editing techniques", competitiveness: "eases regulatory burden for gene-edited crop developers boosting innovation", health: "requires safety assessment before gene-edited plant products reach consumers" },
  "agriculture-food-farm-to-fork": { climate: "sets targets cutting fertiliser, pesticide use and farming emissions", competitiveness: "seeks to reposition EU food producers as global sustainability leaders", health: "aims for a healthier food system reducing diet-related disease risk" },
  "agriculture-food-vision-agriculture-food": { climate: "supports farmers' transition toward more sustainable production methods", competitiveness: "outlines plan to boost farm incomes and generational renewal", security: "aims to secure long-term EU food production capacity" },
  "agriculture-food-strategic-dialogue": { climate: "reflects agreement on accelerating agriculture's sustainability transition", competitiveness: "records stakeholder consensus on strengthening farmer incomes and market position" },
  "agriculture-food-cap-ia-swd": { climate: "assesses environmental and climate impacts of proposed CAP reform options", competitiveness: "evaluates income-support and market impacts of CAP reform options on farmers" },
  "agriculture-food-fisheries-control-regulation": { climate: "enforces catch data reporting supporting sustainable stock management", competitiveness: "ensures a level playing field for fleets through consistent enforcement", security: "sets inspection systems ensuring compliance with fisheries quotas and rules" },
  // ── economy-social
  "economy-social-sgp-preventive": { competitiveness: "sets fiscal adjustment paths shaping states' capacity for productive investment" },
  "economy-social-sgp-corrective": { competitiveness: "clarifies deficit-procedure rules affecting fiscal space for investment and growth" },
  "economy-social-budgetary-frameworks-dir": { competitiveness: "strengthens national budget rules underpinning credible fiscal surveillance" },
  "economy-social-rrf": { climate: "earmarks 37% of recovery spending for green transition investments", competitiveness: "funds reforms and investment restoring post-pandemic growth capacity" },
  "economy-social-cpr": { climate: "governs Just Transition Fund and cohesion spending on green transition", competitiveness: "sets shared rules for regional investment funds worth hundreds of billions" },
  "economy-social-taxonomy": { climate: "defines criteria for classifying activities as environmentally sustainable", competitiveness: "channels investment capital toward green sectors via standardised classification" },
  "economy-social-sfdr": { climate: "mandates disclosure of sustainability risks steering capital toward green finance", competitiveness: "sets disclosure standards shaping competition among financial market participants" },
  "economy-social-csrd": { climate: "mandates standardised emissions and environmental reporting for large companies", competitiveness: "harmonises sustainability reporting reducing compliance divergence across markets" },
  "economy-social-csddd": { climate: "requires companies to address environmental harms across value chains", competitiveness: "imposes due-diligence costs affecting large companies' compliance burden" },
  "economy-social-green-bond": { climate: "sets strict use-of-proceeds standards for bonds funding green projects", competitiveness: "creates a trusted label helping issuers access green capital markets" },
  "economy-social-omnibus-i": { climate: "simplifies sustainability rules while preserving core climate reporting obligations", competitiveness: "cuts reporting and due-diligence burdens to ease compliance costs for firms" },
  "economy-social-mica": { competitiveness: "creates licensing regime giving crypto firms EU-wide market access" },
  "economy-social-crr": { competitiveness: "sets capital rules shaping banks' cost and capacity to lend", security: "requires liquidity buffers protecting financial system stability" },
  "economy-social-crd4": { competitiveness: "governs bank authorisation rules affecting cross-border banking competition", security: "sets supervisory governance rules safeguarding banking-sector stability" },
  "economy-social-minimum-wage": { competitiveness: "sets wage-setting criteria affecting labour costs and market fairness across states" },
  "economy-social-jtf": { climate: "funds regions transitioning away from coal and carbon-intensive industry", competitiveness: "supports economic diversification in fossil-fuel-dependent regions" },
  "economy-social-sustainable-finance-strategy": { climate: "scales sustainable finance and addresses climate-related financial risks", competitiveness: "mobilises private capital toward the green and digital transition" },
  "economy-social-savings-investments-union": { competitiveness: "deepens capital markets channelling household savings into EU business investment" },
  "economy-social-taxonomy-climate-da": { climate: "sets technical screening criteria for climate-mitigation and adaptation activities", competitiveness: "gives investors precise criteria for allocating capital to green activities" },
  "economy-social-csddd-impact-assessment": { climate: "assesses due-diligence options for addressing environmental harms in value chains", competitiveness: "weighs compliance costs and benefits of due-diligence obligations for firms" },
};
