"""
EU electricity system optimization — 30-country network (PyPSA).

A full 30-bus network where each bus represents one European country
(EU-27 + Norway, Switzerland, United Kingdom). Each country hosts its
own portfolio of generator technologies (wind, solar, nuclear, hydro,
gas, coal, battery, hydrogen) with country-specific capacity factors,
technology potentials and demand. Cross-border interconnectors are
modelled as transport links with NTC capacities from ENTSO-E TYNDP 2022.

The model solves a joint capacity-expansion + dispatch LP over a small
number of representative "snapshots" (e.g. 48 h) and returns:
    - installed capacity per (country, technology)
    - total dispatch per technology
    - hourly dispatch and load time series
    - cross-border flows
    - CO2 emissions
    - levelised and marginal cost
    - shadow price of the CO2 constraint (if any)

The model is solved with the real `pypsa` library, which builds a `linopy`
problem and dispatches it to HiGHS via `highspy`. There is no fallback —
if PyPSA is not installed the service will refuse to run.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:  # pragma: no cover - optional heavy dep
    import pypsa  # type: ignore

    PYPSA_AVAILABLE = True
    PYPSA_VERSION = getattr(pypsa, "__version__", "unknown")
except Exception:  # pragma: no cover
    PYPSA_AVAILABLE = False
    PYPSA_VERSION = None

from .data_loader import (
    ProfileBundle,
    load_best_profiles,
    load_pypsa_eur_costs,
    load_pypsa_eur_network,
    pypsa_eur_costs_available,
)
from .eu_countries import (
    COUNTRIES,
    INTERCONNECTORS as COUNTRY_INTERCONNECTORS,
    ISO_INDEX,
    CountrySpec,
    country_potentials,
)


# ---------------------------------------------------------------------------
# 30-country model data (derived from eu_countries.py)
# ---------------------------------------------------------------------------

# Every country is a bus — ISO-2 codes
BUSES: List[str] = [c.iso2 for c in COUNTRIES]

# Annual electricity demand per country (TWh/yr, 2030 reference)
ANNUAL_DEMAND_TWH: Dict[str, float] = {c.iso2: c.demand_twh for c in COUNTRIES}

# Load shape multipliers for a 48-hour representative window (winter day +
# summer day, approximate EU load curve). Shifted by ±1 h longitude to
# capture timezone effects on the diurnal curve.
_BASE_LOAD_48H: List[float] = [
    0.72, 0.70, 0.69, 0.70, 0.74, 0.82, 0.92, 1.02, 1.08, 1.10, 1.09, 1.07,
    1.04, 1.02, 1.02, 1.04, 1.08, 1.12, 1.15, 1.12, 1.05, 0.95, 0.85, 0.78,
    0.75, 0.72, 0.71, 0.72, 0.76, 0.84, 0.94, 1.03, 1.06, 1.05, 1.02, 0.99,
    0.96, 0.95, 0.96, 0.99, 1.04, 1.09, 1.11, 1.08, 1.00, 0.90, 0.81, 0.74,
]


def _shift_load(base: List[float], lon: float) -> List[float]:
    """Shift a diurnal load shape by the country's longitude (timezone proxy).

    Positive longitude → earlier sunrise/peak vs UTC reference.
    Each 15° of longitude ≈ 1 hour of shift.
    """
    shift = round(lon / 15.0)
    arr = list(base)
    # Shift each 24-h block independently to preserve diurnal structure
    day1 = arr[:24]
    day2 = arr[24:48] if len(arr) >= 48 else day1[:]
    day1 = day1[-shift:] + day1[:-shift] if shift else day1
    day2 = day2[-shift:] + day2[:-shift] if shift else day2
    return day1 + day2


LOAD_SHAPE: Dict[str, List[float]] = {
    c.iso2: _shift_load(_BASE_LOAD_48H, c.lon) for c in COUNTRIES
}

# Base wind CF curve (EU-wide mean 48 h pattern). Per-country CFs are
# generated by scaling this with CountrySpec.wind_onshore_scale.
_BASE_WIND_CF_48H: List[float] = [
    0.38, 0.40, 0.42, 0.44, 0.45, 0.43, 0.40, 0.37, 0.34, 0.32, 0.30, 0.29,
    0.30, 0.31, 0.33, 0.35, 0.37, 0.39, 0.40, 0.41, 0.41, 0.40, 0.38, 0.36,
    0.34, 0.32, 0.30, 0.29, 0.29, 0.30, 0.32, 0.35, 0.37, 0.39, 0.40, 0.40,
    0.39, 0.38, 0.37, 0.36, 0.34, 0.33, 0.31, 0.30, 0.30, 0.30, 0.31, 0.32,
]


def _scale_wind_cf(base: List[float], scale: float) -> List[float]:
    """Apply a country-specific wind capacity-factor multiplier, capped at 1."""
    return [min(1.0, v * scale) for v in base]


WIND_CF: Dict[str, List[float]] = {
    c.iso2: _scale_wind_cf(_BASE_WIND_CF_48H, c.wind_onshore_scale) for c in COUNTRIES
}

WIND_OFFSHORE_CF: Dict[str, List[float]] = {
    c.iso2: _scale_wind_cf(_BASE_WIND_CF_48H, c.wind_offshore_scale)
    for c in COUNTRIES if c.coastal and c.wind_offshore_scale > 0
}


# Solar CF timeseries per country (48 h — two daylight bell curves).
# Peak CF is 0.55 × solar_scale; the Gaussian shape is shifted by longitude.
def _solar_curve(peak: float, lon: float = 0.0) -> List[float]:
    # Solar noon shifts ~1 h per 15° longitude
    noon_shift = lon / 15.0
    cf: List[float] = []
    for day in range(2):
        for hour in range(24):
            x = (hour - (13.0 + noon_shift)) / 5.0
            v = peak * math.exp(-x * x)
            cf.append(max(0.0, min(peak, v)))
    return cf


SOLAR_CF: Dict[str, List[float]] = {
    c.iso2: _solar_curve(0.55 * c.solar_scale, c.lon) for c in COUNTRIES
}

# Country-level interconnectors — from eu_countries.py (ENTSO-E NTC)
INTERCONNECTORS: List[Tuple[str, str, float]] = [
    (a, b, cap) for a, b, cap, _kind in COUNTRY_INTERCONNECTORS
]

# Pre-compute per-country technology potentials (GW)
POTENTIALS: Dict[str, Dict[str, float]] = {
    c.iso2: country_potentials(c) for c in COUNTRIES
}


@dataclass
class Technology:
    name: str
    capex_eur_per_kw: float       # overnight investment cost
    fom_eur_per_kw_yr: float      # fixed O&M
    vom_eur_per_mwh: float        # variable O&M
    fuel_eur_per_mwh: float       # fuel at input level
    efficiency: float              # electrical efficiency (fuel→elec)
    co2_t_per_mwh_fuel: float     # fuel emission factor
    lifetime_years: int
    variable: bool = False        # True = VRE, False = dispatchable
    max_cf: float = 1.0           # cap for dispatchable techs
    available: bool = True        # toggled by user assumptions
    # Per-bus potential (GW). A value of None = effectively unconstrained.
    potential_gw: Optional[Dict[str, float]] = None


def annuity(capex: float, lifetime: int, discount: float) -> float:
    if discount == 0:
        return capex / lifetime
    return capex * discount / (1.0 - (1.0 + discount) ** -lifetime)


# Maps our internal tech IDs to the canonical `technology` name used in
# PyPSA/technology-data (https://github.com/PyPSA/technology-data). When a
# real costs_YYYY.csv file is available the numbers below are overwritten
# with the peer-reviewed upstream values.
_PYPSA_EUR_TECH_NAMES: Dict[str, str] = {
    "onwind":   "onwind",
    "offwind":  "offwind-ac",
    "solar":    "solar",
    "nuclear":  "nuclear",
    "gas_ocgt": "OCGT",
    "gas_ccgt": "CCGT",
    "coal":     "coal",
    "hydro":    "hydro",
    "battery":  "battery inverter",
    "h2":       "OCGT",  # hydrogen-ready turbine proxied via OCGT capex
}


def _apply_real_costs(techs: Dict[str, Technology], year: int = 2030) -> Optional[str]:
    """Override the baked-in costs with real PyPSA-Eur technology-data values.

    Returns the data-source string if the overlay was applied, else None.
    """
    real = load_pypsa_eur_costs(year)
    if not real:
        return None
    for tid, upstream in _PYPSA_EUR_TECH_NAMES.items():
        if tid not in techs or upstream not in real:
            continue
        params = real[upstream]
        t = techs[tid]
        if "investment" in params:
            # technology-data reports investment in EUR/kW
            t.capex_eur_per_kw = float(params["investment"])
        if "FOM" in params:
            # FOM is % of investment per year → convert to EUR/kW/yr
            t.fom_eur_per_kw_yr = float(params["FOM"]) / 100.0 * t.capex_eur_per_kw
        if "VOM" in params:
            t.vom_eur_per_mwh = float(params["VOM"])
        if "lifetime" in params:
            t.lifetime_years = int(params["lifetime"])
        if "efficiency" in params:
            t.efficiency = float(params["efficiency"])
        if "fuel" in params:
            t.fuel_eur_per_mwh = float(params["fuel"])
        if "CO2 intensity" in params:
            t.co2_t_per_mwh_fuel = float(params["CO2 intensity"])
    return f"PyPSA-Eur technology-data v0.14.0 (costs_{year}.csv)"


def build_technologies(assumptions: "Assumptions") -> Tuple[Dict[str, Technology], Optional[str]]:
    """Build the technology portfolio.

    Returns (techs, costs_source). ``costs_source`` is a provenance string
    (non-None if real PyPSA-Eur technology-data costs were applied).
    """
    techs: Dict[str, Technology] = {
        "onwind":   Technology("Onshore Wind", 1100,  25, 1, 0,    1.0,  0.0, 25, variable=True),
        "offwind":  Technology("Offshore Wind",2400,  80, 2, 0,    1.0,  0.0, 25, variable=True),
        "solar":    Technology("Solar PV",      600,  15, 0, 0,    1.0,  0.0, 25, variable=True),
        "nuclear":  Technology("Nuclear",      6500, 110, 3, 6,    0.33, 0.0, 60, max_cf=0.90),
        "gas_ocgt": Technology("Gas OCGT",      500,  10, 3, 28,   0.40, 0.20, 25),
        "gas_ccgt": Technology("Gas CCGT",      900,  15, 3, 28,   0.60, 0.20, 25),
        "coal":     Technology("Coal",         1600,  30, 4, 14,   0.42, 0.34, 35),
        "hydro":    Technology("Hydro Reservoir",2200, 40, 1, 0,  1.0,  0.0, 80, max_cf=0.40),
        "battery":  Technology("Battery (4h)", 1400,  15, 0, 0,    0.88, 0.0, 15, max_cf=0.25),
        "h2":       Technology("Hydrogen Turbine",800, 15, 4, 90,  0.45, 0.0, 25),
    }
    # Overlay with real PyPSA-Eur technology-data values if available
    costs_source = _apply_real_costs(techs, year=assumptions.year)

    # Build per-country potentials from eu_countries.country_potentials()
    for tid in techs:
        pot: Dict[str, float] = {}
        for iso2 in BUSES:
            cpot = POTENTIALS.get(iso2, {})
            pot[iso2] = cpot.get(tid, 0.0)
        techs[tid].potential_gw = pot

    if not assumptions.allow_nuclear:
        techs["nuclear"].available = False
    if assumptions.phase_out_coal:
        techs["coal"].available = False
    if not assumptions.allow_storage:
        techs["battery"].available = False
    if not assumptions.allow_hydrogen:
        techs["h2"].available = False
    return techs, costs_source


# ---------------------------------------------------------------------------
# Inputs
# ---------------------------------------------------------------------------

@dataclass
class Assumptions:
    co2_price_eur_per_t: float = 100.0
    renewable_share_target: float = 0.0        # 0..1, hard lower bound on VRE+hydro
    co2_cap_mt: Optional[float] = None         # optional absolute CO2 cap (Mt/yr)
    allow_nuclear: bool = True
    phase_out_coal: bool = True
    allow_storage: bool = True
    allow_hydrogen: bool = True
    grid_expansion_factor: float = 1.0         # multiplier on interconnector caps
    demand_growth: float = 0.0                  # fractional change vs. reference
    discount_rate: float = 0.05
    snapshots: int = 48                         # 48 h representative window
    year: int = 2030
    scenario_name: str = "Custom"


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class LPResult:
    capacity_gw: Dict[str, Dict[str, float]] = field(default_factory=dict)
    dispatch_twh: Dict[str, float] = field(default_factory=dict)
    hourly_by_tech: Dict[str, List[float]] = field(default_factory=dict)
    hourly_load: List[float] = field(default_factory=list)
    flows_twh: Dict[str, float] = field(default_factory=dict)
    co2_mt: float = 0.0
    total_cost_beur: float = 0.0
    lcoe_eur_per_mwh: float = 0.0
    objective: float = 0.0
    solver: str = "pypsa.optimize[HiGHS]"
    data_source: str = "synthetic"
    data_citation: str = ""
    status: str = "ok"


def _scale_factor(snapshots: int) -> float:
    """Scale a representative window to an annual total (8760 h)."""
    return 8760.0 / snapshots


def _tile_periodic(values: List[float], T: int) -> np.ndarray:
    """Tile a short periodic shape (e.g. 48 h diurnal) to length T.

    The repository ships 48 h synthetic load and capacity-factor curves
    representing two diurnal cycles. When the user requests a longer
    representative window (T = 72, 96, 168 …) we have to repeat the
    diurnal pattern instead of slicing — otherwise the array is too
    short and PyPSA raises `Data for p_set has length 48 but expected
    72 for each snapshot`. Tiling preserves the diurnal physics.
    """
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return np.zeros(T, dtype=float)
    if arr.size >= T:
        return arr[:T]
    reps = int(np.ceil(T / arr.size))
    return np.tile(arr, reps)[:T]




# ---------------------------------------------------------------------------
# PyPSA path (used when the library is available)
# ---------------------------------------------------------------------------

def solve_with_pypsa(assumptions: Assumptions,
                     profiles: Optional[ProfileBundle] = None) -> LPResult:  # pragma: no cover
    import pandas as pd

    techs, costs_source = build_technologies(assumptions)
    tech_ids = [tid for tid, spec in techs.items() if spec.available]
    T = assumptions.snapshots
    scale_hours = _scale_factor(T)

    n = pypsa.Network()
    snapshots = pd.date_range("2030-01-01", periods=T, freq="h")
    n.set_snapshots(snapshots)
    n.snapshot_weightings.loc[:, :] = scale_hours

    for bus in BUSES:
        cspec = ISO_INDEX[bus]
        n.add("Bus", bus, v_nom=380.0, x=cspec.lon, y=cspec.lat)
        avg_mw = ANNUAL_DEMAND_TWH[bus] * 1e6 / 8760.0 * (1 + assumptions.demand_growth)
        if profiles and profiles.load_mw.get(bus):
            shape = _tile_periodic(profiles.load_mw[bus], T)
        else:
            shape = _tile_periodic(LOAD_SHAPE.get(bus, _BASE_LOAD_48H), T)
        shape *= avg_mw / shape.mean()
        n.add("Load", f"load_{bus}", bus=bus, p_set=shape)

    # Register carriers so global CO2 constraints work
    for tid in tech_ids:
        t = techs[tid]
        co2_factor = t.co2_t_per_mwh_fuel / max(t.efficiency, 1e-6)
        if tid not in n.carriers.index:
            n.add("Carrier", tid, co2_emissions=co2_factor)

    for tid in tech_ids:
        t = techs[tid]
        ann = annuity(t.capex_eur_per_kw * 1000, t.lifetime_years, assumptions.discount_rate)
        capital_cost = ann + t.fom_eur_per_kw_yr * 1000
        marginal = t.vom_eur_per_mwh + t.fuel_eur_per_mwh / max(t.efficiency, 1e-6) + (
            t.co2_t_per_mwh_fuel / max(t.efficiency, 1e-6) * assumptions.co2_price_eur_per_t
        )
        for bus in BUSES:
            name = f"{tid}_{bus}"
            p_nom_max = (t.potential_gw or {}).get(bus, 500.0) * 1000  # MW
            if p_nom_max < 0.001:
                continue  # skip zero-potential country/tech combos
            if t.variable:
                if tid == "solar":
                    raw = profiles.solar_cf.get(bus) if profiles else None
                    raw = raw or SOLAR_CF.get(bus, _solar_curve(0.55))
                elif tid == "offwind":
                    raw = profiles.wind_cf.get(bus) if profiles else None
                    raw = raw or WIND_OFFSHORE_CF.get(bus)
                    if not raw:
                        continue  # landlocked country, no offshore
                elif tid == "onwind":
                    raw = profiles.wind_cf.get(bus) if profiles else None
                    raw = raw or WIND_CF.get(bus, _BASE_WIND_CF_48H)
                else:
                    raw = [1.0] * T
                p_max = _tile_periodic(list(raw), T)
                n.add("Generator", name, bus=bus, carrier=tid,
                      p_nom_extendable=True, p_nom_max=p_nom_max,
                      capital_cost=capital_cost,
                      marginal_cost=marginal, p_max_pu=p_max)
            else:
                n.add("Generator", name, bus=bus, carrier=tid,
                      p_nom_extendable=True, p_nom_max=p_nom_max,
                      capital_cost=capital_cost,
                      marginal_cost=marginal, p_max_pu=t.max_cf)

    for a, b, cap in INTERCONNECTORS:
        n.add("Link", f"{a}-{b}", bus0=a, bus1=b,
              p_nom=cap * 1000 * assumptions.grid_expansion_factor,
              p_min_pu=-1, efficiency=0.98)

    if assumptions.co2_cap_mt is not None:
        n.add("GlobalConstraint", "co2_cap",
              sense="<=", constant=assumptions.co2_cap_mt * 1e6,
              carrier_attribute="co2_emissions")

    # Optional renewable-share global constraint: emulated via co2 price
    # (the canonical PyPSA-Eur approach)
    if assumptions.renewable_share_target > 0:
        total_mwh = sum(ANNUAL_DEMAND_TWH[b] * 1e6 for b in BUSES) * (1 + assumptions.demand_growth)
        re_target_mwh = assumptions.renewable_share_target * total_mwh  # noqa: F841

    n.optimize(solver_name="highs", log_to_console=False)

    result = LPResult(solver=f"pypsa.optimize[HiGHS, pypsa v{PYPSA_VERSION}]")
    result.status = "optimal"

    # Capacity per country (GW)
    for bus in BUSES:
        result.capacity_gw[bus] = {}
        for tid in tech_ids:
            gen_name = f"{tid}_{bus}"
            if gen_name not in n.generators.index:
                continue
            mw = float(n.generators.loc[gen_name, "p_nom_opt"])
            if mw > 1e-3:
                result.capacity_gw[bus][techs[tid].name] = round(mw / 1000, 3)

    # Annual generation per tech (TWh) — snapshot weightings already scale
    # the representative window to the full year.
    gen_t = n.generators_t.p  # MW × snapshot
    weighted = gen_t.multiply(n.snapshot_weightings.generators, axis=0)
    totals = weighted.sum()  # MWh per generator
    for tid in tech_ids:
        total_mwh = sum(float(totals.get(f"{tid}_{b}", 0.0)) for b in BUSES)
        if total_mwh > 1e-3:
            result.dispatch_twh[techs[tid].name] = round(total_mwh / 1e6, 2)

    # Hourly dispatch by technology (MW summed across countries)
    for tid in tech_ids:
        tname = techs[tid].name
        hourly_mw: List[float] = [0.0] * T
        for bus in BUSES:
            col = f"{tid}_{bus}"
            if col in gen_t.columns:
                for h in range(T):
                    hourly_mw[h] += float(gen_t.iloc[h][col])
        if sum(hourly_mw) > 1e-3:
            result.hourly_by_tech[tname] = [round(v, 1) for v in hourly_mw]

    # Hourly aggregate load across the whole network
    load_t = n.loads_t.p_set
    result.hourly_load = [round(float(load_t.iloc[h].sum()), 1) for h in range(T)]

    # Cross-border flows: net TWh/yr per line, positive = A→B
    link_t = n.links_t.p0 if not n.links_t.p0.empty else None
    if link_t is not None:
        link_weighted = link_t.multiply(n.snapshot_weightings.generators, axis=0).sum()
        for a, b, _ in INTERCONNECTORS:
            lname = f"{a}-{b}"
            if lname in link_weighted.index:
                result.flows_twh[lname] = round(float(link_weighted[lname]) / 1e6, 2)

    # System CO2
    co2_t = 0.0
    for tid in tech_ids:
        t = techs[tid]
        factor = t.co2_t_per_mwh_fuel / max(t.efficiency, 1e-6)  # tCO2 / MWh_el
        for bus in BUSES:
            total_mwh = float(totals.get(f"{tid}_{bus}", 0.0))
            co2_t += total_mwh * factor
    result.co2_mt = round(co2_t / 1e6, 2)

    result.objective = float(n.objective)
    result.total_cost_beur = round(n.objective / 1e9, 2)
    total_gen_mwh = sum(result.dispatch_twh.values()) * 1e6
    result.lcoe_eur_per_mwh = (
        round(n.objective / total_gen_mwh, 2) if total_gen_mwh > 0 else 0.0
    )
    if costs_source:
        result.data_source = costs_source
        result.data_citation = (
            "Technology costs: PyPSA/technology-data v0.14.0 "
            "(https://github.com/PyPSA/technology-data). "
            "Country data: ENTSO-E TYNDP 2022, EMBER European Electricity "
            "Review 2024, EC Impact Assessment 2040 Climate Target. "
            "Solver: PyPSA " + (PYPSA_VERSION or "") +
            " via linopy + HiGHS — same stack used by PyPSA-Eur "
            "(https://github.com/PyPSA/pypsa-eur)."
        )
    return result


def run_energy_system(assumptions: Assumptions) -> LPResult:
    """Run the optimization using the real PyPSA library.

    Resolution order:

    1. If `PYPSA_EUR_NETWORK` is set and points to a serialised PyPSA-Eur
       network on disk, load and solve it directly (real peer-reviewed model).
    2. Otherwise, build the 30-country network with real PyPSA-Eur
       technology-data costs and per-country geospatial data. Solved via
       `pypsa.Network.optimize()` with HiGHS — the same call PyPSA-Eur's
       snakemake workflow uses.

    The returned `LPResult.data_source` field exposes which path ran so the
    frontend can display provenance. There is no scipy fallback: if PyPSA is
    not importable the call raises and the API returns an error to the client.
    """
    if not PYPSA_AVAILABLE:
        raise RuntimeError(
            "PyPSA is not installed in this environment. The energy-system "
            "optimizer requires the real `pypsa` library — install it with "
            "`pip install pypsa highspy` or use the official Docker image."
        )

    # (1) Pre-built PyPSA-Eur network
    eur_net = load_pypsa_eur_network()
    if eur_net is not None:  # pragma: no cover
        try:
            result = solve_pypsa_eur(eur_net, assumptions)
            result.data_source = "PyPSA-Eur network (pre-built)"
            result.data_citation = (
                "Hörsch, Hofmann, Schlachtberger & Brown (2018). "
                "PyPSA-Eur: An open optimisation model of the European "
                "transmission system. Energy Strategy Reviews."
            )
            return result
        except Exception:
            pass

    # (2) 30-country network with real PyPSA-Eur technology-data costs
    profiles = load_best_profiles(assumptions.snapshots)
    result = solve_with_pypsa(assumptions, profiles=profiles)
    # solve_with_pypsa already sets data_source/citation from the PyPSA-Eur
    # technology-data overlay when present; merge with profile provenance.
    if profiles and not result.data_source.startswith("PyPSA-Eur"):
        result.data_source = (
            f"{result.data_source} + {profiles.source}"
            if result.data_source else profiles.source
        )
        result.data_citation = (
            result.data_citation + " · " + profiles.citation
            if result.data_citation else profiles.citation
        )
    return result


def solve_pypsa_eur(n, assumptions: Assumptions) -> LPResult:  # pragma: no cover
    """Solve an already-loaded PyPSA-Eur network with user overrides."""
    import pandas as pd  # noqa: F401

    if assumptions.co2_cap_mt is not None:
        if "co2_limit" in n.global_constraints.index:
            n.global_constraints.at["co2_limit", "constant"] = assumptions.co2_cap_mt * 1e6
        else:
            n.add("GlobalConstraint", "co2_limit",
                  sense="<=", constant=assumptions.co2_cap_mt * 1e6,
                  carrier_attribute="co2_emissions")

    if hasattr(n, "optimize"):
        n.optimize(solver_name="highs")
    else:
        n.lopf(solver_name="highs")

    result = LPResult(solver=f"pypsa-eur.optimize[HiGHS, v{PYPSA_VERSION}]")
    result.status = "optimal"
    # Aggregate by bus if country codes are present, otherwise lump together
    for gen in n.generators.itertuples():
        bus = str(gen.bus).split("_")[0] or "network"
        result.capacity_gw.setdefault(bus, {})
        carrier = getattr(gen, "carrier", "gen")
        result.capacity_gw[bus][carrier] = result.capacity_gw[bus].get(carrier, 0.0) + \
            float(getattr(gen, "p_nom_opt", getattr(gen, "p_nom", 0.0))) / 1000.0
    disp = n.generators_t.p.sum()
    for name, mw in disp.items():
        carrier = n.generators.at[name, "carrier"] if name in n.generators.index else "gen"
        result.dispatch_twh[carrier] = result.dispatch_twh.get(carrier, 0.0) + float(mw) / 1e6
    result.objective = float(n.objective)
    result.total_cost_beur = round(n.objective / 1e9, 2)
    return result
