-- ─────────────────────────────────────────────────────────────────────────────
-- Materialise the full ECNO indicator seed set directly into pw_indicators
-- and pw_indicator_points for the "policy-gap-2-0" project.
--
-- Until now the seed list lived only in src/data/ecno-indicators.ts and was
-- copied into Postgres lazily on first project page load. Doing it here in
-- SQL means the rows exist in the database from migration time, independent
-- of whether the Next.js seeder ever runs.
--
-- Both inserts are idempotent (on conflict do nothing) so re-running the
-- migration is safe — and the app-level seeder remains as a fallback for
-- any indicator IDs added to the TS file after this migration was authored.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.pw_indicators
  (id, project_id, name, category, unit, description, source, source_url,
   direction, target_value, target_year, is_seed)
values
  ('ghg-total-net', 'policy-gap-2-0', 'Net GHG emissions (excl. LULUCF)', 'emissions', 'Mt CO₂eq', 'Total EU-27 net greenhouse gas emissions excluding LULUCF, reported under the UNFCCC inventory.', 'EEA GHG inventory', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/3b7fe76c-524a-439a-bfd2-a6e4046302a2', 'down', 850, 2030, true),
  ('res-share', 'policy-gap-2-0', 'Renewable energy share in gross final energy consumption', 'energy-supply', '%', 'Share of energy from renewable sources in gross final energy consumption (RED III binding 2030 target: 42.5%, indicative 45%).', 'Eurostat (nrg_ind_ren)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_ind_ren/default/table', 'up', 42.5, 2030, true),
  ('power-sector-ghg', 'policy-gap-2-0', 'Power sector GHG emissions', 'energy-supply', 'Mt CO₂eq', 'GHG emissions from public electricity and heat production (CRF 1.A.1.a/b/c). ECNO block: Electricity.', 'EEA GHG inventory (CRF 1.A.1)', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/3b7fe76c-524a-439a-bfd2-a6e4046302a2', 'down', null, null, true),
  ('solar-pv-additions', 'policy-gap-2-0', 'Annual solar PV capacity additions', 'energy-supply', 'GW/yr', 'Net new solar photovoltaic capacity installed each year across the EU-27. ECNO block: Electricity.', 'IRENA renewable capacity statistics', 'https://www.irena.org/Data/View-data-by-topic/Capacity-and-Generation/Statistics-Time-Series', 'up', null, null, true),
  ('wind-additions', 'policy-gap-2-0', 'Annual wind capacity additions', 'energy-supply', 'GW/yr', 'Net new onshore and offshore wind capacity commissioned each year in the EU-27. ECNO block: Electricity.', 'IRENA renewable capacity statistics', 'https://www.irena.org/Data/View-data-by-topic/Capacity-and-Generation/Statistics-Time-Series', 'up', null, null, true),
  ('battery-storage-capacity', 'policy-gap-2-0', 'Stationary battery storage capacity', 'energy-supply', 'GW', 'Installed stationary battery storage capacity (grid-scale + behind-the-meter) in the EU-27. ECNO block: Electricity.', 'IRENA renewable capacity statistics', 'https://www.irena.org/Data/View-data-by-topic/Capacity-and-Generation/Statistics-Time-Series', 'up', null, null, true),
  ('fossil-power-share', 'policy-gap-2-0', 'Fossil share of electricity generation', 'energy-supply', '%', 'Share of gross electricity generation produced from coal, oil and gas in the EU-27. Required to fall sharply to align with the 2040 climate target. ECNO block: Electricity.', 'Eurostat (nrg_bal_peh)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_bal_peh/default/table', 'down', null, null, true),
  ('smart-meter-rollout', 'policy-gap-2-0', 'Electricity smart meter penetration', 'energy-supply', '%', 'Share of consumption points equipped with a smart electricity meter. Tracks Electricity-Directive rollout obligations. ECNO block: Electricity.', 'JRC smart-meter benchmarking', 'https://joint-research-centre.ec.europa.eu/scientific-activities-z/smart-electricity-systems-and-interoperability_en', 'up', null, null, true),
  ('final-energy-consumption', 'policy-gap-2-0', 'Final energy consumption', 'energy-demand', 'Mtoe', 'EU final energy consumption. EED 2030 indicative target: 763 Mtoe.', 'Eurostat (nrg_bal_c)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_bal_c/default/table', 'down', 763, 2030, true),
  ('end-use-electrification', 'policy-gap-2-0', 'Electricity share of final energy demand', 'energy-demand', '%', 'Share of final energy consumption supplied as electricity (all sectors). Used as a proxy for end-use electrification progress. ECNO block: Electricity.', 'Eurostat (nrg_bal_c)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_bal_c/default/table', 'up', null, null, true),
  ('ev-share-new-cars', 'policy-gap-2-0', 'Battery-electric vehicle share of new car registrations', 'transport', '%', 'Share of new passenger car registrations that are battery-electric. Tracks progress towards the CO₂-emission standards for new cars (100% ZEV by 2035).', 'EEA / ACEA', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/fa8b1229-3db6-495d-b18e-9c9b3267c02b', 'up', 100, 2035, true),
  ('zev-share-car-stock', 'policy-gap-2-0', 'Zero-emission share of passenger car stock', 'transport', '%', 'Cumulative share of zero-emission vehicles in the on-the-road passenger car fleet across the EU-27. ECNO block: Mobility.', 'Eurostat road vehicle stock (road_eqs_carpda)', 'https://ec.europa.eu/eurostat/databrowser/view/road_eqs_carpda/default/table', 'up', 93.5, 2050, true),
  ('zev-charging-points', 'policy-gap-2-0', 'Public EV charging points deployed', 'transport', 'thousand points', 'Cumulative count of publicly accessible alternative-fuel recharging points across the EU-27 (AC + DC). Used to track AFIR rollout. ECNO block: Mobility.', 'EAFO', 'https://alternative-fuels-observatory.ec.europa.eu/transport-mode/road/european-union-eu27', 'up', null, null, true),
  ('road-passenger-share', 'policy-gap-2-0', 'Road share of inland passenger transport', 'transport', '%', 'Share of inland passenger transport (passenger-kilometres) carried by cars, buses and coaches. ECNO block: Mobility.', 'Eurostat (tran_hv_psmod)', 'https://ec.europa.eu/eurostat/databrowser/view/tran_hv_psmod/default/table', 'down', 77.5, 2050, true),
  ('rail-passenger-share', 'policy-gap-2-0', 'Rail share of inland passenger transport', 'transport', '%', 'Share of inland passenger-kilometres travelled by rail (trains + trams + metros). ECNO block: Mobility.', 'Eurostat (tran_hv_psmod)', 'https://ec.europa.eu/eurostat/databrowser/view/tran_hv_psmod/default/table', 'up', null, null, true),
  ('rail-iww-freight-share', 'policy-gap-2-0', 'Rail and inland waterway share of freight transport', 'transport', '%', 'Share of inland tonne-kilometres carried by rail or inland waterways (the rest is hauled by road). ECNO block: Mobility.', 'Eurostat (tran_hv_frmod)', 'https://ec.europa.eu/eurostat/databrowser/view/tran_hv_frmod/default/table', 'up', null, null, true),
  ('rail-electrification', 'policy-gap-2-0', 'Share of electrified railway lines', 'transport', '%', 'Share of total operational railway track length that is electrified. ECNO block: Mobility.', 'Eurostat (rail_if_electri)', 'https://ec.europa.eu/eurostat/databrowser/view/rail_if_electri/default/table', 'up', null, null, true),
  ('zev-share-van-stock', 'policy-gap-2-0', 'Zero-emission share of light commercial vehicle stock', 'transport', '%', 'Share of N1 light commercial vehicles in the EU-27 fleet that are zero-emission. Tracks the 2035 zero-emission target for new vans. ECNO block: Mobility.', 'Eurostat (road_eqs_lormot)', 'https://ec.europa.eu/eurostat/databrowser/view/road_eqs_lormot/default/table', 'up', 100, 2050, true),
  ('zev-share-truck-stock', 'policy-gap-2-0', 'Zero-emission share of heavy-duty vehicle stock', 'transport', '%', 'Share of heavy-duty trucks and buses in the EU-27 fleet that are zero-emission (battery-electric or fuel-cell). ECNO block: Mobility.', 'Eurostat (road_eqs_lormot)', 'https://ec.europa.eu/eurostat/databrowser/view/road_eqs_lormot/default/table', 'up', null, null, true),
  ('building-renovation-rate', 'policy-gap-2-0', 'Energy-related building renovation rate', 'buildings', '%/yr', 'Weighted annual energy renovation rate of the EU building stock. EPBD recast (2024) requires Member States to at least double the deep-renovation rate.', 'JRC / Commission staff working document', 'https://commission.europa.eu/topics/energy-efficiency/energy-efficient-buildings_en', 'up', 2, 2030, true),
  ('buildings-ghg', 'policy-gap-2-0', 'Operational GHG emissions from buildings', 'buildings', 'Mt CO₂eq', 'Direct GHG emissions from energy use in residential and commercial/institutional buildings (CRF 1.A.4.a/b). ECNO block: Buildings.', 'EEA GHG inventory (CRF 1.A.4)', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/3b7fe76c-524a-439a-bfd2-a6e4046302a2', 'down', null, null, true),
  ('heat-pump-stock', 'policy-gap-2-0', 'Installed heat pump stock', 'buildings', 'million units', 'Cumulative installed base of heat pumps for space heating across the EU-27. REPowerEU targets 60 million units by 2030. ECNO block: Buildings.', 'EHPA Market Report', 'https://www.ehpa.org/market-data/', 'up', 60, 2030, true),
  ('heat-pump-sales', 'policy-gap-2-0', 'Annual heat pump sales', 'buildings', 'thousand units', 'New heat pump units sold per year across the EU-27 (all heat-pump types). ECNO block: Buildings.', 'EHPA Market Report', 'https://www.ehpa.org/market-data/', 'up', null, null, true),
  ('renewable-heating-cooling', 'policy-gap-2-0', 'Renewable share in heating and cooling', 'buildings', '%', 'Share of energy used for heating and cooling that comes from renewable sources. RED III indicative 2030 target: 49% (with annual +1.1pp average increment). ECNO block: Buildings.', 'Eurostat (nrg_ind_ren, nrg_bal=REN_H_C)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_ind_ren/default/table', 'up', 49, 2030, true),
  ('floor-space-per-capita', 'policy-gap-2-0', 'Average residential floor space per resident', 'buildings', 'm²/person', 'Average residential floor area per EU resident. A rising trend pushes sectoral energy demand up even if per-m² intensity falls. ECNO block: Buildings.', 'Eurostat / EU-SILC (ilc_lvho03)', 'https://ec.europa.eu/eurostat/databrowser/view/ilc_lvho03/default/table', 'down', null, null, true),
  ('industry-ghg', 'policy-gap-2-0', 'Industrial process and energy-use GHG emissions', 'industry', 'Mt CO₂eq', 'Combined GHG emissions from industrial energy use (CRF 1.A.2) and industrial processes & product use (CRF 2), EU-27.', 'EEA GHG inventory', 'https://www.eea.europa.eu/en/datahub', 'down', null, null, true),
  ('industry-electrification', 'policy-gap-2-0', 'Electricity share of industrial energy use', 'industry', '%', 'Share of final energy used by industry that is supplied as electricity. A key driver of process decarbonisation. ECNO block: Industry.', 'Eurostat (nrg_bal_c)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_bal_c/default/table', 'up', null, null, true),
  ('hydrogen-electrolyser-capacity', 'policy-gap-2-0', 'Installed electrolyser capacity', 'industry', 'MW', 'Cumulative installed water-electrolyser capacity in the EU-27, a proxy for renewable hydrogen ramp-up. REPowerEU 2030 target: 10 Mt RFNBO production. ECNO block: Industry / Clean Technologies.', 'IEA / Clean Hydrogen Joint Undertaking', 'https://www.clean-hydrogen.europa.eu/knowledge-management/sria-key-performance-indicators-kpis_en', 'up', null, null, true),
  ('agri-ghg', 'policy-gap-2-0', 'Agriculture GHG emissions', 'agriculture', 'Mt CO₂eq', 'EU-27 agriculture-sector GHG emissions (CRF 3). ECNO block: Agrifood.', 'EEA GHG inventory', 'https://www.eea.europa.eu/en/datahub', 'down', null, null, true),
  ('lulucf-net-removal', 'policy-gap-2-0', 'LULUCF net removals', 'lulucf', 'Mt CO₂eq', 'Net carbon removals from Land Use, Land-Use Change & Forestry. LULUCF Regulation 2030 target: -310 Mt CO₂eq (i.e. removal of 310 Mt). ECNO block: Carbon Dioxide Removal.', 'EEA GHG inventory', 'https://www.eea.europa.eu/en/datahub', 'down', -310, 2030, true),
  ('clean-tech-investment', 'policy-gap-2-0', 'Clean-energy investment', 'finance', 'bn EUR', 'Annual EU clean-energy investment (renewables, grids, efficiency, electrified transport). Sourced from IEA World Energy Investment.', 'IEA World Energy Investment', 'https://www.iea.org/reports/world-energy-investment-2024', 'up', null, null, true),
  ('energy-poverty-share', 'policy-gap-2-0', 'Population unable to keep home adequately warm', 'fairness', '%', 'Share of EU population reporting inability to keep their home adequately warm — proxy indicator for energy poverty.', 'Eurostat (ilc_mdes01)', 'https://ec.europa.eu/eurostat/databrowser/view/ilc_mdes01/default/table', 'down', null, null, true),
  ('environmental-employment', 'policy-gap-2-0', 'Employment in environmental goods and services', 'fairness', 'million FTE', 'Full-time-equivalent employment in the EU environmental goods and services sector. A proxy for green-job creation. ECNO block: Just & Fair Transition.', 'Eurostat (env_ac_egss1)', 'https://ec.europa.eu/eurostat/databrowser/view/env_ac_egss1/default/table', 'up', null, null, true),
  ('cattle-population', 'policy-gap-2-0', 'EU cattle herd size', 'agriculture', 'million head', 'Number of bovine animals on EU-27 farms. Enteric fermentation from cattle is the largest single source of agricultural methane. ECNO block: Agrifood.', 'Eurostat (apro_mt_lscatl)', 'https://ec.europa.eu/eurostat/databrowser/view/apro_mt_lscatl/default/table', 'down', null, null, true),
  ('nitrogen-fertiliser-use', 'policy-gap-2-0', 'Mineral nitrogen fertiliser consumption', 'agriculture', 'kt N', 'Total mineral nitrogen fertiliser applied on EU-27 agricultural land — drives N₂O emissions and ammonia losses. ECNO block: Agrifood.', 'Eurostat (aei_fm_usefert)', 'https://ec.europa.eu/eurostat/databrowser/view/aei_fm_usefert/default/table', 'down', null, null, true),
  ('organic-farming-share', 'policy-gap-2-0', 'Organic share of utilised agricultural area', 'agriculture', '%', 'Share of utilised agricultural area under organic farming (in-conversion or certified). Farm-to-Fork 2030 target: 25%. ECNO block: Agrifood.', 'Eurostat (sdg_02_40)', 'https://ec.europa.eu/eurostat/databrowser/view/sdg_02_40/default/table', 'up', 25, 2030, true),
  ('food-waste-per-capita', 'policy-gap-2-0', 'Food waste generated per capita', 'agriculture', 'kg/person/yr', 'Total food waste across the EU-27 food chain, per resident. The Waste Framework Directive sets binding 2030 reduction targets vs. 2020. ECNO block: Agrifood.', 'Eurostat (env_wasfw)', 'https://ec.europa.eu/eurostat/databrowser/view/env_wasfw/default/table', 'down', null, null, true),
  ('forest-net-sink', 'policy-gap-2-0', 'Forest land net carbon removals', 'lulucf', 'Mt CO₂eq', 'Net CO₂ removals from forest land (CRF 4.A), EU-27. The sink has been weakening since the mid-2010s due to harvest pressure, disturbances and ageing stands. ECNO block: Carbon Dioxide Removal.', 'EEA GHG inventory (CRF 4.A)', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/3b7fe76c-524a-439a-bfd2-a6e4046302a2', 'down', null, null, true),
  ('harvested-wood-pool', 'policy-gap-2-0', 'Harvested wood products carbon pool change', 'lulucf', 'Mt CO₂eq', 'Annual change in the carbon stock of harvested wood products (CRF 4.G). Negative values indicate net carbon storage in long-lived wood products. ECNO block: Carbon Dioxide Removal.', 'EEA GHG inventory (CRF 4.G)', 'https://www.eea.europa.eu/en/datahub/datahubitem-view/3b7fe76c-524a-439a-bfd2-a6e4046302a2', 'down', null, null, true),
  ('engineered-cdr-capacity', 'policy-gap-2-0', 'Engineered CDR operational capacity', 'lulucf', 'kt CO₂/yr', 'Capacity of operational engineered carbon-removal facilities in the EU-27 (DACCS, BECCS, BiCRS, ocean alkalinity). Tracks the EU 2040 Industrial Carbon Management Strategy ramp-up. ECNO block: Carbon Dioxide Removal.', 'IEA CCUS projects database', 'https://www.iea.org/data-and-statistics/data-product/ccus-projects-database', 'up', null, null, true),
  ('battery-mfg-capacity', 'policy-gap-2-0', 'EU battery cell manufacturing capacity', 'industry', 'GWh/yr', 'Operational lithium-ion battery cell manufacturing capacity in the EU-27. Net-Zero Industry Act targets 40% of EU annual demand from domestic production by 2030. ECNO block: Clean Technologies.', 'JRC strategic technologies for the green deal', 'https://joint-research-centre.ec.europa.eu/scientific-activities-z/strategic-technologies-green-deal_en', 'up', null, null, true),
  ('solar-pv-mfg-capacity', 'policy-gap-2-0', 'EU solar PV module manufacturing capacity', 'industry', 'GW/yr', 'Annual solar PV module assembly capacity located in the EU-27. NZIA 2030 benchmark: 40% of annual deployment supplied domestically. ECNO block: Clean Technologies.', 'JRC strategic technologies for the green deal', 'https://joint-research-centre.ec.europa.eu/scientific-activities-z/strategic-technologies-green-deal_en', 'up', null, null, true),
  ('electrolyser-mfg-capacity', 'policy-gap-2-0', 'EU electrolyser manufacturing capacity', 'industry', 'GW/yr', 'Announced electrolyser production capacity from EU-located manufacturers. ECNO block: Clean Technologies.', 'Clean Hydrogen Joint Undertaking / IEA Hydrogen Production Projects', 'https://www.iea.org/data-and-statistics/data-product/hydrogen-production-and-infrastructure-projects-database', 'up', null, null, true),
  ('clean-tech-trade-balance', 'policy-gap-2-0', 'EU clean-tech goods trade balance', 'industry', 'bn EUR', 'Net trade balance for the EU-27 in clean energy goods (solar, wind, batteries, heat pumps, EVs). Negative values indicate net imports. ECNO block: Clean Technologies.', 'Eurostat Comext', 'https://ec.europa.eu/eurostat/web/international-trade-in-goods/data/database', 'up', null, null, true),
  ('eu-ets-price', 'policy-gap-2-0', 'EU ETS allowance price', 'finance', 'EUR/t CO₂eq', 'Annual average secondary-market spot price of EU ETS allowances (EUA). Used as the headline carbon-price signal for the EU. ECNO block: Finance.', 'ICE EUA futures (settlement)', 'https://www.eex.com/en/market-data/environmental-markets/emissions-auctions', 'up', null, null, true),
  ('fossil-subsidies', 'policy-gap-2-0', 'EU fossil-fuel subsidies', 'finance', 'bn EUR', 'Sum of identified direct and indirect fossil-fuel subsidies across EU-27 Member States. ECNO block: Finance.', 'Commission State of the Energy Union (fossil-fuel subsidies)', 'https://energy.ec.europa.eu/topics/energy-strategy/energy-union_en', 'down', null, null, true),
  ('green-bond-issuance', 'policy-gap-2-0', 'EU green bond issuance', 'finance', 'bn EUR', 'Annual EU-aligned green bond issuance from sovereign, corporate and supranational issuers domiciled in the EU-27. ECNO block: Finance.', 'Climate Bonds Initiative — Green Bond Database', 'https://www.climatebonds.net/market/data/', 'up', null, null, true),
  ('energy-rdd-budget', 'policy-gap-2-0', 'Public energy research, development and demonstration budgets', 'finance', 'bn EUR', 'Public RD&D spending on energy across EU-27 Member States, IEA basis. ECNO block: Finance.', 'IEA Energy Technology RD&D Budgets', 'https://www.iea.org/data-and-statistics/data-product/energy-technology-rd-and-d-budget-database-2', 'up', null, null, true),
  ('carbon-pricing-coverage', 'policy-gap-2-0', 'Share of EU emissions covered by carbon pricing', 'emissions', '%', 'Share of EU-27 GHG emissions covered by an explicit carbon-pricing instrument (EU ETS, ETS2, or national carbon tax). ECNO block: Governance.', 'World Bank Carbon Pricing Dashboard', 'https://carbonpricingdashboard.worldbank.org/', 'up', null, null, true),
  ('national-climate-laws', 'policy-gap-2-0', 'Member States with a binding national climate law', 'emissions', 'count', 'Number of EU-27 Member States that have adopted a binding national climate-neutrality or framework climate law. ECNO block: Governance.', 'Ecologic Institute / EEA national policy database', 'https://www.eea.europa.eu/en/topics/at-a-glance/climate/policies-and-targets', 'up', null, null, true),
  ('necp-implementation-score', 'policy-gap-2-0', 'NECP implementation completeness score', 'emissions', 'score 0–100', 'Aggregate Commission assessment of how completely Member States have implemented their National Energy and Climate Plans. Higher is better. ECNO block: Governance.', 'Commission NECP assessments', 'https://commission.europa.eu/energy-climate-change-environment/implementation-eu-countries/energy-and-climate-governance-and-reporting/national-energy-and-climate-plans_en', 'up', null, null, true),
  ('meat-consumption-per-capita', 'policy-gap-2-0', 'Per-capita meat consumption', 'fairness', 'kg/person/yr', 'Average annual meat consumption per EU-27 resident across bovine, pig, poultry and sheep & goat meat. ECNO block: Lifestyles.', 'Eurostat / DG AGRI meat balance sheets', 'https://agriculture.ec.europa.eu/data-and-analysis/markets/overviews/market-observatories/meat_en', 'down', null, null, true),
  ('air-passengers-per-capita', 'policy-gap-2-0', 'Air passenger journeys per capita', 'fairness', 'journeys/person/yr', 'Total air passengers carried (arrivals + departures, including transfer) per EU-27 resident. Proxy for aviation demand. ECNO block: Lifestyles.', 'Eurostat (avia_paoc)', 'https://ec.europa.eu/eurostat/databrowser/view/avia_paoc/default/table', 'down', null, null, true),
  ('household-energy-per-capita', 'policy-gap-2-0', 'Per-capita household final energy consumption', 'fairness', 'kgoe/person', 'Final energy consumed by households across the EU-27, divided by population. Captures behaviour, efficiency and floor-space effects together. ECNO block: Lifestyles.', 'Eurostat (nrg_bal_c, sector households)', 'https://ec.europa.eu/eurostat/databrowser/view/nrg_bal_c/default/table', 'down', null, null, true),
  ('climate-economic-losses', 'policy-gap-2-0', 'Climate-related economic losses', 'fairness', 'bn EUR/yr', 'Annual reported economic losses from weather and climate-related events in the EU-27 (CATDAT / EEA indicator). ECNO block: Adaptation.', 'EEA indicator CLIM039', 'https://www.eea.europa.eu/en/analysis/indicators/economic-losses-from-climate-related', 'down', null, null, true),
  ('water-exploitation-index', 'policy-gap-2-0', 'Water exploitation index', 'fairness', '%', 'Ratio of total freshwater abstraction to long-term mean freshwater resources, EU-27 aggregate. Values above 20% indicate water stress. ECNO block: Adaptation.', 'EEA / Eurostat (env_wat_bal)', 'https://ec.europa.eu/eurostat/databrowser/view/env_wat_bal/default/table', 'down', null, null, true),
  ('national-adaptation-strategies', 'policy-gap-2-0', 'Member States with an adopted national adaptation strategy', 'fairness', 'count', 'Count of EU-27 Member States that have a national adaptation strategy or plan recorded in the Climate-ADAPT platform. ECNO block: Adaptation.', 'EEA Climate-ADAPT', 'https://climate-adapt.eea.europa.eu/en/countries-regions/countries', 'up', null, null, true),
  ('international-climate-finance', 'policy-gap-2-0', 'EU international public climate finance', 'finance', 'bn EUR', 'Public climate finance flowing from the EU-27 and EU institutions to developing countries (mitigation + adaptation). ECNO block: External Action.', 'Commission progress reports under Reg. 2018/1999', 'https://climate.ec.europa.eu/eu-action/international-action-climate-change/eu-climate-finance_en', 'up', null, null, true),
  ('cbam-import-coverage', 'policy-gap-2-0', 'Imports covered by CBAM reporting', 'finance', 'Mt CO₂eq', 'Embedded emissions in EU-27 imports of CBAM-covered goods (iron & steel, aluminium, cement, fertiliser, electricity, hydrogen) as reported during the CBAM transitional period. ECNO block: External Action.', 'DG TAXUD CBAM transitional registry', 'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en', 'down', null, null, true),
  ('embodied-import-emissions', 'policy-gap-2-0', 'Embodied GHG emissions in EU imports', 'finance', 'Mt CO₂eq', 'Total GHG emissions embodied in goods and services imported into the EU-27, based on consumption-based accounting. ECNO block: External Action.', 'JRC consumption-based emissions / EDGAR', 'https://edgar.jrc.ec.europa.eu/', 'down', null, null, true)
on conflict (id) do nothing;

insert into public.pw_indicator_points (indicator_id, year, value)
values
  ('ghg-total-net', 2018, 3893),
  ('ghg-total-net', 2019, 3743),
  ('ghg-total-net', 2020, 3457),
  ('ghg-total-net', 2021, 3635),
  ('ghg-total-net', 2022, 3548),
  ('ghg-total-net', 2023, 3225),
  ('res-share', 2018, 18),
  ('res-share', 2019, 19.1),
  ('res-share', 2020, 22),
  ('res-share', 2021, 21.9),
  ('res-share', 2022, 23),
  ('res-share', 2023, 24.5),
  ('power-sector-ghg', 2018, 953),
  ('power-sector-ghg', 2019, 829),
  ('power-sector-ghg', 2020, 726),
  ('power-sector-ghg', 2021, 793),
  ('power-sector-ghg', 2022, 786),
  ('power-sector-ghg', 2023, 622),
  ('solar-pv-additions', 2019, 16),
  ('solar-pv-additions', 2020, 21),
  ('solar-pv-additions', 2021, 28),
  ('solar-pv-additions', 2022, 41),
  ('solar-pv-additions', 2023, 56),
  ('solar-pv-additions', 2024, 65),
  ('wind-additions', 2019, 13),
  ('wind-additions', 2020, 14),
  ('wind-additions', 2021, 11),
  ('wind-additions', 2022, 16),
  ('wind-additions', 2023, 16),
  ('wind-additions', 2024, 13),
  ('battery-storage-capacity', 2020, 2.5),
  ('battery-storage-capacity', 2021, 4),
  ('battery-storage-capacity', 2022, 7.5),
  ('battery-storage-capacity', 2023, 14),
  ('battery-storage-capacity', 2024, 25),
  ('fossil-power-share', 2018, 42),
  ('fossil-power-share', 2019, 38),
  ('fossil-power-share', 2020, 35),
  ('fossil-power-share', 2021, 37),
  ('fossil-power-share', 2022, 38),
  ('fossil-power-share', 2023, 32),
  ('smart-meter-rollout', 2018, 34),
  ('smart-meter-rollout', 2020, 43),
  ('smart-meter-rollout', 2022, 56),
  ('smart-meter-rollout', 2023, 60),
  ('final-energy-consumption', 2018, 1064),
  ('final-energy-consumption', 2019, 1053),
  ('final-energy-consumption', 2020, 962),
  ('final-energy-consumption', 2021, 1018),
  ('final-energy-consumption', 2022, 977),
  ('final-energy-consumption', 2023, 940),
  ('end-use-electrification', 2018, 22.1),
  ('end-use-electrification', 2019, 22.4),
  ('end-use-electrification', 2020, 22.8),
  ('end-use-electrification', 2021, 22.9),
  ('end-use-electrification', 2022, 22.9),
  ('end-use-electrification', 2023, 23.2),
  ('ev-share-new-cars', 2019, 1.9),
  ('ev-share-new-cars', 2020, 6.2),
  ('ev-share-new-cars', 2021, 9.1),
  ('ev-share-new-cars', 2022, 12.1),
  ('ev-share-new-cars', 2023, 14.6),
  ('ev-share-new-cars', 2024, 13.6),
  ('zev-share-car-stock', 2019, 0.3),
  ('zev-share-car-stock', 2020, 0.6),
  ('zev-share-car-stock', 2021, 1),
  ('zev-share-car-stock', 2022, 1.5),
  ('zev-share-car-stock', 2023, 2.3),
  ('zev-share-car-stock', 2024, 2.8),
  ('zev-charging-points', 2019, 180),
  ('zev-charging-points', 2020, 250),
  ('zev-charging-points', 2021, 330),
  ('zev-charging-points', 2022, 460),
  ('zev-charging-points', 2023, 630),
  ('zev-charging-points', 2024, 830),
  ('road-passenger-share', 2018, 82.7),
  ('road-passenger-share', 2019, 82.1),
  ('road-passenger-share', 2020, 84.6),
  ('road-passenger-share', 2021, 83.5),
  ('road-passenger-share', 2022, 81.4),
  ('road-passenger-share', 2023, 80.6),
  ('rail-passenger-share', 2018, 7.9),
  ('rail-passenger-share', 2019, 8.2),
  ('rail-passenger-share', 2020, 5.7),
  ('rail-passenger-share', 2021, 6.5),
  ('rail-passenger-share', 2022, 7.6),
  ('rail-passenger-share', 2023, 7.8),
  ('rail-iww-freight-share', 2018, 23.7),
  ('rail-iww-freight-share', 2019, 23.5),
  ('rail-iww-freight-share', 2020, 23.1),
  ('rail-iww-freight-share', 2021, 22.9),
  ('rail-iww-freight-share', 2022, 22.1),
  ('rail-iww-freight-share', 2023, 22),
  ('rail-electrification', 2018, 55.6),
  ('rail-electrification', 2019, 55.8),
  ('rail-electrification', 2020, 56.1),
  ('rail-electrification', 2021, 56.4),
  ('rail-electrification', 2022, 56.5),
  ('zev-share-van-stock', 2020, 0.4),
  ('zev-share-van-stock', 2021, 0.7),
  ('zev-share-van-stock', 2022, 1.1),
  ('zev-share-van-stock', 2023, 1.6),
  ('zev-share-truck-stock', 2020, 0.1),
  ('zev-share-truck-stock', 2021, 0.15),
  ('zev-share-truck-stock', 2022, 0.2),
  ('zev-share-truck-stock', 2023, 0.3),
  ('building-renovation-rate', 2018, 1),
  ('building-renovation-rate', 2019, 1),
  ('building-renovation-rate', 2020, 1),
  ('building-renovation-rate', 2021, 1.1),
  ('building-renovation-rate', 2022, 1.2),
  ('buildings-ghg', 2018, 510),
  ('buildings-ghg', 2019, 491),
  ('buildings-ghg', 2020, 474),
  ('buildings-ghg', 2021, 506),
  ('buildings-ghg', 2022, 446),
  ('buildings-ghg', 2023, 420),
  ('heat-pump-stock', 2019, 13.5),
  ('heat-pump-stock', 2020, 15),
  ('heat-pump-stock', 2021, 17.1),
  ('heat-pump-stock', 2022, 20),
  ('heat-pump-stock', 2023, 22.5),
  ('heat-pump-stock', 2024, 24.5),
  ('heat-pump-sales', 2019, 1620),
  ('heat-pump-sales', 2020, 1830),
  ('heat-pump-sales', 2021, 2180),
  ('heat-pump-sales', 2022, 3000),
  ('heat-pump-sales', 2023, 2640),
  ('heat-pump-sales', 2024, 2100),
  ('renewable-heating-cooling', 2018, 21.7),
  ('renewable-heating-cooling', 2019, 22.5),
  ('renewable-heating-cooling', 2020, 23.9),
  ('renewable-heating-cooling', 2021, 23),
  ('renewable-heating-cooling', 2022, 24.8),
  ('renewable-heating-cooling', 2023, 26.2),
  ('floor-space-per-capita', 2018, 41.1),
  ('floor-space-per-capita', 2019, 41.4),
  ('floor-space-per-capita', 2020, 42),
  ('floor-space-per-capita', 2021, 42.5),
  ('floor-space-per-capita', 2022, 42.9),
  ('industry-ghg', 2018, 813),
  ('industry-ghg', 2019, 793),
  ('industry-ghg', 2020, 740),
  ('industry-ghg', 2021, 775),
  ('industry-ghg', 2022, 728),
  ('industry-ghg', 2023, 670),
  ('industry-electrification', 2018, 33),
  ('industry-electrification', 2019, 33.5),
  ('industry-electrification', 2020, 34.4),
  ('industry-electrification', 2021, 33.4),
  ('industry-electrification', 2022, 33),
  ('industry-electrification', 2023, 34.1),
  ('hydrogen-electrolyser-capacity', 2020, 60),
  ('hydrogen-electrolyser-capacity', 2021, 100),
  ('hydrogen-electrolyser-capacity', 2022, 170),
  ('hydrogen-electrolyser-capacity', 2023, 260),
  ('hydrogen-electrolyser-capacity', 2024, 440),
  ('agri-ghg', 2018, 387),
  ('agri-ghg', 2019, 386),
  ('agri-ghg', 2020, 383),
  ('agri-ghg', 2021, 378),
  ('agri-ghg', 2022, 372),
  ('agri-ghg', 2023, 367),
  ('lulucf-net-removal', 2018, -266),
  ('lulucf-net-removal', 2019, -251),
  ('lulucf-net-removal', 2020, -234),
  ('lulucf-net-removal', 2021, -230),
  ('lulucf-net-removal', 2022, -216),
  ('lulucf-net-removal', 2023, -224),
  ('clean-tech-investment', 2019, 175),
  ('clean-tech-investment', 2020, 195),
  ('clean-tech-investment', 2021, 245),
  ('clean-tech-investment', 2022, 305),
  ('clean-tech-investment', 2023, 360),
  ('energy-poverty-share', 2018, 7.3),
  ('energy-poverty-share', 2019, 6.9),
  ('energy-poverty-share', 2020, 7.5),
  ('energy-poverty-share', 2021, 6.9),
  ('energy-poverty-share', 2022, 9.3),
  ('energy-poverty-share', 2023, 10.6),
  ('environmental-employment', 2018, 1.78),
  ('environmental-employment', 2019, 1.83),
  ('environmental-employment', 2020, 1.86),
  ('environmental-employment', 2021, 1.92),
  ('environmental-employment', 2022, 1.98),
  ('environmental-employment', 2023, 2.03),
  ('cattle-population', 2018, 78.1),
  ('cattle-population', 2019, 77.4),
  ('cattle-population', 2020, 76.6),
  ('cattle-population', 2021, 75.5),
  ('cattle-population', 2022, 74.6),
  ('cattle-population', 2023, 73.4),
  ('nitrogen-fertiliser-use', 2018, 10800),
  ('nitrogen-fertiliser-use', 2019, 10650),
  ('nitrogen-fertiliser-use', 2020, 10500),
  ('nitrogen-fertiliser-use', 2021, 10580),
  ('nitrogen-fertiliser-use', 2022, 9700),
  ('nitrogen-fertiliser-use', 2023, 9900),
  ('organic-farming-share', 2018, 7.5),
  ('organic-farming-share', 2019, 8.1),
  ('organic-farming-share', 2020, 9.1),
  ('organic-farming-share', 2021, 9.6),
  ('organic-farming-share', 2022, 10.5),
  ('organic-farming-share', 2023, 10.8),
  ('food-waste-per-capita', 2020, 131),
  ('food-waste-per-capita', 2021, 132),
  ('food-waste-per-capita', 2022, 132),
  ('forest-net-sink', 2018, -344),
  ('forest-net-sink', 2019, -316),
  ('forest-net-sink', 2020, -302),
  ('forest-net-sink', 2021, -287),
  ('forest-net-sink', 2022, -271),
  ('forest-net-sink', 2023, -281),
  ('harvested-wood-pool', 2018, -41),
  ('harvested-wood-pool', 2019, -36),
  ('harvested-wood-pool', 2020, -32),
  ('harvested-wood-pool', 2021, -38),
  ('harvested-wood-pool', 2022, -33),
  ('harvested-wood-pool', 2023, -30),
  ('engineered-cdr-capacity', 2020, 5),
  ('engineered-cdr-capacity', 2021, 10),
  ('engineered-cdr-capacity', 2022, 20),
  ('engineered-cdr-capacity', 2023, 60),
  ('engineered-cdr-capacity', 2024, 130),
  ('battery-mfg-capacity', 2020, 60),
  ('battery-mfg-capacity', 2021, 85),
  ('battery-mfg-capacity', 2022, 140),
  ('battery-mfg-capacity', 2023, 195),
  ('battery-mfg-capacity', 2024, 260),
  ('solar-pv-mfg-capacity', 2020, 6),
  ('solar-pv-mfg-capacity', 2021, 7.5),
  ('solar-pv-mfg-capacity', 2022, 8.5),
  ('solar-pv-mfg-capacity', 2023, 9.5),
  ('solar-pv-mfg-capacity', 2024, 10),
  ('electrolyser-mfg-capacity', 2021, 1),
  ('electrolyser-mfg-capacity', 2022, 2.5),
  ('electrolyser-mfg-capacity', 2023, 4),
  ('electrolyser-mfg-capacity', 2024, 6.5),
  ('clean-tech-trade-balance', 2019, -4),
  ('clean-tech-trade-balance', 2020, -8),
  ('clean-tech-trade-balance', 2021, -15),
  ('clean-tech-trade-balance', 2022, -22),
  ('clean-tech-trade-balance', 2023, -32),
  ('eu-ets-price', 2019, 25),
  ('eu-ets-price', 2020, 25),
  ('eu-ets-price', 2021, 53),
  ('eu-ets-price', 2022, 81),
  ('eu-ets-price', 2023, 84),
  ('eu-ets-price', 2024, 65),
  ('fossil-subsidies', 2018, 56),
  ('fossil-subsidies', 2019, 56),
  ('fossil-subsidies', 2020, 49),
  ('fossil-subsidies', 2021, 56),
  ('fossil-subsidies', 2022, 123),
  ('fossil-subsidies', 2023, 111),
  ('green-bond-issuance', 2019, 110),
  ('green-bond-issuance', 2020, 145),
  ('green-bond-issuance', 2021, 280),
  ('green-bond-issuance', 2022, 240),
  ('green-bond-issuance', 2023, 295),
  ('green-bond-issuance', 2024, 320),
  ('energy-rdd-budget', 2018, 5.5),
  ('energy-rdd-budget', 2019, 5.8),
  ('energy-rdd-budget', 2020, 6.3),
  ('energy-rdd-budget', 2021, 7.5),
  ('energy-rdd-budget', 2022, 9),
  ('energy-rdd-budget', 2023, 10.2),
  ('carbon-pricing-coverage', 2018, 39),
  ('carbon-pricing-coverage', 2020, 41),
  ('carbon-pricing-coverage', 2022, 43),
  ('carbon-pricing-coverage', 2024, 78),
  ('national-climate-laws', 2018, 4),
  ('national-climate-laws', 2020, 8),
  ('national-climate-laws', 2022, 13),
  ('national-climate-laws', 2024, 17),
  ('necp-implementation-score', 2021, 45),
  ('necp-implementation-score', 2022, 50),
  ('necp-implementation-score', 2023, 58),
  ('necp-implementation-score', 2024, 63),
  ('meat-consumption-per-capita', 2018, 70.4),
  ('meat-consumption-per-capita', 2019, 70.2),
  ('meat-consumption-per-capita', 2020, 69.8),
  ('meat-consumption-per-capita', 2021, 70.1),
  ('meat-consumption-per-capita', 2022, 68.5),
  ('meat-consumption-per-capita', 2023, 67.2),
  ('air-passengers-per-capita', 2018, 2.3),
  ('air-passengers-per-capita', 2019, 2.39),
  ('air-passengers-per-capita', 2020, 0.69),
  ('air-passengers-per-capita', 2021, 0.85),
  ('air-passengers-per-capita', 2022, 1.85),
  ('air-passengers-per-capita', 2023, 2.21),
  ('household-energy-per-capita', 2018, 590),
  ('household-energy-per-capita', 2019, 580),
  ('household-energy-per-capita', 2020, 597),
  ('household-energy-per-capita', 2021, 605),
  ('household-energy-per-capita', 2022, 555),
  ('household-energy-per-capita', 2023, 535),
  ('climate-economic-losses', 2018, 16),
  ('climate-economic-losses', 2019, 13),
  ('climate-economic-losses', 2020, 12),
  ('climate-economic-losses', 2021, 56),
  ('climate-economic-losses', 2022, 52),
  ('climate-economic-losses', 2023, 44),
  ('water-exploitation-index', 2018, 5.4),
  ('water-exploitation-index', 2019, 5.5),
  ('water-exploitation-index', 2020, 5.3),
  ('water-exploitation-index', 2021, 5.4),
  ('national-adaptation-strategies', 2018, 20),
  ('national-adaptation-strategies', 2020, 23),
  ('national-adaptation-strategies', 2022, 25),
  ('national-adaptation-strategies', 2024, 26),
  ('international-climate-finance', 2018, 21.7),
  ('international-climate-finance', 2019, 23.2),
  ('international-climate-finance', 2020, 23.4),
  ('international-climate-finance', 2021, 23),
  ('international-climate-finance', 2022, 28.5),
  ('international-climate-finance', 2023, 31.2),
  ('cbam-import-coverage', 2024, 60),
  ('embodied-import-emissions', 2018, 905),
  ('embodied-import-emissions', 2019, 870),
  ('embodied-import-emissions', 2020, 805),
  ('embodied-import-emissions', 2021, 875),
  ('embodied-import-emissions', 2022, 855)
on conflict (indicator_id, year) do nothing;
