-- ─────────────────────────────────────────────────────────────────────────────
-- Backfill the post-report ("afterReport") indicator data points into
-- pw_indicator_points.
--
-- Generated by scripts/esabcc-indicators/build-points-backfill.mjs from the
-- bundled src/data/*-indicators.ts series. The original seed migration
-- (041_seed_esabcc_report_indicators.sql) only went up to 2022; the monthly
-- Eurostat/EEA refresh adds later years to the TS file but the app-level
-- seeder never pushes them into an already-seeded DB. This migration closes
-- that gap.
--
-- Idempotent: on conflict (indicator_id, year) do nothing — only missing
-- years are inserted, existing rows are never overwritten. Re-run after each
-- refresh (the generator overwrites this file with the current years).
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.pw_indicator_points (indicator_id, year, value)
values
  ('esabcc-a1-agri-nonco2', 2023, 359.9),
  ('esabcc-a1-agri-nonco2', 2024, 355.7),
  ('esabcc-b1-buildings-ghg', 2023, 437.3),
  ('esabcc-b1-buildings-ghg', 2024, 430.7),
  ('esabcc-b2-buildings-fec', 2022, 4213.6),
  ('esabcc-b2-buildings-fec', 2023, 4037.9),
  ('esabcc-b5a-residential-fossil-share', 2023, 42.000),
  ('esabcc-b5b-tertiary-fossil-share', 2023, 32.200),
  ('esabcc-b6-heat-pump-stock', 2023, 23.960),
  ('esabcc-b6-heat-pump-stock', 2024, 25.500),
  ('esabcc-e1-energy-supply-ghg', 2023, 746.3),
  ('esabcc-e1-energy-supply-ghg', 2024, 689.1),
  ('esabcc-e2-fossil-power-share', 2023, 33.000),
  ('esabcc-e2-fossil-power-share', 2024, 29.000),
  ('esabcc-e2-fossil-power-share', 2025, 29.000),
  ('esabcc-e2-res-noBio-power-share', 2023, 39.000),
  ('esabcc-e4a-solar-pv-add', 2023, 56.000),
  ('esabcc-e4a-solar-pv-add', 2024, 65.500),
  ('esabcc-e4a-solar-pv-add', 2025, 65.100),
  ('esabcc-e4b-wind-add', 2023, 16.200),
  ('esabcc-e4b-wind-add', 2024, 12.900),
  ('esabcc-e4b-wind-add', 2025, 15.100),
  ('esabcc-e6-energy-ch4', 2022, 64.460),
  ('esabcc-e6-energy-ch4', 2023, 60.050),
  ('esabcc-e6-energy-ch4', 2024, 57.770),
  ('esabcc-f-cleantech-investment', 2023, 0.00070),
  ('esabcc-f-cleantech-investment', 2024, 0.00050),
  ('esabcc-f-cleantech-investment', 2025, 0.00040),
  ('esabcc-f-fossil-subsidies', 2023, 111.0),
  ('esabcc-f-gerd', 2023, 2.2600),
  ('esabcc-f-gerd', 2024, 2.2400),
  ('esabcc-f-green-bonds-share', 2023, 5.3000),
  ('esabcc-f-green-bonds-share', 2024, 6.9000),
  ('esabcc-i1-industry-ghg', 2023, 622.1),
  ('esabcc-i1-industry-ghg', 2024, 611.4),
  ('esabcc-i3-circular-mat-use', 2022, 11.400),
  ('esabcc-i3-circular-mat-use', 2023, 12.100),
  ('esabcc-i3-circular-mat-use', 2024, 12.200),
  ('esabcc-i5-industry-fec', 2022, 2627.8),
  ('esabcc-i5-industry-fec', 2023, 2497.2),
  ('esabcc-i6-industry-electrification', 2022, 33.300),
  ('esabcc-i6-industry-electrification', 2023, 32.600),
  ('esabcc-l1-lulucf-net', 2023, -215.5),
  ('esabcc-l1-lulucf-net', 2024, -231.0),
  ('esabcc-o2-fec', 2022, 10711.2),
  ('esabcc-o2-fec', 2023, 10397.2),
  ('esabcc-o2-fec', 2024, 10467.0),
  ('esabcc-o2-pec', 2022, 14653.8),
  ('esabcc-o2-pec', 2023, 14083.9),
  ('esabcc-o2-pec', 2024, 13979.3),
  ('esabcc-o3-gross-inland', 2022, 16241.1),
  ('esabcc-o3-gross-inland', 2023, 15575.3),
  ('esabcc-t1-transport-ghg', 2023, 901.9),
  ('esabcc-t1-transport-ghg', 2024, 920.0),
  ('esabcc-t4-car-co2-intensity', 2023, 106.4),
  ('esabcc-t5a-zev-share-newcars', 2023, 14.600),
  ('esabcc-t5a-zev-share-newcars', 2024, 13.600)
on conflict (indicator_id, year) do nothing;
